<?php
function s3_status($response,$status){m0_assert(wp_remote_retrieve_response_code($response)===$status,'HTTP '.wp_remote_retrieve_response_code($response).' expected '.$status.': '.substr(strip_tags(preg_replace('~<style.*?</style>~s','',wp_remote_retrieve_body($response))),-450));}
function s3_assignment($id=999232){global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}survey_assignments WHERE id=%d",$id),ARRAY_A);}
function s3_legacy($data=array(),$admin=true){$query=array_merge(array('page'=>'eipsi-results','action'=>'export_participants_excel','study_id'=>999203,'_wpnonce'=>m0_admin_nonce('eipsi_admin_nonce')),$data);return m0_http('/wp-admin/admin.php?'.http_build_query($query),null,$admin);}
function s3_trace(){return json_decode(file_get_contents('/tmp/eipsi-s3-http-trace.json'),true);}
$tests['Wave success retains original field names']=function(){$j=s3_json(s3_request('eipsi_check_wave_state',array('wave_id'=>999222),false,s3_session(),'eipsi_auto_refresh'));m0_assert(array_keys($j['data'])===array('wave_id','wave_name','status','is_locked','seconds_until_available','was_skipped','next_wave_id','available_at','timestamp'),'Wave shape');};
$tests['Wave nonexistent keeps string error']=function(){$j=s3_json(s3_request('eipsi_check_wave_state',array('wave_id'=>999999),false,s3_session(),'eipsi_auto_refresh'));m0_assert(!$j['success']&&$j['data']==='Wave not found','Wave missing');};
$tests['Wave foreign study rejected']=function(){$r=s3_request('eipsi_check_wave_state',array('wave_id'=>999224),false,s3_session(),'eipsi_auto_refresh');s3_status($r,403);m0_assert(!s3_json($r)['success'],'Foreign wave');};
$tests['Wave anonymous rejected']=function(){$r=s3_request('eipsi_check_wave_state',array('wave_id'=>999222),false,null,'eipsi_auto_refresh');s3_status($r,403);};
$tests['Wave invalid nonce rejected']=function(){$r=s3_request('eipsi_check_wave_state',array('wave_id'=>999222,'nonce'=>'invalid'),false,s3_session(),'eipsi_auto_refresh');s3_status($r,403);};
$tests['Wave spoof participant rejected']=function(){$r=s3_request('eipsi_check_wave_state',array('wave_id'=>999222,'participant_id'=>999208),false,s3_session(),'eipsi_auto_refresh');s3_status($r,403);};
$tests['Wave future availability unchanged']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_assignments',array('available_at'=>date('Y-m-d H:i:s',current_time('timestamp')+3600)),array('id'=>999232));$j=s3_json(s3_request('eipsi_check_wave_state',array('wave_id'=>999222),false,s3_session(),'eipsi_auto_refresh'));m0_assert($j['data']['is_locked']&&$j['data']['seconds_until_available']>3590,'Future lock shape');};
$tests['Wave skipped finds next wave within own study']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_assignments',array('status'=>'skipped'),array('id'=>999232));$j=s3_json(s3_request('eipsi_check_wave_state',array('wave_id'=>999222),false,s3_session(),'eipsi_auto_refresh'));m0_assert($j['data']['was_skipped']&&(int)$j['data']['next_wave_id']===999223,'Next wave');};
$tests['Reminder nonce rejected without delivery']=function(){$r=s3_request('eipsi_send_individual_reminder',array('participant_id'=>999207,'wave_id'=>999222,'nonce'=>'invalid'));s3_status($r,403);wp_cache_delete('alloptions','options');m0_assert(!get_option('eipsi_s3_mail'),'Unauthorized mail');};
$tests['Reminder no admin rejected']=function(){$r=s3_request('eipsi_send_individual_reminder',array('participant_id'=>999207,'wave_id'=>999222),false,s3_session());s3_status($r,400);};
$tests['Reminder authenticated subscriber rejected']=function(){global $wpdb;$id=wp_insert_user(array('user_login'=>'s3-subscriber','user_pass'=>'s3-fixture','user_email'=>'s3-subscriber@example.invalid','role'=>'subscriber'));m0_assert(!is_wp_error($id),'Subscriber');try{$token=WP_Session_Tokens::get_instance($id)->create(time()+600);$cookie=wp_generate_auth_cookie($id,time()+600,'logged_in',$token);wp_set_current_user($id);$nonce=wp_create_nonce('eipsi_study_dashboard_nonce');wp_set_current_user(1);$r=wp_remote_post('http://127.0.0.1/wp-admin/admin-ajax.php',array('headers'=>array('Host'=>'127.0.0.1:18080','Cookie'=>LOGGED_IN_COOKIE.'='.$cookie),'body'=>array('action'=>'eipsi_send_individual_reminder','participant_id'=>999207,'wave_id'=>999222,'nonce'=>$nonce),'timeout'=>20));s3_status($r,403);}finally{require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($id);}};
$tests['Reminder foreign wave rejected before delivery']=function(){$r=s3_request('eipsi_send_individual_reminder',array('participant_id'=>999207,'wave_id'=>999224));s3_status($r,403);};
$tests['Reminder own wave without assignment rejected']=function(){$r=s3_request('eipsi_send_individual_reminder',array('participant_id'=>999208,'wave_id'=>999222));s3_status($r,403);};
$tests['Reminder participant missing rejected']=function(){$r=s3_request('eipsi_send_individual_reminder',array('participant_id'=>999999,'wave_id'=>999222));s3_status($r,404);};
$tests['Reminder explicit foreign study rejected']=function(){$r=s3_request('eipsi_send_individual_reminder',array('participant_id'=>999207,'wave_id'=>999222,'study_id'=>999204));s3_status($r,403);};
$tests['Reminder zero wave uses canonical general manual flow']=function(){$j=s3_json(s3_request('eipsi_send_individual_reminder',array('participant_id'=>999207,'wave_id'=>0)));m0_assert($j['success']&&$j['data']['sent_count']===1,'General manual reminder');};
$tests['Reminder delivery failure reported with persisted failed log']=function(){global $wpdb;update_option('eipsi_s3_mail_failure',true);$j=s3_json(s3_request('eipsi_send_individual_reminder',array('participant_id'=>999207,'wave_id'=>999222)));m0_assert(!$j['success']&&$j['data']['sent_count']===0&&$j['data']['failed_count']===1,'Delivery false success');m0_assert($wpdb->get_var("SELECT status FROM {$wpdb->prefix}survey_email_log WHERE survey_id=999203 ORDER BY id DESC LIMIT 1")==='failed','Failed log missing');};
$tests['Reminder inactive participant keeps existing owner rejection']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_participants',array('is_active'=>0),array('id'=>999207));$j=s3_json(s3_request('eipsi_send_individual_reminder',array('participant_id'=>999207,'wave_id'=>999222)));m0_assert(!$j['success'],'Inactive notified');};
$tests['Preview HTTP has zero domain mutations and cron unchanged']=function(){$before=s3_assignment();$cron=get_option('cron');$j=s3_json(s3_request('eipsi_recalculate_preview',array('study_id'=>999203)));m0_assert($j['success']&&s3_assignment()===$before&&s3_trace()===array(),'Preview wrote domain');wp_cache_delete('alloptions','options');m0_assert(get_option('cron')===$cron,'Preview scheduled cron');};
$tests['Preview direct owner performs only reads']=function(){$writes=array();$filter=function($sql)use(&$writes){if(preg_match('/^\s*(INSERT|UPDATE|DELETE|REPLACE|ALTER|CREATE|DROP)/i',$sql)){$writes[]=$sql;}return $sql;};add_filter('query',$filter);try{$r=EIPSI_Longitudinal_T1_Recalculation_Service::preview_study(999203);}finally{remove_filter('query',$filter);}m0_assert(!is_wp_error($r)&&$writes===array(),'Owner preview writes');};
$tests['Preview invalid study rejected']=function(){$r=s3_request('eipsi_recalculate_preview',array('study_id'=>999999));s3_status($r,400);m0_assert(!s3_json($r)['success'],'Invalid preview study');};
$tests['Preview invalid nonce rejected']=function(){s3_status(s3_request('eipsi_recalculate_preview',array('study_id'=>999203,'nonce'=>'invalid')),403);};
$tests['Preview excludes terminal and inactive assignments']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_assignments',array('status'=>'expired'),array('id'=>999233));$j=s3_json(s3_request('eipsi_recalculate_preview',array('study_id'=>999203)));m0_assert($j['data']['waves_to_update']===1,'Terminal preview');$wpdb->update($wpdb->prefix.'survey_participants',array('is_active'=>0),array('id'=>999207));$j=s3_json(s3_request('eipsi_recalculate_preview',array('study_id'=>999203)));m0_assert($j['data']['waves_to_update']===0,'Inactive preview');};
$tests['Apply HTTP delegates minute offsets and preserves T1']=function(){$t1=s3_assignment(999231);$j=s3_json(s3_request('eipsi_recalculate_waves',array('study_id'=>999203)));$a=s3_assignment();m0_assert($j['success']&&$j['data']['waves_to_update']===2&&isset($j['data']['message']),'Apply shape');m0_assert($a['available_at']===date('Y-m-d H:i:s',strtotime($GLOBALS['s3_anchor'])+2880*60)&&$a['due_at']===date('Y-m-d H:i:s',strtotime($a['available_at'])+30*60),'Arithmetic changed');m0_assert(s3_assignment(999231)===$t1,'T1 modified');};
$tests['Apply leaves submitted skipped expired dates intact']=function(){global $wpdb;foreach(array('submitted','skipped','expired')as$status){$wpdb->update($wpdb->prefix.'survey_assignments',array('status'=>$status),array('id'=>999233));$before=s3_assignment(999233);$j=s3_json(s3_request('eipsi_recalculate_waves',array('study_id'=>999203)));m0_assert($j['success']&&s3_assignment(999233)===$before,'Terminal rewritten');}};
$tests['Apply NULL window retains recalc owner NULL deadline']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_waves',array('window_minutes'=>null),array('id'=>999222));$j=s3_json(s3_request('eipsi_recalculate_waves',array('study_id'=>999203)));m0_assert($j['success']&&s3_assignment()['due_at']===null,'Invented window');};
$tests['Apply invalid study rejected']=function(){s3_status(s3_request('eipsi_recalculate_waves',array('study_id'=>999999)),400);};
$tests['Apply nonce rejects without mutations']=function(){$before=s3_assignment();s3_status(s3_request('eipsi_recalculate_waves',array('study_id'=>999203,'nonce'=>'invalid')),403);m0_assert(s3_assignment()===$before,'Unauthorized recalc');};
$tests['Apply audit includes old new values and admin actor']=function(){global $wpdb;$j=s3_json(s3_request('eipsi_recalculate_waves',array('study_id'=>999203)));$row=$wpdb->get_row("SELECT * FROM {$wpdb->prefix}survey_audit_log WHERE survey_id=999203 ORDER BY id DESC LIMIT 1");$metadata=json_decode($row->metadata,true);m0_assert($j['success']&&$row->actor_type==='admin'&&(int)$row->actor_id===1&&isset($metadata['old_value'],$metadata['new_value'],$metadata['batch_id']),'Audit contract');};
$tests['Apply cron refresh occurs after COMMIT']=function(){$j=s3_json(s3_request('eipsi_recalculate_waves',array('study_id'=>999203)));$trace=s3_trace();$commit=array_search('COMMIT',$trace,true);$queue=array_search('UPDATE:survey_nudge_jobs',$trace,true);m0_assert($j['success']&&$commit!==false&&$queue!==false&&$commit<$queue,'Refresh before commit');};
$tests['Dashboard own session payload matches consumer']=function(){$j=s3_json(s3_request('eipsi_get_participant_dashboard',array(),false,s3_session(),'eipsi_participant_dashboard'));m0_assert($j['success']&&$j['data']['completed_waves']===1&&$j['data']['pending_waves']===2&&$j['data']['progress_percentage']===33&&count($j['data']['timeline'])===3,'Dashboard shape');};
$tests['Dashboard foreign participant rejected']=function(){s3_status(s3_request('eipsi_get_participant_dashboard',array('participant_id'=>999208),false,s3_session(),'eipsi_participant_dashboard'),403);};
$tests['Dashboard foreign study rejected']=function(){s3_status(s3_request('eipsi_get_participant_dashboard',array('study_id'=>999204),false,s3_session(),'eipsi_participant_dashboard'),403);};
$tests['Dashboard anonymous rejected']=function(){s3_status(s3_request('eipsi_get_participant_dashboard',array(),false,null,'eipsi_participant_dashboard'),403);};
$tests['Dashboard admin without participant session rejected']=function(){s3_status(s3_request('eipsi_get_participant_dashboard',array('participant_id'=>999207),true,null,'eipsi_participant_dashboard'),403);};
$tests['Dashboard invalid nonce rejected']=function(){s3_status(s3_request('eipsi_get_participant_dashboard',array('nonce'=>'bad'),false,s3_session(),'eipsi_participant_dashboard'),403);};
$tests['Dashboard inactive participant rejected']=function(){global $wpdb;$session=s3_session();$wpdb->update($wpdb->prefix.'survey_participants',array('is_active'=>0),array('id'=>999207));s3_status(s3_request('eipsi_get_participant_dashboard',array(),false,$session,'eipsi_participant_dashboard'),403);};
$tests['Dashboard response does not expose credentials or email']=function(){$j=s3_json(s3_request('eipsi_get_participant_dashboard',array(),false,s3_session(),'eipsi_participant_dashboard'));$raw=wp_json_encode($j);m0_assert(strpos($raw,'password')===false&&strpos($raw,'token')===false&&strpos($raw,'@example.invalid')===false,'PII dashboard');};
$tests['Legacy XLSX unauthorized redirect or forbidden']=function(){$r=s3_legacy(array(),false);m0_assert(in_array(wp_remote_retrieve_response_code($r),array(302,403),true)&&strpos(wp_remote_retrieve_body($r),'PK')!==0,'Public XLSX');};
$tests['Legacy XLSX missing nonce denied']=function(){s3_status(s3_legacy(array('_wpnonce'=>'')),403);};
$tests['Legacy XLSX wrong nonce denied']=function(){s3_status(s3_legacy(array('_wpnonce'=>'invalid')),403);};
$tests['Legacy XLSX valid stream columns and canonical filename']=function(){$r=s3_legacy();s3_status($r,200);$body=wp_remote_retrieve_body($r);m0_assert(substr($body,0,2)==='PK','XLSX not ZIP');m0_assert(strpos(wp_remote_retrieve_header($r,'content-type'),'spreadsheetml')!==false&&strpos(wp_remote_retrieve_header($r,'content-disposition'),'participantes-wide-999203-')!==false,'Stream headers');$tmp=tempnam('/tmp','s3-xlsx-');file_put_contents($tmp,$body);$zip=new ZipArchive();try{m0_assert($zip->open($tmp)===true,'ZIP');$xml=$zip->getFromName('xl/worksheets/sheet1.xml').$zip->getFromName('xl/sharedStrings.xml');m0_assert(strpos($xml,'Email')!==false&&strpos($xml,'T1')!==false&&strpos($xml,'T1_submitted_at')!==false,'Expected columns missing');}finally{$zip->close();unlink($tmp);}};
$tests['Legacy XLSX invalid study rejected']=function(){s3_status(s3_legacy(array('study_id'=>999999)),404);};
$tests['Legacy XLSX filters apply to existing roster']=function(){$r=s3_legacy(array('search'=>'s3-999207'));s3_status($r,200);$tmp=tempnam('/tmp','s3-xlsx-');file_put_contents($tmp,wp_remote_retrieve_body($r));$zip=new ZipArchive();try{m0_assert($zip->open($tmp)===true,'ZIP');$xml=$zip->getFromName('xl/worksheets/sheet1.xml').$zip->getFromName('xl/sharedStrings.xml');m0_assert(strpos($xml,'s3-999207')!==false&&strpos($xml,'s3-999208')===false,'Filter ignored');}finally{$zip->close();unlink($tmp);}};
$tests['LONG remains unresolved without aliases']=function(){m0_assert(!has_action('wp_ajax_eipsi_export_participants_long_excel')&&!has_action('wp_ajax_eipsi_export_participants_long_csv'),'Invented LONG');$source=file_get_contents(EIPSI_FORMS_PLUGIN_DIR.'admin/tabs/export-tab.php');m0_assert(strpos($source,'id="ep-download-excel-long"')===false&&strpos($source,'id="ep-download-csv-long"')===false,'LONG UI falsely restored');};
$tests['Rollback remains dormant without invented handler']=function(){m0_assert(!has_action('wp_ajax_eipsi_rollback_recalculation'),'Invented rollback');};
$tests['Admin repaired actions never register nopriv']=function(){foreach(array('eipsi_send_individual_reminder','eipsi_recalculate_preview','eipsi_recalculate_waves')as$action){m0_assert(!has_action('wp_ajax_nopriv_'.$action),'Public admin action');}};
require __DIR__.'/concurrency.php';
$tests['Apply waits on real assignment lock and rereads terminal status']=function(){$before=s3_assignment();$results=s3_concurrent(array('apply'),array('status'=>'submitted'));$after=s3_assignment();m0_assert($results[0]['result']['waves_to_update']===1&&$after['status']==='submitted'&&$after['available_at']===$before['available_at']&&$after['due_at']===$before['due_at'],'Stale recalc overwrote terminal');};
$tests['Two real apply workers serialize without stale audit dates']=function(){global $wpdb;$results=s3_concurrent(array('apply','apply'));foreach($results as$r){m0_assert(!isset($r['result']['error'])&&$r['result']['waves_to_update']===2,'Concurrent apply failed');}$audit=$wpdb->get_results("SELECT metadata FROM {$wpdb->prefix}survey_audit_log WHERE survey_id=999203 ORDER BY id");$count=0;foreach($audit as$row){$m=json_decode($row->metadata,true);if((int)$m['wave_id']===999222){$count++;if($count===2){m0_assert($m['old_value']===$m['new_value'],'Second worker stale audit');}}}m0_assert($count===2,'Audit count');};
$tests['Concurrent submit and apply preserve submitted outcome']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_waves',array('offset_minutes'=>1430),array('id'=>999222));$results=s3_concurrent(array('apply','submit'));m0_assert(s3_assignment()['status']==='submitted','Lost submission: '.wp_json_encode($results));foreach($results as$r){m0_assert(!isset($r['result']['error']),'Concurrent mutation failed');}};
foreach(array('update','audit')as$operation){$tests['Apply '.$operation.' SQL failure rolls back assignment']=function()use($operation){global $wpdb;$before=s3_assignment();$fired=false;$filter=function($sql)use($operation,&$fired){$match=$operation==='update'?preg_match('/^UPDATE.*survey_assignments.*available_at/is',$sql):preg_match('/^INSERT.*survey_audit_log/is',$sql);if($match&&!$fired){$fired=true;return 'SELECT eipsi_s3_controlled_missing_column';}return $sql;};$wpdb->suppress_errors(true);add_filter('query',$filter);try{$r=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_study(999203,1);}finally{remove_filter('query',$filter);$wpdb->suppress_errors(false);}m0_assert($fired&&is_wp_error($r)&&$r->get_error_data()['updated']===0&&s3_assignment()===$before,'Failed recalc persisted');};}
$tests['Postcommit refresh failure reports persisted partial result']=function(){global $wpdb;$before=s3_assignment();$fired=false;$filter=function($sql)use(&$fired){if(!$fired&&preg_match('/^UPDATE.*survey_nudge_jobs/is',$sql)){$fired=true;return 'SELECT eipsi_s3_controlled_missing_column';}return $sql;};$wpdb->suppress_errors(true);add_filter('query',$filter);try{$r=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_study(999203,1);}finally{remove_filter('query',$filter);$wpdb->suppress_errors(false);}m0_assert($fired&&is_wp_error($r)&&$r->get_error_code()==='refresh_failed'&&$r->get_error_data()['updated']===1&&s3_assignment()['available_at']!==$before['available_at'],'Partial result hidden');};
foreach(json_decode(file_get_contents(__DIR__.'/consumer-requests.json'),true)as$key=>$fixture){$tests['Executed JS fixture to HTTP handler owner response: '.$key]=function()use($key,$fixture){$participant=in_array($key,array('wave','dashboard'),true);$r=s3_request($fixture['action'],$fixture['data'],!$participant,$participant?s3_session():null,$fixture['nonce_action']);s3_status($r,200);$j=s3_json($r);m0_assert($j['success'],'Actual JS request failed');if($key==='preview'){m0_assert($j['data']===array('affected_participants'=>1,'waves_to_update'=>2),'Preview response');}elseif($key==='dashboard'){m0_assert($j['data']['progress_percentage']===33,'Dashboard render field');}elseif($key==='reminder'){m0_assert($j['data']['sent_count']===1,'Actual reminder failed');}elseif($key==='apply'){m0_assert(isset($j['data']['message'])&&$j['data']['waves_to_update']===2,'Apply render field');}else{m0_assert($j['data']['wave_name']==='S3 T2','Polling response');}};}
$tests['Legacy XLSX generation SQL failure returns 500 not file']=function(){update_option('eipsi_s3_export_sql_failure',true);$r=s3_legacy();s3_status($r,500);m0_assert(substr(wp_remote_retrieve_body($r),0,2)!=='PK','False XLSX stream');};
$tests['Legacy XLSX stream removes only its generated file']=function(){$before=glob(EIPSI_FORMS_PLUGIN_DIR.'exports/*');$r=s3_legacy();s3_status($r,200);m0_assert(glob(EIPSI_FORMS_PLUGIN_DIR.'exports/*')===$before,'Export left behind or deleted unrelated file');};
$tests['Preview and apply use submitted T1 fallback anchor']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_participants',array('t1_completed_at'=>null),array('id'=>999207));$preview=EIPSI_Longitudinal_T1_Recalculation_Service::preview_study(999203);m0_assert($preview['waves_to_update']===2,'Fallback preview');$r=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_study(999203,1);m0_assert(!is_wp_error($r)&&s3_assignment()['available_at']===date('Y-m-d H:i:s',strtotime($GLOBALS['s3_anchor'])+2880*60),'Fallback apply');};
$tests['Unanchored participant never receives invented dates']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_participants',array('t1_completed_at'=>null),array('id'=>999207));$wpdb->update($wpdb->prefix.'survey_assignments',array('status'=>'pending','submitted_at'=>null),array('id'=>999231));$before=s3_assignment();$r=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_study(999203,1);m0_assert(!is_wp_error($r)&&$r['waves_to_update']===0&&s3_assignment()===$before,'Invented anchor');};
$tests['Apply missing nonce and participant session cannot authorize admin mutation']=function(){$before=s3_assignment();s3_status(s3_request('eipsi_recalculate_waves',array('study_id'=>999203,'nonce'=>'')),403);s3_status(s3_request('eipsi_recalculate_waves',array('study_id'=>999203),false,s3_session()),400);m0_assert(s3_assignment()===$before,'Public mutation');};
$tests['Wave invalid participant token rejected']=function(){$session=s3_session();$session['token']='invalid-participant-token';s3_status(s3_request('eipsi_check_wave_state',array('wave_id'=>999222),false,$session,'eipsi_auto_refresh'),403);};
