<?php
/** Characterization on real WordPress/MariaDB; no schema mocks. */
if(PHP_SAPI!=='cli'||!function_exists('m0_assert')){exit;}
require_once EIPSI_FORMS_PLUGIN_DIR.'includes/services/Wave_Service.php';
require __DIR__.'/concurrency.php';
function m4_context($wave=992221){return array('wave_id'=>$wave,'study_id'=>992203,'longitudinal_participant_id'=>992207,'stable_form_id'=>'m2-long-form','submitted_at'=>current_time('mysql'),'user_data'=>array('email'=>'m2-a@example.invalid'));}
function m4_assignment($id=992231){global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}survey_assignments WHERE id=%d",$id));}
function m4_set($id,$data){global $wpdb;m0_assert($wpdb->update($wpdb->prefix.'survey_assignments',$data,array('id'=>$id))!==false,$wpdb->last_error);}
function m4_admin($action,$data=array(),$nonce='eipsi_study_dashboard_nonce'){$j=m4_json(m0_http('/wp-admin/admin-ajax.php',array_merge(array('action'=>$action,'nonce'=>m0_admin_nonce($nonce)),$data),true));return $j;}
function m4_tokens($source){$out='';foreach(token_get_all('<?php '.$source) as $t){if(is_array($t)){if(in_array($t[0],array(T_OPEN_TAG,T_WHITESPACE,T_COMMENT,T_DOC_COMMENT),true)){continue;}$out.=$t[1];}else{$out.=$t;}}return $out;}
function m4_method_source($class,$method){$r=new ReflectionMethod($class,$method);$lines=file($r->getFileName());return implode('',array_slice($lines,$r->getStartLine()-1,$r->getEndLine()-$r->getStartLine()+1));}
$tests['M4 public facades retain frozen signatures and defaults']=function(){foreach(json_decode(file_get_contents(__DIR__.'/contracts.json'),true)['signatures'] as $class=>$methods){foreach($methods as $name=>$signature){$source=m4_method_source($class,$name);m0_assert(m4_tokens(substr($source,0,strpos($source,'{')))===m4_tokens($signature),'Signature changed '.$class.'::'.$name);}}};
$tests['M4 critical Wave, recalculation and notification bodies retain baseline tokens']=function(){foreach(json_decode(file_get_contents(__DIR__.'/contracts.json'),true)['bodies'] as $row){$source=m4_method_source($row['class'],$row['method']);$body=substr($source,strpos($source,'{')+1,strrpos($source,'}')-strpos($source,'{')-1);if($row['class']==='Wave_Service'&&$row['method']==='maybe_send_immediate_wave_reminder'){
    // M5 splits temporal calculations and notification scheduling without changing the frozen rule.
    $source=m4_method_source('EIPSI_Longitudinal_Notification_Context_Service','notify_submission');
    $body=substr($source,strpos($source,'{')+1,strrpos($source,'}')-strpos($source,'{')-1);
    $notification=m4_method_source('EIPSI_Notification_Longitudinal_Adapter','notify_available_context');
    $notification=substr($notification,strpos($notification,'// Only send if'),strrpos($notification,'}')-strpos($notification,'// Only send if'));
    $bridge="return EIPSI_Notification_Longitudinal_Adapter::notify_available_context(compact('next_assignment','now','available_at'));";
    m0_assert(strpos($body,$bridge)!==false,'M5 context bridge changed');$body=str_replace($bridge,$notification,$body);
}
m0_assert(m4_tokens($body)===m4_tokens($row['body']),'Rule changed '.$row['class'].'::'.$row['method']);}};
$tests['M4 Forms has no longitudinal SQL and command facade preserves context']=function(){$forms=glob(EIPSI_FORMS_PLUGIN_DIR.'includes/forms/*.php');foreach($forms as $file){m0_assert(!preg_match('/FOR UPDATE|START TRANSACTION|UPDATE.*survey_assignments/',file_get_contents($file)),'Longitudinal SQL leaked into Forms');}$facade=file_get_contents(EIPSI_FORMS_PLUGIN_DIR.'admin/services/class-form-longitudinal-submit-adapter.php');m0_assert(strpos($facade,'EIPSI_Longitudinal_Submission_Service::handle_submission')!==false && strpos($facade,'$wpdb')===false,'Submit facade contains policy');};
$tests['Study wizard creates active study with weekly config and owned page']=function(){global $wpdb,$posts,$form;$data=array('step_1'=>array('study_code'=>'m4-created','study_name'=>'M4 created','description'=>'fixture','principal_investigator_id'=>1),'step_2'=>array('waves_config'=>array(array('name'=>'M4 created T1','wave_index'=>1,'form_template_id'=>$form))),'step_3'=>array('study_end_offset_minutes'=>240),'step_4'=>array());$id=eipsi_create_study_from_wizard($data);m0_assert($id,'Study creation failed');$GLOBALS['m4_owned_studies'][]=$id;$row=EIPSI_Longitudinal_Study_Repository::get($id);m0_assert($row->status==='active'&&(int)$row->study_end_offset_minutes===240,'Study state changed');m0_assert(json_decode($row->config,true)['weekly_reminders']['enabled'],'Weekly config lost');m0_assert(count(EIPSI_Wave_Service::get_study_waves($id))===1,'Wizard did not create T1');$pages=get_posts(array('post_type'=>'page','meta_key'=>'eipsi_study_id','meta_value'=>$id,'post_status'=>'any'));m0_assert(count($pages)===1,'Owned study page missing');foreach($pages as $page){$posts[]=$page->ID;}};
$tests['Study pause and resume preserve public status contract']=function(){m0_assert(EIPSI_Longitudinal_Study_Service::set_status(992203,'paused')!==false,'Pause failed');m0_assert(EIPSI_Longitudinal_Study_Repository::get(992203)->status==='paused','Pause not persisted');m0_assert(EIPSI_Longitudinal_Study_Service::set_status(992203,'active')!==false,'Resume failed');};
$tests['HTTP study close preserves completed payload and state']=function(){$j=m4_admin('eipsi_close_study',array('study_id'=>992203));m0_assert($j['success']&&$j['data']['status']==='completed','Close payload changed');m0_assert(EIPSI_Longitudinal_Study_Repository::get(992203)->status==='completed','Close not persisted');};
$tests['HTTP longitudinal dashboard overview remains reachable']=function(){$nonce=m0_admin_nonce('eipsi_study_dashboard_nonce');$j=m4_json(m0_http('/wp-admin/admin-ajax.php?action=eipsi_get_study_overview&study_id=992203&nonce='.rawurlencode($nonce),null,true));m0_assert($j['success'],'Overview failed');};
$tests['HTTP cron config still renders original tab']=function(){$nonce=m0_admin_nonce('eipsi_study_dashboard_nonce');$j=m4_json(m0_http('/wp-admin/admin-ajax.php?action=eipsi_get_study_cron_config&study_id=992203&nonce='.rawurlencode($nonce),null,true));m0_assert($j['success']&&!empty($j['data']['html']),'Moved include broke cron tab');};
$tests['Wave creation and deletion retain base-one and minute fields']=function(){global $form;$id=EIPSI_Wave_Service::create_wave(992203,array('wave_index'=>4,'name'=>'M4 create','form_id'=>$form,'offset_minutes'=>137,'window_minutes'=>23,'status'=>'active'));m0_assert(is_int($id),'Create wave failed');try{$w=EIPSI_Wave_Service::get_wave($id);m0_assert((int)$w->wave_index===4&&(int)$w->offset_minutes===137&&(int)$w->window_minutes===23,'Minute fields changed');m0_assert(!is_wp_error(EIPSI_Wave_Service::delete_wave($id)),'Unassigned delete failed');}finally{global $wpdb;$wpdb->delete($wpdb->prefix.'survey_waves',array('id'=>$id));}};
$tests['Wave zero and duplicate indexes are rejected']=function(){global $form;foreach(array(0,1) as $index){m0_assert(is_wp_error(EIPSI_Wave_Service::create_wave(992203,array('wave_index'=>$index,'name'=>'invalid','form_id'=>$form))),'Bad index accepted');}};
$tests['Wave T1 T2 T3 remain exactly one two three']=function(){m0_assert(array_map(function($w){return (int)$w['wave_index'];},EIPSI_Wave_Service::get_study_waves(992203))===array(1,2,3),'Index shifted');};
$tests['Wave allowed name edit persists without touching assignments']=function(){global $wpdb;$before=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}survey_assignments WHERE study_id=992203",ARRAY_A);m0_assert(!is_wp_error(EIPSI_Wave_Service::update_wave(992222,array('name'=>'M4 edited'))),'Allowed edit blocked');m0_assert(EIPSI_Wave_Service::get_wave(992222)->name==='M4 edited','Edit ignored');m0_assert($before===$wpdb->get_results("SELECT * FROM {$wpdb->prefix}survey_assignments WHERE study_id=992203",ARRAY_A),'Edit changed assignments');};
foreach(array('wave_index'=>3,'form_id'=>999999,'start_date'=>'2026-10-20T12:00','due_date'=>'2026-10-21T12:00') as $field=>$value){$tests['Wave assigned or immutable field blocked: '.$field]=function()use($field,$value){m0_assert(is_wp_error(EIPSI_Wave_Service::update_wave(992222,array($field=>$value))),'Protected field changed');};}
$tests['Wave deletion with submitted responses is blocked']=function(){m4_set(992232,array('status'=>'submitted'));m0_assert(is_wp_error(EIPSI_Wave_Service::delete_wave(992222)),'Assigned wave deleted');};
$tests['Assignment creation returns id and duplicate returns existing record']=function(){global $wpdb;$id=EIPSI_Assignment_Service::create_assignment(992203,992222,992208);m0_assert(is_int($id),'Assignment creation failed');try{$old=$wpdb->suppress_errors(true);$duplicate=EIPSI_Assignment_Service::create_assignment(992203,992222,992208);$wpdb->suppress_errors($old);m0_assert(is_array($duplicate)&&(int)$duplicate['id']===$id,'Duplicate contract changed');m0_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_assignments WHERE wave_id=992222 AND participant_id=992208")===1,'Duplicate persisted');}finally{$wpdb->delete($wpdb->prefix.'survey_assignments',array('id'=>$id));}};
$tests['Assignment rejects wave from another study']=function(){m0_assert(is_wp_error(EIPSI_Assignment_Service::create_assignment(992204,992221,992208)),'Study mismatch accepted');};
$tests['Assignment in_progress sets first_viewed_at only once']=function(){m0_assert(EIPSI_Assignment_Service::update_assignment_status(992221,992207,'in_progress')===true,'Transition failed');$first=m4_assignment()->first_viewed_at;m0_assert($first,'Missing first view');m0_assert(EIPSI_Assignment_Service::update_assignment_status(992221,992207,'in_progress')===true && m4_assignment()->first_viewed_at===$first,'First view overwritten');};
$tests['Assignment invalid status remains rejected']=function(){m0_assert(is_wp_error(EIPSI_Assignment_Service::update_assignment_status(992221,992207,'invented')),'Invalid status accepted');};
$tests['Manual completion preserves submitted_at']=function(){m0_assert(EIPSI_Assignment_Service::mark_wave_completed(992231)===true,'Manual completion failed');m0_assert(m4_assignment()->status==='submitted'&&m4_assignment()->submitted_at,'Missing timestamp');};
$tests['Locked T1 submission commits state and T1 timestamp']=function(){$result=EIPSI_Longitudinal_Assignment_Transition_Service::submit_locked(992207,992203,992221);$a=m4_assignment();m0_assert($result===true&&$a->status==='submitted'&&$a->submitted_at&&$a->t1_completed_at,'T1 transaction incomplete');};
$tests['Locked T2 submission does not become T1']=function(){m0_assert(EIPSI_Longitudinal_Assignment_Transition_Service::submit_locked(992207,992203,992222)===false,'T2 treated as T1');m0_assert(m4_assignment(992232)->status==='submitted'&&m4_assignment(992232)->t1_completed_at===null,'T2 timestamp changed');};
$tests['Repeated locked submission rejected with preserved 500 envelope']=function(){EIPSI_Longitudinal_Assignment_Transition_Service::submit_locked(992207,992203,992221);$r=EIPSI_Longitudinal_Assignment_Transition_Service::submit_locked(992207,992203,992221);m0_assert($r['success']===false&&$r['status']===500&&isset($r['data']['message'],$r['data']['error']),'Retry error changed');};
$tests['Real transaction rolls back submitted state if T1 timestamp write fails']=function(){global $wpdb;$queries=array();$filter=function($q)use(&$queries,$wpdb){$queries[]=$q;if(strpos($q,'UPDATE `'.$wpdb->prefix.'survey_assignments`')===0&&strpos($q,'`t1_completed_at`')!==false){return 'UPDATE eipsi_m4_missing_table SET x=1';}return $q;};$old=$wpdb->suppress_errors(true);add_filter('query',$filter);try{$r=EIPSI_Longitudinal_Assignment_Transition_Service::submit_locked(992207,992203,992221);}finally{remove_filter('query',$filter);$wpdb->suppress_errors($old);}m0_assert(is_array($r)&&!$r['success']&&m4_assignment()->status==='pending'&&m4_assignment()->t1_completed_at===null,'Rollback failed');m0_assert(in_array('START TRANSACTION',$queries,true)&&in_array('ROLLBACK',$queries,true)&&strpos(implode('\n',$queries),'FOR UPDATE')!==false,'Lock/rollback path omitted');};
$tests['Recalculation preserves T1 and minute offset/window']=function(){m4_set(992231,array('status'=>'submitted','t1_completed_at'=>'2026-10-05 12:00:00'));$before=m4_assignment();$r=EIPSI_Wave_Recalculator::recalculate_after_t1(992207,992203,'2026-10-05 12:00:00');m0_assert($r['success']&&count($r['affected_waves'])===2,'Recalculation failed');$a=m4_assignment(992232);m0_assert($a->available_at==='2026-10-05 13:00:00'&&$a->due_at==='2026-10-05 13:30:00','Minute arithmetic changed');m0_assert(m4_assignment()==$before,'T1 overwritten');};
$tests['Recalculation no window preserves NULL deadline']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_waves',array('window_minutes'=>null),array('id'=>992223));EIPSI_Wave_Recalculator::recalculate_after_t1(992207,992203,'2026-10-05 12:00:00');m0_assert(m4_assignment(992233)->due_at===null,'Invented deadline');};
$tests['Single wave recalculation retains minutes and other waves']=function(){$before=m4_assignment(992233);m0_assert(EIPSI_Wave_Recalculator::recalculate_single_wave(992207,992222,'2026-10-05 12:00:00'),'Single recalculation failed');m0_assert(m4_assignment(992232)->available_at==='2026-10-05 13:00:00'&&m4_assignment(992233)==$before,'Wrong wave changed');};
$tests['Recalculation invalid T1 date is rejected']=function(){$r=EIPSI_Wave_Recalculator::recalculate_after_t1(992207,992203,'invalid');m0_assert(!$r['success']&&!empty($r['errors']),'Bad date accepted');};
$tests['T1 anchor emits event after participant timestamp is persisted']=function(){global $wpdb;$stamp='2026-10-05 12:00:00';m4_set(992231,array('status'=>'submitted','submitted_at'=>$stamp,'t1_completed_at'=>$stamp));$events=array();$cb=function($study,$participant)use(&$events,$wpdb){$events[]=array($study,$participant,$wpdb->get_var("SELECT t1_completed_at FROM {$wpdb->prefix}survey_participants WHERE id=992207"));};add_action('eipsi_t1_anchored',$cb,99,3);try{$r=EIPSI_T1_Anchor_Service::anchor_participant_timeline(992203,992207);}finally{remove_action('eipsi_t1_anchored',$cb,99);}m0_assert(!is_wp_error($r)&&count($events)===1&&$events[0][2]===$stamp,'T1 event order changed');};
$tests['T1 already anchored is stable and force remains explicit']=function(){m4_set(992231,array('status'=>'submitted','submitted_at'=>'2026-10-05 12:00:00'));$r=EIPSI_T1_Anchor_Service::anchor_participant_timeline(992203,992207);m0_assert(!is_wp_error($r),'Anchor failed');m0_assert(is_wp_error(EIPSI_T1_Anchor_Service::manual_anchor(992203,992207,'2026-10-06 12:00:00',false)),'Manual overwrite allowed without force');};
$tests['Status changed hook retains T1 consumer and no new automatic emit']=function(){m0_assert(has_action('eipsi_assignment_status_changed',array('EIPSI_T1_Anchor_Service','on_assignment_status_changed'))===10,'T1 listener lost');$events=0;$cb=function()use(&$events){$events++;};add_action('eipsi_assignment_status_changed',$cb);try{EIPSI_Assignment_Service::update_assignment_status(992221,992207,'submitted');m0_assert($events===0,'Invented event emission');do_action('eipsi_assignment_status_changed',992221,992207,'submitted');m0_assert($events===1,'Existing event contract lost');}finally{remove_action('eipsi_assignment_status_changed',$cb);}};
$tests['Next wave array and object facade formats stay distinct']=function(){m4_set(992231,array('status'=>'submitted'));$array=Wave_Service::get_next_pending_wave(992207,992203);$object=EIPSI_Wave_Service::get_next_pending_wave(992207,992203);m0_assert(is_array($array)&&isset($array['wave_id'],$array['wave_index'],$array['wave_name'])&&(int)$array['wave_index']===2,'Array payload changed');m0_assert(is_object($object)&&(int)$object->wave_index===2,'Object facade changed');};
$tests['Longitudinal command retains next-wave payload and millisecond countdown']=function(){$before=current_time('timestamp');$r=EIPSI_Longitudinal_Submission_Service::handle_submission(m4_context());m0_assert($r['has_next_wave']&&array_keys($r)===array('next_wave_data','has_next_wave','nudge_0_sent','nudge_0_message'),'Command envelope changed');$next=$r['next_wave_data'];m0_assert(array_keys($next)===array('wave_index','due_date','wave_name','offset_minutes','interval_days','reminder_days','time_unit','available_at')&&(int)$next['wave_index']===2&&$next['offset_minutes']===60,'Next-wave fields changed');m0_assert($next['available_at']>=($before+3600)*1000 && $next['available_at']<=($before+3605)*1000,'Countdown units changed');};
$tests['Final wave completes without inventing next wave']=function(){m4_set(992231,array('status'=>'submitted'));m4_set(992232,array('status'=>'submitted'));$r=EIPSI_Longitudinal_Submission_Service::handle_submission(m4_context(992223));m0_assert(!$r['has_next_wave']&&$r['next_wave_data']===null&&m4_assignment(992233)->status==='submitted','Completion changed');};
$tests['Expired snapshot transitions once and stale snapshot cannot clobber submit']=function(){$old=m4_assignment();m0_assert(EIPSI_Longitudinal_Assignment_Transition_Service::expire_snapshot($old)===1,'Expire failed');m0_assert(EIPSI_Longitudinal_Assignment_Transition_Service::expire_snapshot($old)===0,'Double transition');m4_set(992231,array('status'=>'submitted'));m0_assert(EIPSI_Longitudinal_Assignment_Transition_Service::change_snapshot(992231,'pending','skipped')===0&&m4_assignment()->status==='submitted','Stale snapshot clobbered submit');};
$tests['Expiration service retains pending selector and post-state event']=function(){m4_set(992231,array('due_at'=>'2020-01-01 00:00:00'));m4_set(992232,array('status'=>'in_progress','due_at'=>'2020-01-01 00:00:00'));$seen=array();$cb=function($id)use(&$seen){$seen[]=m4_assignment($id)->status;};add_action('eipsi_wave_expired',$cb);try{$r=EIPSI_Wave_Expiration_Service::process_expirations();}finally{remove_action('eipsi_wave_expired',$cb);}m0_assert($r['expired_count']===1&&$seen===array('expired')&&m4_assignment(992232)->status==='in_progress','Expiration selector/event changed');};
$tests['Manual expiration rejects submitted assignment']=function(){m4_set(992231,array('status'=>'submitted'));$r=EIPSI_Wave_Expiration_Service::manual_expire(992231);m0_assert(is_wp_error($r)&&$r->get_error_code()==='already_submitted','Manual expired submit');};
$tests['Expiration cron adapter preserves broader in_progress selector']=function(){m4_set(992233,array('status'=>'in_progress','due_at'=>'2020-01-01 00:00:00'));eipsi_run_process_assignment_expirations();m0_assert(m4_assignment(992233)->status==='expired','Cron selector changed');};
$tests['Skipping cron adapter protects T1 and skips older T2']=function(){m4_set(992233,array('available_at'=>'2020-01-01 00:00:00'));m0_assert(eipsi_check_wave_skipping_for_participant(992207,992203)===1,'Skip count changed');m0_assert(m4_assignment()->status==='pending'&&m4_assignment(992232)->status==='skipped'&&m4_assignment(992233)->status==='pending','Skipping rules changed');};
$tests['Auto expired skipping preserves existing T1 behavior and wave_available event']=function(){m4_set(992231,array('status'=>'expired'));$events=array();$cb=function($id)use(&$events){$events[]=$id;};add_action('eipsi_wave_available',$cb);try{eipsi_auto_skip_expired_waves();}finally{remove_action('eipsi_wave_available',$cb);}m0_assert(m4_assignment()->status==='skipped','Existing auto-expired T1 policy changed');m0_assert(!empty($events),'Wave available event lost');};
$tests['Availability cron repository selects only T2+ due availability']=function(){m4_set(992231,array('available_at'=>'2020-01-01 00:00:00'));m4_set(992232,array('available_at'=>'2020-01-01 00:00:00'));$rows=EIPSI_Longitudinal_Assignment_Repository::get_newly_available(current_time('mysql'));m0_assert(count($rows)===1&&(int)$rows[0]->wave_id===992222,'Availability selector changed');};
$tests['Manual deadline extension by days preserves exact delta']=function(){m4_set(992232,array('due_at'=>'2026-10-05 13:30:00'));m0_assert(EIPSI_Assignment_Service::extend_wave_deadline(992232,2)===true&&m4_assignment(992232)->due_at==='2026-10-07 13:30:00','Deadline delta changed');};
$tests['HTTP manual deadline and removal remain compatible']=function(){$j=m4_admin('eipsi_extend_wave_deadline',array('wave_id'=>992222,'deadline_date'=>'2026-12-20'));m0_assert($j['success'],'Manual deadline failed');m0_assert(m4_assignment(992232)->due_at==='2026-12-20 23:59:59','Deadline ignored');$j=m4_admin('eipsi_remove_wave_deadline',array('wave_id'=>992222));m0_assert($j['success'],'Remove deadline failed');};
$tests['HTTP anonymous submit persists through unchanged Forms contract']=function(){global $wpdb;$j=m4_json(m4_ajax('eipsi_forms_submit_form',array('form_id'=>'m4-anonymous','participant_id'=>'m4-anonymous','session_id'=>'m4-anonymous-session','answer'=>'4'),null,'eipsi_forms_nonce'));m0_assert($j['success']&&(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}vas_form_results WHERE participant_id='m4-anonymous'")===1,'Anonymous submit changed');$wpdb->delete($wpdb->prefix.'vas_form_results',array('participant_id'=>'m4-anonymous'));};
$tests['Pools completion callback and helper use numeric identity only']=function(){global $wpdb;$session=m4_session();m0_assert(m4_json(m4_pool(array('pool_id'=>992201),$session))['success'],'Pool assignment failed');foreach(array(992231,992232,992233) as $id){m4_set($id,array('status'=>'submitted'));}do_action('eipsi_form_submitted',array('participant_id'=>992207,'survey_id'=>992203,'wave_id'=>992223));m0_assert((int)$wpdb->get_var("SELECT completed FROM {$wpdb->prefix}eipsi_pool_assignments WHERE pool_id=992201 AND participant_id=992207")===1,'pool_name callback failed');$wpdb->update($wpdb->prefix.'eipsi_pool_assignments',array('completed'=>0),array('pool_id'=>992201,'participant_id'=>992207));m0_assert(eipsi_check_and_mark_pool_completion(992207,992203,'m2-long-form'),'Numeric helper failed');m0_assert(!eipsi_check_and_mark_pool_completion(992208,992203,'m2-long-form'),'Other participant completed');};
$tests['MariaDB two concurrent submits yield one committed transition']=function(){$r=m4_concurrent('submit');$wins=0;$loses=0;foreach($r as $row){if(isset($row['result']['has_next_wave'])){$wins++;}elseif(($row['result']['success']??null)===false&&$row['result']['status']===500){$loses++;}}m0_assert($wins===1&&$loses===1&&m4_assignment()->status==='submitted'&&m4_assignment()->t1_completed_at,'Concurrent submit result not unique');};
$tests['MariaDB two concurrent snapshot transitions affect exactly one row']=function(){$r=m4_concurrent('transition');$affected=array($r[0]['result'],$r[1]['result']);sort($affected);m0_assert($affected===array(0,1)&&in_array(m4_assignment()->status,array('expired','skipped'),true),'Concurrent transition duplicated');};
$tests['MariaDB FOR UPDATE acquisition waits for parent commit']=function(){$r=m4_concurrent('submit',true);foreach($r as $row){m0_assert($row['finished_at'] >= $row['released_at'],'Worker finished before parent released lock');}m0_assert(m4_assignment()->status==='submitted','Lock order lost final submit');};
$tests['Bulk assignment creation preserves retry counts and active waves']=function(){global $wpdb;try{$first=eipsi_create_assignments_for_participant(992208,992203);$second=eipsi_create_assignments_for_participant(992208,992203);m0_assert($first['created']===3&&$second['created']===0&&$second['skipped']===3&&empty($first['errors'])&&empty($second['errors']),'Bulk assignment retry changed');}finally{$wpdb->delete($wpdb->prefix.'survey_assignments',array('participant_id'=>992208));}};
$tests['Manual forced anchor updates T1 timestamp and downstream availability']=function(){global $wpdb;$r=EIPSI_T1_Anchor_Service::manual_anchor(992203,992207,'2026-10-05 12:00:00');m0_assert(!is_wp_error($r),'Manual anchor failed: '.(is_wp_error($r)?$r->get_error_message():''));$r=EIPSI_T1_Anchor_Service::manual_anchor(992203,992207,'2026-10-06 12:00:00',true);m0_assert(!is_wp_error($r)&&m4_assignment()->submitted_at==='2026-10-06 12:00:00','Forced timestamp changed');m0_assert($wpdb->get_var("SELECT t1_completed_at FROM {$wpdb->prefix}survey_participants WHERE id=992207")==='2026-10-06 12:00:00'&&m4_assignment(992232)->available_at==='2026-10-06 13:00:00','Forced downstream anchor changed');};
$tests['Submission hooks retain T1 before Pools priority and registration']=function(){m0_assert(has_action('eipsi_form_submitted',array('EIPSI_T1_Anchor_Service','on_form_submitted'))===5,'T1 priority changed');m0_assert(has_action('eipsi_form_submitted','eipsi_check_pool_completion_on_submit')===10,'Pools priority changed');m0_assert(has_action('eipsi_process_assignment_expirations','eipsi_run_process_assignment_expirations')!==false,'Expiration cron adapter lost');m0_assert(has_action('eipsi_wave_skipping_cron','eipsi_check_wave_skipping')!==false,'Skipping cron adapter lost');};
$tests['Skipped and expired assignments reject submit without state changes']=function(){foreach(array('skipped','expired') as $status){m4_set(992231,array('status'=>$status));$r=EIPSI_Longitudinal_Assignment_Transition_Service::submit_locked(992207,992203,992221);m0_assert(is_array($r)&&!$r['success']&&m4_assignment()->status===$status,'Terminal state overwritten');}};
$tests['Conditioned purge removes only private A duplicates and retains Notifications']=function(){$manifest=json_decode(file_get_contents(__DIR__.'/purge-manifest.json'),true);m0_assert(count($manifest['deleted'])===7,'Purge scope changed');foreach($manifest['deleted'] as $row){m0_assert($row['classification']==='A'&&!method_exists($row['class'],$row['method'])&&method_exists($row['owner'],$row['method']),'Unsafe purge');}m0_assert(method_exists('Wave_Service','maybe_send_immediate_wave_reminder'),'M5 notification code purged');};
