<?php
require __DIR__.'/m0/bootstrap.php';
$root=EIPSI_FORMS_PLUGIN_DIR;
$baseline=json_decode(file_get_contents(__DIR__.'/purga-final/public-contracts-before.json'),true);
$s0=json_decode(file_get_contents(__DIR__.'/s0/security-contracts.json'),true);
$s1=json_decode(file_get_contents(__DIR__.'/s1/security-contracts.json'),true);
$matrix=json_decode(file_get_contents(__DIR__.'/m8/global-retained-matrix.json'),true);
$tests=array();
$tests['A: archivo y tres wrappers privados ausentes']=function()use($root){
 m0_assert(!file_exists($root.'helpers.txt'),'Orphan remains');$r=new ReflectionClass('EIPSI_Database_Schema_Manager');foreach(array('get_table_creation_order','local_table_exists','add_foreign_keys_phase2')as$m)m0_assert(!$r->hasMethod($m),'Private wrapper remains: '.$m);
};
$tests['Firmas públicas de clases incluidas las heredadas preservadas']=function()use($baseline,$s0,$s1){
 foreach(array('includes/services/class-nudge-service.php','includes/services/Wave_Service.php','includes/shortcodes/class-pool-join-shortcode.php','admin/services/class-email-confirmation-service.php','admin/services/class-device-data-service.php','admin/services/class-wave-eligibility-service.php','admin/services/class-participant-data-cleanup.php')as$file)require_once EIPSI_FORMS_PLUGIN_DIR.$file;
 foreach($baseline['classes']as$name=>$expected){m0_assert(class_exists($name),'Class absent: '.$name);$r=new ReflectionClass($name);$actual=array();foreach($r->getMethods(ReflectionMethod::IS_PUBLIC)as$m){$params=array();foreach($m->getParameters()as$p)$params[]=array('name'=>$p->getName(),'optional'=>$p->isOptional(),'default'=>$p->isDefaultValueAvailable()?$p->getDefaultValue():null,'type'=>$p->hasType()?(string)$p->getType():null);$actual[$m->getName()]=array('static'=>$m->isStatic(),'parameters'=>$params,'owner'=>$m->getDeclaringClass()->getName());}m0_assert($actual==array_merge($expected['methods'],$s0['added_public_methods'][$name]??array(),$s1['added_public_methods'][$name]??array()),'Public API changed: '.$name);}
};
$tests['Firmas globales y callbacks de compatibilidad preservados']=function()use($baseline){
 foreach($baseline['functions']as$name=>$expected){m0_assert(function_exists($name),'Global absent: '.$name);$params=array();foreach((new ReflectionFunction($name))->getParameters()as$p)$params[]=array('name'=>$p->getName(),'optional'=>$p->isOptional(),'default'=>$p->isDefaultValueAvailable()?$p->getDefaultValue():null);m0_assert($params==$expected['parameters'],'Global signature changed: '.$name);}
};
function purga_inventory($profile,$refresh=false){
 static $cache=array();if($refresh)unset($cache[$profile]);if(isset($cache[$profile]))return $cache[$profile];
 $cmd='EIPSI_M0_PROFILE='.escapeshellarg($profile).' '.escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/purga-final/capture.php');exec($cmd,$lines,$code);m0_assert($code===0,'Inventory failed');$cache[$profile]=json_decode(implode("\n",$lines),true,512,JSON_THROW_ON_ERROR);return $cache[$profile];
}
function purga_hooks($rows){return array_map(function($h){return array_intersect_key($h,array_flip(array('hook','callback','file','priority','order_at_priority','accepted_args','callable')));},$rows);}
$tests['Hooks admin/frontend preservan nombres prioridad orden y argumentos']=function(){foreach(array('frontend','admin')as$p){$before=json_decode(file_get_contents(__DIR__.'/purga-final/'.$p.'-before.json'),true);$after=purga_inventory($p);m0_assert(purga_hooks($before['hooks'])==purga_hooks($after['hooks']),'Hook boundary changed: '.$p);}};
$tests['Todos los callbacks runtime son callable']=function(){foreach(array('frontend','admin')as$p){$i=purga_inventory($p);foreach($i['hooks']as$h)m0_assert($h['callable'],'Broken hook '.$h['hook']);foreach($i['rest']as$r)m0_assert($r['callback']['callable']&&$r['permission']['callable'],'REST callback broken');foreach($i['shortcodes']as$r)m0_assert($r['callable'],'Shortcode broken');}};
$tests['Includes runtime existen y preservan lista de carga']=function()use($root){foreach(array('frontend','admin')as$p){$before=json_decode(file_get_contents(__DIR__.'/purga-final/'.$p.'-before.json'),true);$after=purga_inventory($p);$a=array_column($before['included'],'file');$b=array_column($after['included'],'file');m0_assert($a===$b,'Include list changed');foreach($b as$f)m0_assert(is_file($root.$f),'Dangling include: '.$f);}};
$tests['Assets preservan handles URL dependencia y orden']=function(){foreach(array('frontend','admin')as$p){$before=json_decode(file_get_contents(__DIR__.'/purga-final/'.$p.'-before.json'),true);$after=purga_inventory($p);$normalize=function($rows){foreach($rows as&$r)if($r['handle']==='eipsi-forms-js')$r['version']=preg_replace('/\.\d+$/','',(string)$r['version']);unset($r);return$rows;};m0_assert($normalize($before['assets'])===$normalize($after['assets']),'Asset contract changed: '.$p);}};
$tests['Contenido de assets locales preservado tras build']=function()use($root,$s0){$hashes=json_decode(file_get_contents(__DIR__.'/purga-final/asset-hashes-before.json'),true);foreach($hashes as$file=>$hash){if(isset($s0['assets'][$file])){m0_assert($s0['assets'][$file]['before_s0_sha256']===$hash,'Original asset baseline lost');$hash=$s0['assets'][$file]['s0_sha256'];}m0_assert(is_file($root.$file)&&hash_file('sha256',$root.$file)===$hash,'Asset body changed: '.$file);}};
$tests['Dependencias de assets EIPSI registradas en WordPress']=function(){foreach(array('frontend','admin')as$p){$i=purga_inventory($p);m0_assert(!$i['missing_asset_dependencies'],'Dangling dependency: '.json_encode($i['missing_asset_dependencies']));}};
$tests['Cron programado conserva frecuencia y callback']=function(){m0_assert(has_action('wp','eipsi_schedule_job_worker')===10,'Contextual scheduler absent');$request=m0_http('/');m0_assert(wp_remote_retrieve_response_code($request)===200,'Frontend lifecycle failed');foreach(array('frontend','admin')as$p){$i=purga_inventory($p,true);$b=json_decode(file_get_contents(__DIR__.'/purga-final/'.$p.'-before.json'),true);$shape=function($rows){$a=array();foreach($rows as$r)$a[]=array($r['hook'],$r['schedule'],$r['interval'],$r['args'],$r['callback_registered']);sort($a);return$a;};m0_assert($shape($i['cron'])===$shape($b['cron']),'Cron contract changed');foreach($i['cron']as$r)m0_assert($r['callback_registered'],'Cron orphan');}};
$tests['Matriz conserva 70 decisiones y datos de retiro']=function()use($matrix){m0_assert(count($matrix['rows'])===70,'Lost matrix rows');foreach($matrix['rows']as$i=>$r){m0_assert($r['id']===$i+1&&in_array($r['final_classification'],array('A','B','C','D','E','F'),true),'Invalid decision');m0_assert($r['reviewed_files']&&$r['canonical_owner']&&$r['evidence']&&$r['recommended_action'],'Review incomplete');}m0_assert(count($matrix['deleted_A'])===4,'Unreviewed deletion');};
$tests['Deuda UI visible F y casos externos E siguen caracterizados']=function()use($matrix,$root){foreach($matrix['ui_handler_debt']as$r){m0_assert(strpos(file_get_contents($root.$r['file']),$r['action'])!==false,'Emitter changed');$registered=has_action('wp_ajax_'.$r['action'])!==false||has_action('wp_ajax_nopriv_'.$r['action'])!==false;m0_assert($registered===$r['runtime_registered'],'Handler contract changed');}m0_assert($matrix['additional_debt'][0]['classification']==='F','Join/Auth debt omitted');};
$tests['Estados draft e identidad incompatible conservan decisión F']=function()use($matrix){foreach(array(68,69)as$id)m0_assert($matrix['rows'][$id-1]['final_classification']==='F','Functional risk hidden');};
$tests['Migraciones y herramientas manuales retenidas']=function()use($matrix,$root){foreach($matrix['rows']as$r)if($r['final_classification']==='D')foreach($r['reviewed_files']as$f)m0_assert(is_file($root.$f),'Manual recovery deleted');m0_assert(class_exists('EIPSI_Migration_Runner')&&class_exists('EIPSI_Schema_Inspector'),'Upgrade/reporting boundary lost');};
$tests['Código operativo no referencia el archivo A eliminado']=function()use($root){$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as$f){$rel=substr($f->getPathname(),strlen($root));if(preg_match('~^(tests|docs|node_modules|build|\.git)/~',$rel)||!preg_match('/\.(php|js|json|css)$/',$rel))continue;m0_assert(strpos(file_get_contents($f->getPathname()),'helpers.txt')===false,'Dangling file reference: '.$rel);}};
$failures=0;foreach($tests as$name=>$test){try{$test();echo 'PASS '.$name."\n";}catch(Throwable$e){$failures++;echo 'FAIL '.$name.': '.$e->getMessage()."\n";}}echo count($tests)." tests, $failures failures\n";ob_end_flush();exit($failures?1:0);
