<?php
/** M8 real MariaDB fixtures. Only owned random-prefix tables are changed. */
define('DOING_CRON', true);
require __DIR__.'/m0/bootstrap.php';
require __DIR__.'/m8/concurrency.php';
$original=$wpdb; $prefix='m8_'.bin2hex(random_bytes(4)).'_';
$wpdb=new wpdb(DB_USER,DB_PASSWORD,DB_NAME,DB_HOST); $wpdb->set_prefix($prefix); $wpdb->suppress_errors(true);
$wpdb->query("CREATE TABLE `{$prefix}options` LIKE `{$original->options}`");
$wpdb->query("INSERT INTO `{$prefix}options` SELECT * FROM `{$original->options}`");
wp_cache_flush();
$tests=[];$failed=0;
function m8_check($condition,$message){m0_assert($condition,$message);}
function m8_schema(){global $wpdb;$r=[];foreach(EIPSI_Schema_Registry::get_schema_map() as $slug=>$def){$table=$wpdb->prefix.$slug;$r[$slug]=[$wpdb->get_results("SHOW FULL COLUMNS FROM `$table`",ARRAY_A),$wpdb->get_results("SHOW INDEX FROM `$table`",ARRAY_A)];}return $r;}
function m8_install(){ $r=EIPSI_Schema_Installer::repair_local_schema();m8_check($r['success'],wp_json_encode($r)); }
function m8_version($v){update_option('eipsi_migration_version',$v);wp_cache_flush();}
function m8_run(){return (new EIPSI_Migration_Runner())->run();}
function m8_drop_new_columns(){global $wpdb;foreach(['survey_participants'=>['study_end_at'],'survey_studies'=>['start_date','end_date']] as $slug=>$cols){foreach($cols as $col){$wpdb->query("ALTER TABLE `{$wpdb->prefix}$slug` DROP COLUMN `$col`");}}}
function m8_rows(){global $wpdb;$r=[];foreach(EIPSI_Schema_Registry::get_schema_map() as $slug=>$def){$r[$slug]=$wpdb->get_results("SELECT * FROM `{$wpdb->prefix}$slug` ORDER BY id",ARRAY_A);}return $r;}
try {
 m8_install();
 // Representative data in all domains, with matching logical relation IDs.
 foreach(EIPSI_Schema_Registry::get_schema_map()as$slug=>$definition){
  $row=['id'=>88001];
  foreach($definition['columns']as$column=>$sql){
   if($column==='id')continue;
   if(preg_match('/^(survey_id|study_id|participant_id|wave_id|assignment_id|pool_id)$/',$column)&&preg_match('/^(bigint|int)/i',$sql)){$row[$column]=88001;continue;}
   if(stripos($sql,'NOT NULL')===false||stripos($sql,'DEFAULT')!==false)continue;
   if(preg_match('/^(bigint|int|tinyint|decimal|float|double)/i',$sql))$row[$column]=1;
   elseif(preg_match('/^(datetime|timestamp|date)/i',$sql))$row[$column]='2020-02-03 04:05:06';
   elseif(preg_match("/^enum\('([^']+)'/i",$sql,$m))$row[$column]=$m[1];
   elseif(stripos($sql,'json')===0)$row[$column]='{"answer":"hist"}';
   else $row[$column]='hist';
  }
  if(isset($definition['columns']['form_responses']))$row['form_responses']='{"answer":"historical sensitive value"}';
  if($slug==='eipsi_emergency_submissions')$row['form_data']='historical raw payload';
  if($slug==='survey_participants')$row['email']='history@example.invalid';
  m8_check($wpdb->insert($wpdb->prefix.$slug,$row)!==false,'Seed '.$slug.': '.$wpdb->last_error);
 }
 $historical_rows=m8_rows();
 $tests['Registry contains all 26 local tables']=function(){m8_check(count(EIPSI_Schema_Registry::get_schema_map())===26,'Table count');};
 $tests['Creation order covers registry once']=function(){$a=array_keys(EIPSI_Schema_Registry::get_schema_map());$b=EIPSI_Schema_Registry::get_table_creation_order();sort($a);sort($b);m8_check($a===$b,'Order coverage');};
 foreach(EIPSI_Schema_Registry::get_schema_map() as $slug=>$def){$tests['Clean structure '.$slug]=function()use($slug){$r=EIPSI_Schema_Inspector::inspect($slug);m8_check($r['exists']&&!$r['issues'],wp_json_encode($r));};}
 $tests['Reinstallation is structurally idempotent']=function(){$before=m8_schema();m8_install();m8_check(m8_schema()===$before,'Changed structures');};
 $tests['Schema revision is independent of plugin version']=function(){m8_check(strlen(get_option('eipsi_schema_revision'))===64&&get_option('eipsi_schema_revision')===EIPSI_Schema_Version_Service::revision(),'Wrong revision');};
 $tests['Inspector does not modify schema or migration state']=function(){$before=m8_schema();$v=get_option('eipsi_migration_version');foreach(array_keys(EIPSI_Schema_Registry::get_schema_map())as$s){EIPSI_Schema_Inspector::inspect($s);}EIPSI_Schema_Inspector::check_collation_issues();m8_check($before===m8_schema()&&$v===get_option('eipsi_migration_version'),'Inspector mutation');};
 $tests['Missing nullable column detected and repaired']=function(){global$wpdb;$wpdb->query("ALTER TABLE `{$wpdb->prefix}survey_participants` DROP COLUMN study_end_at");m8_check(in_array('study_end_at',EIPSI_Schema_Inspector::inspect('survey_participants')['missing_columns'],true),'Missing not detected');$r=EIPSI_Schema_Repair_Service::sync_local_table('survey_participants');m8_check($r['success']&&$r['columns_added']===['study_end_at'],'Repair failed');};
 $tests['Missing index detected and repaired']=function(){global$wpdb;$wpdb->query("ALTER TABLE `{$wpdb->prefix}eipsi_manual_overrides` DROP INDEX randomization_id");$r=EIPSI_Schema_Inspector::inspect('eipsi_manual_overrides');m8_check(!empty($r['missing_indexes']),'Missing index not found');m8_check(EIPSI_Schema_Repair_Service::sync_local_table('eipsi_manual_overrides')['success'],'Index repair');};
 $tests['Missing table detected and restored']=function(){global$wpdb;$wpdb->query("RENAME TABLE `{$wpdb->prefix}eipsi_manual_overrides` TO `{$wpdb->prefix}manual_backup`");m8_check(!EIPSI_Schema_Inspector::inspect('eipsi_manual_overrides')['exists'],'Missing not found');m8_check(EIPSI_Schema_Repair_Service::sync_local_table('eipsi_manual_overrides')['success'],'Table repair');$wpdb->query("DROP TABLE `{$wpdb->prefix}eipsi_manual_overrides`");$wpdb->query("RENAME TABLE `{$wpdb->prefix}manual_backup` TO `{$wpdb->prefix}eipsi_manual_overrides`");};
 $tests['Incompatible type is detected without conversion']=function(){global$wpdb;$t=$wpdb->prefix.'survey_studies';$wpdb->query("ALTER TABLE `$t` MODIFY description VARCHAR(64) NULL");$before=m8_schema();m8_check(in_array('description',EIPSI_Schema_Inspector::inspect('survey_studies')['incompatible_types'],true),'Type missing');m8_check(!EIPSI_Schema_Repair_Service::sync_local_table('survey_studies')['success'],'Unsafe repair succeeded');m8_check($before===m8_schema(),'Unsafe mutation');$wpdb->query("ALTER TABLE `$t` MODIFY description TEXT NULL");};
 $tests['JSON alias retains validation constraint']=function(){global$wpdb;$r=$wpdb->get_row("SHOW CREATE TABLE `{$wpdb->prefix}survey_studies`",ARRAY_N);m8_check(stripos($r[1],'json_valid')!==false&&!EIPSI_Schema_Inspector::inspect('survey_studies')['incompatible_types'],'JSON alias');};
 $tests['Collation report is read only']=function(){$b=m8_schema();$r=EIPSI_Schema_Repair_Service::fix_collations();m8_check($r['total_fixed']===0&&$b===m8_schema(),'Collation converted');};
 $tests['Unknown table rejected without DDL']=function(){$b=m8_schema();m8_check(!EIPSI_Schema_Repair_Service::sync_local_table('unknown')['success']&&$b===m8_schema(),'Unknown mutation');};
 $tests['Upgrade from previous revision restores current columns']=function(){m8_drop_new_columns();m8_version(9);$r=m8_run();m8_check($r['success']&&(int)get_option('eipsi_migration_version')===10,'Upgrade failed');foreach(['survey_participants','survey_studies']as$s){m8_check(!EIPSI_Schema_Inspector::inspect($s)['issues'],'Drift');}};
 $tests['Intermediate upgrade preserves dynamic values and metadata']=function(){global$wpdb;$t=$wpdb->prefix.'survey_participants';$wpdb->query("ALTER TABLE `$t` ADD T1_history VARCHAR(255) NULL DEFAULT 'legacy' COMMENT 'historical' ");m8_drop_new_columns();m8_version(6);$r=m8_run();$c=$wpdb->get_row("SHOW FULL COLUMNS FROM `$t` LIKE 'T1_history'",ARRAY_A);m8_check($r['success']&&$c['Type']==='text'&&trim($c['Default'],"'")==='legacy'&&$c['Comment']==='historical'&&$c['Null']==='YES','Dynamic conversion: '.wp_json_encode([$r,$c]));};
 $tests['Early supported template identity renamed without narrowing']=function(){global$wpdb;$t=$wpdb->prefix.'eipsi_randomization_assignments';$wpdb->query("ALTER TABLE `$t` CHANGE randomization_id template_id VARCHAR(255) NOT NULL");m8_version(0);$r=m8_run();m8_check($r['success']&&in_array('randomization_id',array_column($wpdb->get_results("SHOW COLUMNS FROM `$t`",ARRAY_A),'Field'),true),'Early upgrade');};
 $tests['Known historical email ENUM widens without losing rows']=function(){global$wpdb;$t=$wpdb->prefix.'survey_email_log';$before=$wpdb->get_results("SELECT * FROM `$t` ORDER BY id",ARRAY_A);m8_check($wpdb->query("ALTER TABLE `$t` MODIFY email_type ENUM('custom','reminder') NULL DEFAULT 'custom'")!==false,'Email historical fixture');m8_version(9);m8_check(m8_run()['success'],'Email upgrade');$type=$wpdb->get_var("SHOW COLUMNS FROM `$t` LIKE 'email_type'",1);m8_check($type==='varchar(100)'&&$wpdb->get_results("SELECT * FROM `$t` ORDER BY id",ARRAY_A)===$before,'Email rows changed');};
 $tests['Rerun at latest version is idempotent']=function(){$b=m8_schema();m8_check(m8_run()['success']&&$b===m8_schema(),'Rerun drift');};
 $tests['Unsupported future version rejected']=function(){m8_version(999);m8_check(!m8_run()['success']&&(int)get_option('eipsi_migration_version')===999,'Future advanced');m8_version(10);};
 $tests['Unsupported historical identity rejected without advancing']=function(){global$wpdb;$t=$wpdb->prefix.'eipsi_randomization_assignments';$wpdb->query("ALTER TABLE `$t` CHANGE user_fingerprint legacy_identity VARCHAR(255) NOT NULL");m8_version(9);$r=m8_run();m8_check(!$r['success']&&(int)get_option('eipsi_migration_version')===9,'Unsupported advanced');$wpdb->query("ALTER TABLE `$t` CHANGE legacy_identity user_fingerprint VARCHAR(255) NOT NULL");m8_check(m8_run()['success'],'Retry');};
 $tests['SQL failure leaves checkpoint and partial upgrade can retry']=function(){global$wpdb;m8_drop_new_columns();m8_version(9);$filter=function($sql)use($wpdb){return strpos($sql,'ALTER TABLE `'.$wpdb->prefix.'survey_studies` ADD COLUMN `end_date`')===0?'INVALID M8 SQL':$sql;};add_filter('query',$filter);try{$r=m8_run();m8_check(!$r['success']&&(int)get_option('eipsi_migration_version')===9,'Failure advanced');m8_check(!in_array('start_date',EIPSI_Schema_Inspector::inspect('survey_studies')['missing_columns'],true),'Partial fixture absent');}finally{remove_filter('query',$filter);}m8_check(m8_run()['success']&&(int)get_option('eipsi_migration_version')===10,'Retry failed');};
 $tests['Pools unique policy remains unchanged']=function(){global$wpdb;$i=$wpdb->get_results("SHOW INDEX FROM `{$wpdb->prefix}eipsi_pool_assignments`",ARRAY_A);$found=false;foreach($i as$r){if($r['Key_name']==='unique_pool_participant'&&!$r['Non_unique'])$found=true;}m8_check($found,'Pool unique policy');};
 $tests['Emergency retains historical and runtime payload columns']=function(){$d=EIPSI_Schema_Registry::get_schema_map()['eipsi_emergency_submissions']['columns'];m8_check(isset($d['form_data'],$d['raw_post_data']),'Historical payload lost');};
 $tests['Maintenance authorized request fails closed without SQL executor']=function()use($original){global$wpdb;m8_check(!method_exists('EIPSI_Database_Schema_Manager','execute_maintenance_sql'),'Generic executor');$fixture_db=$wpdb;$wpdb=$original;wp_cache_flush();try{$nonce=m0_admin_nonce('eipsi_admin_nonce');$response=m0_http('/wp-admin/admin-ajax.php',['action'=>'eipsi_execute_maintenance_sql','nonce'=>$nonce,'sql_statements'=>['SELECT 1']],true);m8_check(!is_wp_error($response)&&wp_remote_retrieve_response_code($response)===501,'Maintenance did not fail closed');$json=json_decode(wp_remote_retrieve_body($response),true);m8_check(isset($json['success'])&&!$json['success'],'Maintenance false success');}finally{$wpdb=$fixture_db;wp_cache_flush();}};

 foreach(['survey_participants','survey_sessions','survey_studies','survey_waves','survey_assignments','vas_form_results','eipsi_partial_responses','survey_nudge_jobs','eipsi_longitudinal_pools','eipsi_pool_assignments','eipsi_randomization_assignments','eipsi_manual_overrides','survey_data_requests','survey_email_log']as$slug){
  $tests['Historical rows, IDs, values and timestamps retained '.$slug]=function()use($slug,$historical_rows){$actual=m8_rows()[$slug];m8_check(count($actual)===count($historical_rows[$slug]),'Rows lost');foreach($historical_rows[$slug]as$i=>$row){foreach($row as$key=>$value){m8_check(array_key_exists($key,$actual[$i])&&$actual[$i][$key]===$value,'Changed '.$slug.'.'.$key);}}};
 }
 $tests['Historical logical assignment relationships preserved']=function(){global$wpdb;$row=$wpdb->get_row("SELECT a.id FROM `{$wpdb->prefix}survey_assignments` a JOIN `{$wpdb->prefix}survey_participants` p ON p.id=a.participant_id JOIN `{$wpdb->prefix}survey_studies` s ON s.id=a.study_id JOIN `{$wpdb->prefix}survey_waves` w ON w.id=a.wave_id WHERE a.id=88001");m8_check((bool)$row,'Relationships lost');};


 $tests['Historical public method signatures remain compatible']=function(){$contracts=json_decode(file_get_contents(__DIR__.'/m8/contracts.json'),true);foreach($contracts as$class=>$methods){foreach($methods as$name=>$signature){$ref=new ReflectionMethod($class,$name);m8_check($ref->isPublic(),'Visibility '.$class.'::'.$name);preg_match_all('/\$([a-zA-Z_][a-zA-Z0-9_]*)/',$signature,$m);m8_check(array_map(function($p){return$p->getName();},$ref->getParameters())===$m[1],'Parameters '.$class.'::'.$name);}}};
 $tests['New runtime date columns are nullable with NULL defaults']=function(){global$wpdb;foreach(['survey_participants'=>['study_end_at'],'survey_studies'=>['start_date','end_date']]as$t=>$cols){foreach($cols as$c){$r=$wpdb->get_row("SHOW FULL COLUMNS FROM `{$wpdb->prefix}$t` LIKE '$c'",ARRAY_A);m8_check($r['Null']==='YES'&&$r['Default']===null,'Changed default '.$c);}}};
 $tests['Plain LONGTEXT without JSON validation remains incompatible']=function(){global$wpdb;$t=$wpdb->prefix.'survey_studies';m8_check($wpdb->query("ALTER TABLE `$t` DROP COLUMN config, ADD COLUMN config LONGTEXT DEFAULT NULL")!==false,'Remove JSON check fixture');try{m8_check(in_array('config',EIPSI_Schema_Inspector::inspect('survey_studies')['incompatible_types'],true),'Plain LONGTEXT accepted');}finally{$wpdb->query("ALTER TABLE `$t` MODIFY COLUMN config JSON DEFAULT NULL");}};
 $tests['Study settings persists study_name and existing time contract']=function(){global$wpdb;$t=$wpdb->prefix.'survey_studies';$before=$wpdb->get_row("SELECT * FROM `$t` WHERE id=88001",ARRAY_A);try{m8_check($wpdb->query("ALTER TABLE `$t` MODIFY status VARCHAR(20) DEFAULT 'active'")!==false,'Legacy draft fixture');$wpdb->update($t,['status'=>'draft'],['id'=>88001]);$r=EIPSI_Longitudinal_Study_Config_Service::wp_ajax_eipsi_save_study_settings_handler(88001,['study_name'=>'M8 new name','time_config'=>'limited','start_date'=>'2020-02-03 04:05:06','end_date'=>'2020-02-04 04:05:06']);$row=$wpdb->get_row("SELECT * FROM `$t` WHERE id=88001",ARRAY_A);m8_check($r['success']&&$row['study_name']==='M8 new name'&&$row['start_date']==='2020-02-03 04:05:06'&&$row['end_date']==='2020-02-04 04:05:06','Settings contract '.wp_json_encode($r));}finally{unset($before['id']);$wpdb->update($t,$before,['id'=>88001]);$wpdb->query("ALTER TABLE `$t` MODIFY status ENUM('active','completed','paused','archived') DEFAULT 'active'");}};
 $tests['T1 recalculation persists participant study_end_at']=function(){global$wpdb;$s=$wpdb->prefix.'survey_studies';$p=$wpdb->prefix.'survey_participants';$wpdb->update($s,['study_end_offset_minutes'=>60],['id'=>88001]);try{$r=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_after_t1(88001,88001,'2020-02-03 04:05:06');m8_check($r['success']&&$wpdb->get_var("SELECT study_end_at FROM `$p` WHERE id=88001")==='2020-02-03 05:05:06','End-at not persisted');}finally{$wpdb->update($s,['study_end_offset_minutes'=>0],['id'=>88001]);$wpdb->update($p,['study_end_at'=>null],['id'=>88001]);}};
 $tests['Availability obtains T1 wave_index from waves, not assignments']=function(){global$wpdb;$w=$wpdb->prefix.'survey_waves';$a=$wpdb->prefix.'survey_assignments';$old=$wpdb->get_row("SELECT * FROM `$a` WHERE id=88001",ARRAY_A);try{$wpdb->update($w,['wave_index'=>1],['id'=>88001]);$wpdb->update($a,['status'=>'submitted','submitted_at'=>'2020-02-03 04:05:06'],['id'=>88001]);$assignment=(object)['participant_id'=>88001];$wave=(object)['study_id'=>88001,'wave_index'=>2,'offset_minutes'=>60];m8_check(EIPSI_Longitudinal_Notification_Context_Service::is_wave_available($assignment,$wave),'Wave query failed on canonical schema');}finally{unset($old['id']);$wpdb->update($a,$old,['id'=>88001]);}};
 $tests['Killed migration preserves checkpoint and recovers partial schema']=function(){m8_drop_new_columns();m8_version(9);m8_interrupt();m8_check((int)get_option('eipsi_migration_version')===9,'Killed migration advanced');$r=EIPSI_Schema_Inspector::inspect('survey_studies');m8_check(in_array('end_date',$r['missing_columns'],true)&&!in_array('start_date',$r['missing_columns'],true),'Interrupted partial shape');m8_check(m8_run()['success'],'Interrupted retry');};
 $tests['ALTER denied by actual DB privileges leaves version unchanged']=function(){global$wpdb;$owner=$wpdb;m8_drop_new_columns();m8_version(9);$restricted=new wpdb('m8_noalter','m8-noalter',DB_NAME,DB_HOST);$restricted->set_prefix($owner->prefix);$restricted->suppress_errors(true);$wpdb=$restricted;wp_cache_flush();try{$r=m8_run();m8_check(!$r['success']&&(int)get_option('eipsi_migration_version')===9,'Denied ALTER advanced');}finally{$wpdb=$owner;wp_cache_flush();$restricted->close();}m8_check(m8_run()['success'],'Privileged retry');};
 $tests['Two processes migrate with one verified final state']=function(){m8_drop_new_columns();m8_version(9);$r=m8_concurrent('migration');m8_check($r[0]['success']&&$r[1]['success']&&(int)get_option('eipsi_migration_version')===10,'Migration race');foreach(['survey_participants','survey_studies']as$s)m8_check(!EIPSI_Schema_Inspector::inspect($s)['issues'],'Partial structure');};
 $tests['Two processes repair the same missing columns safely']=function(){m8_drop_new_columns();$r=m8_concurrent('repair');m8_check($r[0]['success']&&$r[1]['success']&&!EIPSI_Schema_Inspector::inspect('survey_studies')['missing_columns'],'Repair race');m8_install();};
 $tests['Periodic inspection cannot execute destructive DDL']=function(){delete_option('eipsi_schema_last_inspected');$b=m8_schema();$ddl=[];$filter=function($sql)use(&$ddl){if(preg_match('/^(CREATE|ALTER|DROP|TRUNCATE)\s/i',$sql))$ddl[]=$sql;return$sql;};add_filter('query',$filter);try{EIPSI_Database_Schema_Manager::periodic_verification();EIPSI_Database_Schema_Manager::periodic_verification();}finally{remove_filter('query',$filter);}m8_check(!$ddl&&$b===m8_schema(),'Periodic DDL');};
 $tests['External creator from zero supports current INSERT']=function(){global$wpdb;mysqli_report(MYSQLI_REPORT_OFF);$db=new mysqli('eipsi-m0-db',DB_USER,DB_PASSWORD,'m8_external');m8_check(!$db->connect_error,'External fixture connection');$table=$wpdb->prefix.'vas_form_results';try{m8_check(EIPSI_External_Schema_Adapter::create_results($db),'External create');$cols=[];$r=$db->query("SHOW COLUMNS FROM `$table`");while($row=$r->fetch_assoc())$cols[]=$row['Field'];foreach(['browser','os','screen_width']as$c)m8_check(in_array($c,$cols,true),'External missing '.$c);$store=new class extends EIPSI_Storage_External_Submission_Store{public function get_connection(){return new mysqli('eipsi-m0-db',DB_USER,DB_PASSWORD,'m8_external');}};$data=['form_id'=>'hist','participant_id'=>'hist','session_id'=>'hist','survey_id'=>88001,'wave_index'=>1,'user_fingerprint'=>'hist','form_name'=>'M8 historical','created_at'=>'2020-02-03 04:05:06','submitted_at'=>null,'ip_address'=>null,'device'=>null,'browser'=>'fixture','os'=>'fixture','screen_width'=>640,'duration'=>1,'duration_seconds'=>1.0,'start_timestamp_ms'=>1,'end_timestamp_ms'=>2,'metadata'=>'{}','status'=>'submitted','form_responses'=>'{"answer":"preserve"}'];$r=$store->insert_form_submission($data);m8_check($r['success']&&$r['insert_id']>0,'External INSERT '.wp_json_encode($r));$row=$db->query("SELECT * FROM `$table`")->fetch_assoc();m8_check($row['form_responses']===$data['form_responses'],'External value changed');$check=new ReflectionMethod($store,'validate_required_columns');m8_check($check->invoke($store,$db,$table)['success'],'External verify');$db->query("ALTER TABLE `$table` DROP COLUMN browser, DROP COLUMN os, DROP COLUMN screen_width");m8_check(EIPSI_External_Schema_Adapter::ensure_required_columns($db,$table),'External legacy safe additions');m8_check($store->insert_form_submission($data)['success'],'External existing insert');m8_check((int)$db->query("SELECT COUNT(*) FROM `$table`")->fetch_row()[0]===2,'External data lost');}finally{$db->query("DROP TABLE IF EXISTS `$table`");$db->close();}};
 $tests['External unavailable fails without success']=function(){$store=new class extends EIPSI_Storage_External_Submission_Store{public function get_connection(){mysqli_report(MYSQLI_REPORT_OFF);$db=@new mysqli('eipsi-m0-db',DB_USER,'intentionally-wrong','m8_external');return$db->connect_error?null:$db;}};$r=$store->insert_form_submission(['form_id'=>'hist']);m8_check(!$r['success']&&$r['error_code']==='CONNECTION_FAILED'&&$r['insert_id']===null,'External false success');};
 foreach($tests as$name=>$test){try{$test();echo 'PASS '.$name."\n";}catch(Throwable$e){$failed++;echo 'FAIL '.$name.': '.$e->getMessage()."\n";}}
} finally {
 $wpdb->query('SET FOREIGN_KEY_CHECKS=0');
 foreach(array_keys(EIPSI_Schema_Registry::get_schema_map())as$s){$wpdb->query("DROP TABLE IF EXISTS `{$prefix}$s`");}
 $wpdb->query("DROP TABLE `{$prefix}options`");$wpdb->query('SET FOREIGN_KEY_CHECKS=1');$wpdb=$original;wp_cache_flush();
}
echo count($tests).' tests, '.$failed." failures\n";ob_end_flush();exit($failed?1:0);
