<?php
/** S0: public nonce and real anonymous HTTP, not a fabricated nonce/auth double. */
require __DIR__.'/m0/bootstrap.php';
$id=996103;$pid=996107;$page=0;$portal=0;$form=0;$rate_keys=array();$owned=false;$failed=0;$created=false;
$mu=ABSPATH.'wp-content/mu-plugins/eipsi-s0-isolation.php';
function s0_http($path,$body=null,$session=null){$headers=array('Host'=>'127.0.0.1:18080');if($session)$headers['Cookie']='eipsi_session_token='.rawurlencode($session);$r=wp_remote_request('http://127.0.0.1'.$path,array('method'=>$body===null?'GET':'POST','body'=>$body,'headers'=>$headers,'timeout'=>25,'redirection'=>0));m0_assert(!is_wp_error($r),'HTTP transport failed');return$r;}
function s0_json($r){$d=json_decode(wp_remote_retrieve_body($r),true);m0_assert(is_array($d),'Expected JSON');return$d;}
function s0_ajax($action,$data=array(),$session=null){global $nonce,$rate_keys;if(isset($data['email']))$rate_keys[]='eipsi_auth_email_'.md5(strtolower($data['email']).':'.(int)($data['survey_id']??0));return s0_http('/wp-admin/admin-ajax.php',array_merge(array('action'=>$action,'nonce'=>$nonce),$data),$session);}
function s0_cookie($r){foreach(wp_remote_retrieve_cookies($r)as$c)if($c->name==='eipsi_session_token'&&$c->value!=='')return$c->value;return null;}
function s0_no_session($r){global $wpdb,$id;$d=s0_json($r);m0_assert(!s0_cookie($r)&&empty($d['data']['session_token'])&&empty($d['data']['participant_id']),'Email-only request issued session or participant identity');m0_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id")===0,'Email-only session persisted');}
function s0_reset_limits(){global $rate_keys;foreach(array_merge($rate_keys,array('eipsi_auth_origin_'.md5('127.0.0.1'),'eipsi_auth_origin_'.md5('unknown')))as$key)delete_transient($key);$rate_keys=array();}
function s0_mail_token($parameter='eipsi_magic'){global $wpdb;$mail=maybe_unserialize($wpdb->get_var("SELECT option_value FROM {$wpdb->options} WHERE option_name='eipsi_s0_mail'"))?:array();m0_assert(count($mail)>0,'No intercepted mail');$body=html_entity_decode(end($mail)['message'],ENT_QUOTES);m0_assert(preg_match('/[?&]'.preg_quote($parameter,'/').'=([^&"\s<>]+)/',$body,$m),'Secret link missing from mail');return rawurldecode($m[1]);}
function s0_password($password='s0-valid-password'){global $id;return s0_ajax('eipsi_participant_login',array('email'=>'s0-victim@example.invalid','survey_id'=>$id,'password'=>$password));}
function s0_assert_session($r){global $pid;$token=s0_cookie($r);m0_assert(wp_remote_retrieve_response_code($r)<400,'Authentication HTTP failed');m0_assert($token,'HttpOnly session cookie missing');$info=s0_json(s0_ajax('eipsi_participant_info',array(),$token));m0_assert(!empty($info['success'])&&(int)$info['data']['participant_id']===$pid,'Valid proof did not authorize protected participant');return$token;}
function s0_pool($token=null){global$id;$headers=array('Host'=>'127.0.0.1:18080','Content-Type'=>'application/json');if($token)$headers['Cookie']='eipsi_session_token='.rawurlencode($token);return wp_remote_post('http://127.0.0.1/?rest_route=/eipsi/v1/pool-assign',array('headers'=>$headers,'body'=>wp_json_encode(array('pool_id'=>996101,'participant_id'=>996107,'survey_id'=>$id)),'timeout'=>25,'redirection'=>0));}
$tests=array();
$tests['P0 original: public nonce + known email cannot issue a usable session']=function()use($id){
 $r=s0_ajax('eipsi_participant_login',array('email'=>'s0-victim@example.invalid','survey_id'=>$id));
 // Preserve the original exploit chain, including its protected consumer.
 $d=s0_json($r);$token=$d['data']['session_token']??s0_cookie($r);
 if($token){$info=s0_json(s0_ajax('eipsi_participant_info',array(),$token));m0_assert(empty($info['success']),'P0 reproduced: anonymous email-only session can read participant_info');}
 s0_no_session($r);
};
$tests['HTTP password valid issues canonical session']=function(){s0_assert_session(s0_password());};
$tests['HTTP password wrong never issues a session']=function(){ $r=s0_password('wrong-password');m0_assert(!s0_json($r)['success'],'Wrong password accepted');s0_no_session($r);};
$tests['HTTP email request existing/missing has identical envelope']=function()use($id){$a=s0_ajax('eipsi_participant_login',array('email'=>'s0-victim@example.invalid','survey_id'=>$id));$b=s0_ajax('eipsi_participant_login',array('email'=>'s0-missing@example.invalid','survey_id'=>$id));m0_assert(wp_remote_retrieve_response_code($a)===wp_remote_retrieve_response_code($b)&&s0_json($a)===s0_json($b),'Account enumeration');s0_no_session($a);s0_no_session($b);};
foreach(array('eipsi_request_magic_link','eipsi_participant_magic_link')as$action){$tests['HTTP '.$action.' same response, no session']=function()use($id,$action){$a=s0_ajax($action,array('email'=>'s0-victim@example.invalid','survey_id'=>$id));$b=s0_ajax($action,array('email'=>'s0-missing@example.invalid','survey_id'=>$id));m0_assert(s0_json($a)===s0_json($b),'Magic request enumerates');s0_no_session($a);s0_no_session($b);m0_assert((bool)s0_mail_token(),'Token was not sent');};}
$tests['HTTP requested mailed link creates session only upon consumption']=function()use($id){global$portal,$wpdb,$pid;$r=s0_ajax('eipsi_participant_login',array('email'=>'s0-victim@example.invalid','survey_id'=>$id));s0_no_session($r);$token=s0_mail_token();$row=EIPSI_MagicLinksService::get_magic_link_by_token(hash('sha256',$token));m0_assert($row&&$row->used_at===null&&$row->token_hash!==$token&&!isset($row->token_plain),'Token persistence contract changed');$r=s0_http('/?page_id='.$portal.'&eipsi_magic='.rawurlencode($token));m0_assert(wp_remote_retrieve_response_code($r)===302,'Mailed link should consume before output');s0_assert_session($r);m0_assert(EIPSI_MagicLinksService::validate_magic_link($token)['reason']==='already_used','Mailed token not consumed');};
$tests['HTTP survey-access valid token, one-hour session']=function()use($id,$pid){global$wpdb;$token=EIPSI_MagicLinksService::generate_magic_link($id,$pid);$r=s0_http('/survey-access/?ml='.rawurlencode($token));m0_assert(wp_remote_retrieve_response_code($r)===302,'Valid link denied');$session=s0_assert_session($r);$expiry=$wpdb->get_var($wpdb->prepare("SELECT expires_at FROM {$wpdb->prefix}survey_sessions WHERE token=%s",hash('sha256',$session)));m0_assert(abs(strtotime($expiry)-time()-HOUR_IN_SECONDS)<10,'Magic route TTL changed');};
$tests['HTTP used token cannot create another session']=function()use($id,$pid){global$wpdb;$token=EIPSI_MagicLinksService::generate_magic_link($id,$pid);s0_assert_session(s0_http('/survey-access/?ml='.rawurlencode($token)));$count=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id");$r=s0_http('/survey-access/?ml='.rawurlencode($token));m0_assert(!s0_cookie($r)&&(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id")===$count,'Used token issued new session');};
$tests['HTTP invalid token does not issue session']=function(){global$wpdb,$id;$r=s0_http('/survey-access/?ml=s0-invalid-secret');m0_assert(wp_remote_retrieve_response_code($r)>=400&&!s0_cookie($r)&&!(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id"),'Invalid token session');};
$tests['HTTP expired token does not issue session']=function()use($id,$pid){global$wpdb;$token=EIPSI_MagicLinksService::generate_magic_link($id,$pid);$wpdb->update($wpdb->prefix.'survey_magic_links',array('expires_at'=>gmdate('Y-m-d H:i:s',time()-60)),array('token_hash'=>hash('sha256',$token)));$r=s0_http('/survey-access/?ml='.rawurlencode($token));m0_assert(!s0_cookie($r)&&!(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id"),'Expired token session');};
foreach(array('inactive'=>array('is_active'=>0),'declined'=>array('consent_decision'=>'declined'),'withdrawn'=>array('consent_decision'=>'withdrawn'))as$state=>$change){$tests['HTTP '.$state.' password and secret token both denied']=function()use($id,$pid,$change){global$wpdb;$token=EIPSI_MagicLinksService::generate_magic_link($id,$pid);$wpdb->update($wpdb->prefix.'survey_participants',$change,array('id'=>$pid));s0_no_session(s0_password());$r=s0_http('/survey-access/?ml='.rawurlencode($token));m0_assert(!s0_cookie($r)&&!(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id"),'Ineligible magic session');$a=s0_json(s0_ajax('eipsi_participant_login',array('email'=>'s0-victim@example.invalid','survey_id'=>$id)));$b=s0_json(s0_ajax('eipsi_participant_login',array('email'=>'s0-missing@example.invalid','survey_id'=>$id)));m0_assert($a===$b,'Status exposed');};}
$tests['HTTP original attack cannot unlock REST Pools']=function()use($id){$r=s0_ajax('eipsi_participant_login',array('email'=>'s0-victim@example.invalid','survey_id'=>$id));s0_no_session($r);m0_assert(wp_remote_retrieve_response_code(s0_pool())===401,'Email attacker obtained Pool authorization');};
$tests['HTTP password-authenticated Pools keeps canonical identity']=function()use($id){$token=s0_assert_session(s0_password());$r=s0_pool($token);m0_assert(in_array(wp_remote_retrieve_response_code($r),array(200,201),true),'Valid canonical Pool path denied (HTTP '.wp_remote_retrieve_response_code($r).', '.wp_json_encode(s0_json($r)).')');};
$tests['HTTP fabricated cookie denied by participant_info']=function(){m0_assert(empty(s0_json(s0_ajax('eipsi_participant_info',array(),'s0-forged-token'))['success']),'Fabricated cookie accepted');};
$tests['HTTP logout revokes old cookie']=function(){ $token=s0_assert_session(s0_password());m0_assert(s0_json(s0_ajax('eipsi_participant_logout',array(),$token))['success'],'Logout failed');m0_assert(empty(s0_json(s0_ajax('eipsi_participant_info',array(),$token))['success']),'Logged-out cookie accepted');};
$tests['HTTP origin limiter survives rotating email and study']=function()use($id){for($i=0;$i<20;$i++)m0_assert(s0_json(s0_ajax('eipsi_request_magic_link',array('email'=>'s0-rotate-'.$i.'@example.invalid','survey_id'=>$id+$i)))['success'],'Limit blocked too early');$r=s0_ajax('eipsi_request_magic_link',array('email'=>'s0-extra@example.invalid','survey_id'=>$id));m0_assert((s0_json($r)['data']['code']??'')==='rate_limited','Origin limit bypassed by rotating identity');s0_no_session($r);};
$tests['HTTP per-email limiter counts successful initiation']=function()use($id){for($i=0;$i<5;$i++)m0_assert(s0_json(s0_ajax('eipsi_participant_login',array('email'=>'s0-missing@example.invalid','survey_id'=>$id)))['success'],'Early email limit');$r=s0_ajax('eipsi_participant_login',array('email'=>'s0-missing@example.invalid','survey_id'=>$id));m0_assert((s0_json($r)['data']['code']??'')==='rate_limited','Successful initiation bypasses limiter');s0_no_session($r);};
$tests['HTTP registration without opt-in requests proof, no auto-login']=function()use($id){$r=s0_ajax('eipsi_participant_register',array('email'=>'s0-register@example.invalid','survey_id'=>$id));m0_assert(!empty(s0_json($r)['data']['requires_email_link'])&&s0_json($r)['data']['auto_login']===false,'Registration auto-login remains');s0_no_session($r);m0_assert((bool)s0_mail_token(),'Registration did not send access link');};
$tests['HTTP double opt-in confirmation activates but does not log in']=function()use($id){global$wpdb;$wpdb->update($wpdb->prefix.'survey_studies',array('config'=>'{"double_opt_in":true}'),array('id'=>$id));$r=s0_ajax('eipsi_participant_register',array('email'=>'s0-confirm@example.invalid','survey_id'=>$id));$d=s0_json($r);m0_assert($d['success']&&!empty($d['data']['requires_confirmation'])&&$d['data']['auto_login']===false,'Opt-in envelope');m0_assert(!s0_cookie($r)&&empty($d['data']['session_token']),'Opt-in session before confirmation');$p=EIPSI_Participant_Service::get_by_email($id,'s0-confirm@example.invalid');m0_assert($p&&(int)$p->is_active===0,'Opt-in prematurely active');$token=s0_mail_token('eipsi_confirm');$r=s0_http('/?eipsi_confirm='.rawurlencode($token));m0_assert((int)EIPSI_Participant_Service::get_by_id($p->id)->is_active===1&&!s0_cookie($r),'Confirmation unexpectedly logs in');m0_assert(!(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id"),'Confirmation session persisted');};
$tests['Compatibility passwordless API fail-closed for known and unknown']=function()use($id){$a=EIPSI_Auth_Service::authenticate_passwordless($id,'s0-victim@example.invalid');$b=EIPSI_Auth_Service::authenticate_passwordless($id,'s0-missing@example.invalid');m0_assert($a===$b&&$a['success']===false&&$a['participant_id']===null&&$a['error']==='proof_required','Compatibility still treats email as credential');};

$tests['HTTP legacy login callable cannot authenticate by email']=function()use($id){s0_no_session(s0_ajax('eipsi_s0_legacy_login',array('email'=>'s0-victim@example.invalid','survey_id'=>$id)));};
$tests['HTTP legacy password login remains usable']=function()use($id){s0_assert_session(s0_ajax('eipsi_s0_legacy_login',array('email'=>'s0-victim@example.invalid','survey_id'=>$id,'password'=>'s0-valid-password','redirect_url'=>home_url('/'))));};
$tests['HTTP legacy registration cannot auto-login']=function()use($id){s0_no_session(s0_ajax('eipsi_s0_legacy_register',array('email'=>'s0-legacy-register@example.invalid','survey_id'=>$id,'accept_terms'=>'1')));};
$tests['HTTP legacy double opt-in inactive and no session']=function()use($id){global$wpdb;$wpdb->update($wpdb->prefix.'survey_studies',array('config'=>'{"double_opt_in":true}'),array('id'=>$id));$r=s0_ajax('eipsi_s0_legacy_register',array('email'=>'s0-legacy-confirm@example.invalid','survey_id'=>$id,'accept_terms'=>'1'));m0_assert(!empty(s0_json($r)['data']['requires_confirmation']),'Legacy opt-in missing');s0_no_session($r);m0_assert((int)EIPSI_Participant_Service::get_by_email($id,'s0-legacy-confirm@example.invalid')->is_active===0,'Legacy opt-in prematurely active');};
$tests['HTTP failed single-use claim cannot issue session in either consumer']=function()use($id,$pid){global$wpdb,$portal;$token=EIPSI_MagicLinksService::generate_magic_link($id,$pid);$link=EIPSI_MagicLinksService::validate_magic_link($token);update_option('eipsi_s0_deny_consume',(int)$link['ml_id'],false);try{foreach(array('/survey-access/?ml='.rawurlencode($token),'/?page_id='.$portal.'&eipsi_magic='.rawurlencode($token))as$path){$r=s0_http($path);m0_assert(!s0_cookie($r)&&!(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id"),'Failed consumption still issued session');}}finally{delete_option('eipsi_s0_deny_consume');}};

$tests['HTTP delivery failure shares generic initiation envelope and no session']=function()use($id){update_option('eipsi_s0_deny_delivery',true,false);try{$a=s0_ajax('eipsi_request_magic_link',array('email'=>'s0-victim@example.invalid','survey_id'=>$id));$b=s0_ajax('eipsi_request_magic_link',array('email'=>'s0-missing@example.invalid','survey_id'=>$id));m0_assert(s0_json($a)===s0_json($b),'Delivery failure discloses account');s0_no_session($a);s0_no_session($b);}finally{delete_option('eipsi_s0_deny_delivery');}};
$tests['HTTP existing proven session can extend without changing identity']=function(){global$wpdb,$id;$token=s0_assert_session(s0_password());$r=s0_ajax('eipsi_extend_session',array('ttl_hours'=>24),$token);m0_assert(!empty(s0_json($r)['success']),'Valid session extension denied');s0_assert_session($r);m0_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id")===1,'Extension issued another identity');};
$tests['HTTP extension revokes session when participant becomes ineligible']=function(){global$wpdb,$pid,$id;foreach(array(array('is_active'=>0),array('consent_decision'=>'declined'),array('consent_decision'=>'withdrawn'))as$change){$wpdb->update($wpdb->prefix.'survey_participants',array('is_active'=>1,'consent_decision'=>'accepted'),array('id'=>$pid));$token=s0_assert_session(s0_password());$wpdb->update($wpdb->prefix.'survey_participants',$change,array('id'=>$pid));$r=s0_ajax('eipsi_extend_session',array(),$token);m0_assert(empty(s0_json($r)['success']),'Ineligible session extended');m0_assert(!(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_sessions WHERE survey_id=$id"),'Ineligible session not revoked');}};

try{
 m0_assert(!file_exists($mu),'Existing mail isolation must not be overwritten');wp_mkdir_p(dirname($mu));m0_assert(copy(__DIR__.'/s0/mail-isolation.php',$mu),'Cannot isolate mail');$owned=true;
 foreach(array('survey_studies'=>$id,'survey_participants'=>$pid,'survey_waves'=>996121,'survey_assignments'=>996131,'eipsi_longitudinal_pools'=>996101)as$t=>$i)m0_assert(!$wpdb->get_var("SELECT id FROM {$wpdb->prefix}$t WHERE id=$i"),'Fixture collision');
 m0_assert($wpdb->insert($wpdb->prefix.'survey_studies',array('id'=>$id,'study_code'=>'s0-owned','study_name'=>'S0 fixture','status'=>'active','config'=>'{"double_opt_in":false}'))!==false,$wpdb->last_error);$created=true;
 m0_assert($wpdb->insert($wpdb->prefix.'survey_participants',array('id'=>$pid,'survey_id'=>$id,'email'=>'s0-victim@example.invalid','password_hash'=>wp_hash_password('s0-valid-password'),'is_active'=>1,'consent_decision'=>'accepted'))!==false,$wpdb->last_error);
 $page=wp_insert_post(array('post_type'=>'page','post_status'=>'publish','post_title'=>'S0 owned login','post_content'=>'[eipsi_survey_login survey_id="'.$id.'"]'));m0_assert($page&&!is_wp_error($page),'Page failed');
 $form=wp_insert_post(array('post_type'=>'eipsi_form_template','post_status'=>'publish','post_title'=>'S0 owned form','post_content'=>'<!-- wp:eipsi/form-container --><form class="eipsi-form"><input name="s0-answer"></form><!-- /wp:eipsi/form-container -->'));
 $portal=wp_insert_post(array('post_type'=>'page','post_status'=>'publish','post_title'=>'S0 owned study','post_content'=>'[eipsi_longitudinal_study id="'.$id.'"]'));update_post_meta($portal,'eipsi_study_id',$id);
 m0_assert($wpdb->insert($wpdb->prefix.'survey_waves',array('id'=>996121,'study_id'=>$id,'wave_index'=>1,'name'=>'S0 T1','form_id'=>$form,'status'=>'active'))!==false,$wpdb->last_error);
 m0_assert($wpdb->insert($wpdb->prefix.'survey_assignments',array('id'=>996131,'study_id'=>$id,'wave_id'=>996121,'participant_id'=>$pid,'status'=>'pending'))!==false,$wpdb->last_error);
 m0_assert($wpdb->insert($wpdb->prefix.'eipsi_longitudinal_pools',array('id'=>996101,'pool_name'=>'S0 fixture','status'=>'active','config'=>wp_json_encode(array('version'=>2,'studies'=>array(array('id'=>$id,'probability'=>100)),'method'=>'seeded'))))!==false,$wpdb->last_error);
 $html=wp_remote_retrieve_body(s0_http('/?page_id='.$page));m0_assert(preg_match('/var eipsiAuth\s*=\s*(\{[^;]+\});/',$html,$match),'Public nonce not rendered');$nonce=json_decode($match[1],true)['nonce'];m0_assert($nonce,'Missing public nonce');
 foreach($tests as$name=>$test){try{s0_reset_limits();delete_option('eipsi_s0_mail');$_COOKIE=array();$wpdb->delete($wpdb->prefix.'survey_sessions',array('survey_id'=>$id));$wpdb->update($wpdb->prefix.'survey_participants',array('is_active'=>1,'consent_decision'=>'accepted'),array('id'=>$pid));$wpdb->update($wpdb->prefix.'survey_studies',array('config'=>'{"double_opt_in":false}'),array('id'=>$id));$test();echo'PASS '.$name."\n";}catch(Throwable$e){$failed++;echo'FAIL '.$name.': '.$e->getMessage()."\n";}}
}finally{
 $wpdb->query('ROLLBACK');if($page)wp_delete_post($page,true);
 if($form)wp_delete_post($form,true);if($portal)wp_delete_post($portal,true);
 if($created){$wpdb->query("DELETE jobs FROM {$wpdb->prefix}survey_nudge_jobs jobs INNER JOIN {$wpdb->prefix}survey_assignments a ON JSON_EXTRACT(jobs.payload, '$.assignment_id') = a.id WHERE a.study_id=$id");$wpdb->delete($wpdb->prefix.'eipsi_pool_analytics',array('pool_id'=>996101));foreach(array('survey_sessions'=>'survey_id','survey_magic_links'=>'survey_id','survey_email_log'=>'survey_id','survey_email_confirmations'=>'survey_id','survey_participant_access_log'=>'study_id','survey_assignments'=>'study_id','survey_waves'=>'study_id','survey_participants'=>'survey_id','survey_studies'=>'id')as$t=>$key)$wpdb->query("DELETE FROM {$wpdb->prefix}$t WHERE $key=$id");$wpdb->delete($wpdb->prefix.'eipsi_pool_assignments',array('pool_id'=>996101));$wpdb->delete($wpdb->prefix.'eipsi_longitudinal_pools',array('id'=>996101));}
 s0_reset_limits();
 if($owned)unlink($mu);delete_option('eipsi_s0_deny_consume');delete_option('eipsi_s0_deny_delivery');delete_option('eipsi_s0_mail');delete_transient('eipsi_login_attempts_'.md5('s0-victim@example.invalid'.$id));
}
echo count($tests).' tests, '.$failed." failures\n";ob_end_flush();exit($failed?1:0);
