<?php
define('DOING_CRON',true);
require __DIR__.'/m0/bootstrap.php';
require __DIR__.'/m6/concurrency.php';
$tests=array();$created=false;$request_id=0;$paths=array();$failed=0;
try{
 m0_assert(!$wpdb->get_var("SELECT id FROM {$wpdb->prefix}survey_studies WHERE id=993603")&&!$wpdb->get_var("SELECT id FROM {$wpdb->prefix}survey_participants WHERE id=993607"),'Fixture collision');
 $created=true;
 m0_assert($wpdb->insert($wpdb->prefix.'survey_studies',array('id'=>993603,'study_code'=>'m6-993603','study_name'=>'M6','created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')))!==false,$wpdb->last_error);
 m0_assert($wpdb->insert($wpdb->prefix.'survey_participants',array('id'=>993607,'survey_id'=>993603,'email'=>'m6@example.invalid','password_hash'=>wp_hash_password('fixture'),'is_active'=>1,'consent_decision'=>'accepted','created_at'=>current_time('mysql')))!==false,$wpdb->last_error);
 $tests['M6 HTTP archivo directo histórico bloqueado']=function(){ $r=m0_http('/wp-content/plugins/EIPSI-Forms-Plugin/exports/m6-public-probe.csv');m0_assert(wp_remote_retrieve_response_code($r)===403,'Public exposure'); };
 $tests['M6 HTTP download anónimo denegado']=function(){ $r=m0_http('/wp-admin/admin-ajax.php?action=eipsi_download_admin_export&filename=m6-public-probe.csv&nonce=bad');m0_assert(wp_remote_retrieve_response_code($r)===403,'Anonymous download'); };
 $tests['M6 HTTP download admin autorizado funciona']=function(){ $nonce=m0_admin_nonce('eipsi_export_download');$r=m0_http('/wp-admin/admin-ajax.php?action=eipsi_download_admin_export&filename=m6-public-probe.csv&nonce='.urlencode($nonce),null,true);m0_assert(wp_remote_retrieve_response_code($r)===200&&strpos(wp_remote_retrieve_body($r),'m6_nonsensitive_probe')!==false,'Authorized HTTP download'); };
 $tests['M6 bootstrap owners y action ejecutables']=function(){foreach(array('EIPSI_Submission_Storage_Service','EIPSI_Privacy_Capture_Policy','EIPSI_Export_Query_Service','EIPSI_Download_Authorization_Service') as$c){m0_assert(class_exists($c),'Missing owner');}m0_assert(has_action('wp_ajax_eipsi_download_admin_export','eipsi_download_admin_export_handler')===10,'Missing handler');};
 $tests['M6 aprobación concurrente solo un ganador']=function()use(&$request_id,&$paths){global$wpdb;$wpdb->insert($wpdb->prefix.'survey_data_requests',array('participant_id'=>993607,'survey_id'=>993603,'request_type'=>'export','status'=>'pending','created_at'=>current_time('mysql')));$request_id=(int)$wpdb->insert_id;$r=m6_concurrent('approve',$request_id);m0_assert(count(array_filter($r,function($v){return !empty($v['success']);}))===1,'Double approval');$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}survey_data_requests WHERE id=%d",$request_id));$data=json_decode($row->result_data,true);$paths[]=$data['file_path']??'';m0_assert($row->status==='completed'&&is_file(end($paths)),'Incomplete artifact');};
 $tests['M6 cleanup concurrente con writer declara límite local']=function(){global$wpdb;$r=m6_concurrent('cleanup');m0_assert($r[0]['success']&&$r[1]['success']&&!$r[0]['coverage']['complete'],'Concurrency false claim');m0_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}vas_form_results WHERE form_name='m6-race'")===1,'Lost answer');};
 $tests['M6 fallback concurrente confirma dos IDs locales distintos']=function(){global$wpdb;$saved=array();foreach(array('host','user','password','name','enabled','last_updated')as$key){$saved[$key]=get_option('eipsi_external_db_'.$key,null);}try{$external=new EIPSI_External_Database();$external->save_credentials('eipsi-m0-db','m0','intentionally-wrong','m6_external');$r=m6_concurrent('fallback');m0_assert($r[0]['success']&&$r[1]['success']&&$r[0]['fallback_used']&&$r[1]['fallback_used']&&$r[0]['submission_id']!==$r[1]['submission_id'],'Fallback race');}finally{foreach($saved as$key=>$value){if($value===null){delete_option('eipsi_external_db_'.$key);}else{update_option('eipsi_external_db_'.$key,$value);}}}};
 $tests['M6 emergencia concurrente confirma dos IDs distintos']=function(){ $r=m6_concurrent('emergency');m0_assert($r[0]['success']&&$r[1]['success']&&$r[0]['destination']==='emergency_table_wp'&&$r[1]['destination']==='emergency_table_wp'&&$r[0]['submission_id']!==$r[1]['submission_id'],'Emergency race');};
 foreach($tests as$name=>$test){try{$test();echo"PASS $name\n";}catch(Throwable$e){$failed++;echo"FAIL $name: {$e->getMessage()}\n";}}
}finally{
 if($created){foreach(array('eipsi_emergency_submissions'=>"form_id='m6-race'",'vas_form_results'=>"form_name='m6-race'",'survey_data_requests'=>'participant_id=993607','survey_participant_access_log'=>'participant_id=993607','survey_audit_log'=>'survey_id=993603','survey_sessions'=>'participant_id=993607','survey_participants'=>'id=993607','survey_studies'=>'id=993603')as$t=>$where){$wpdb->query("DELETE FROM {$wpdb->prefix}{$t} WHERE $where");}}
 foreach($paths as$p){if($p&&is_file($p)&&strpos(basename($p),'eipsi-personal-')===0){unlink($p);}}
}
echo count($tests).' tests, '.$failed." failures\n";ob_end_flush();exit($failed?1:0);
