<?php
/** S1 real WordPress/MariaDB/HTTP: owned fixtures, no productive doubles. */
require __DIR__.'/m0/bootstrap.php';
require_once EIPSI_FORMS_PLUGIN_DIR.'includes/services/Wave_Service.php';
require __DIR__.'/s1/concurrency.php';
$sid=997103;$pid=997107;$posts=array();$created=false;$failed=0;$cron_before=get_option('cron');
$form_pages=array();
$mu=ABSPATH.'wp-content/mu-plugins/eipsi-s1-isolation.php';$owned=false;$session=null;
function s1_assignment($wave=997122){global$wpdb;return$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}survey_assignments WHERE participant_id=997107 AND wave_id=%d",$wave));}
function s1_set($data,$wave=997122){global$wpdb;m0_assert($wpdb->update($wpdb->prefix.'survey_assignments',$data,array('participant_id'=>997107,'wave_id'=>$wave))!==false,$wpdb->last_error);}
function s1_reset(){global$wpdb;$wpdb->update($wpdb->prefix.'survey_studies',array('status'=>'active'),array('id'=>997103));s1_set(array('status'=>'pending','submitted_at'=>null,'available_at'=>gmdate('Y-m-d H:i:s',time()+DAY_IN_SECONDS),'due_at'=>gmdate('Y-m-d H:i:s',time()+2*DAY_IN_SECONDS)));$wpdb->query("DELETE FROM {$wpdb->prefix}vas_form_results WHERE participant_id IN ('997107','s1-anon')");}
function s1_request($wave=997122,$extra=array()){return array_merge(array('form_id'=>'s1-t'.($wave-997120),'participant_id'=>'s1-browser','session_id'=>'s1-http','wave_id'=>$wave,'study_id'=>997103,'answer'=>'4'),$extra);}
function s1_http_submit($wave=997122,$extra=array()) {global$session;wp_set_current_user(0);$nonce=wp_create_nonce('eipsi_forms_nonce');wp_set_current_user(1);$r=wp_remote_post('http://127.0.0.1/wp-admin/admin-ajax.php',array('headers'=>array('Host'=>'127.0.0.1:18080','Cookie'=>'eipsi_session_token='.rawurlencode($session['token'])),'body'=>array_merge(array('action'=>'eipsi_forms_submit_form','nonce'=>$nonce),s1_request($wave,$extra)),'timeout'=>25,'redirection'=>0));m0_assert(!is_wp_error($r),'Transport failed');$d=json_decode(wp_remote_retrieve_body($r),true);m0_assert(is_array($d),'HTTP not JSON: '.wp_remote_retrieve_response_code($r));return array($r,$d);}
$tests=array();
$tests['Original service exploit: authorized future T2 must not transition']=function(){global$session;$_COOKIE['eipsi_session_token']=$session['token'];$auth=EIPSI_Auth_Service::authorize_form_operation('s1-t2',s1_request());m0_assert($auth['success'],'Fixture identity not authorized');$r=EIPSI_Longitudinal_Assignment_Transition_Service::submit_locked(997107,997103,997122);m0_assert(s1_assignment()->status==='pending','Service P1 reproduced: future T2 became submitted');m0_assert(is_array($r)&&!$r['success'],'Future transition accepted');};
$tests['Original HTTP exploit: future T2 rejects before persistence']=function(){global$wpdb;list($r,$d)=s1_http_submit();$status=s1_assignment()->status;$rows=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}vas_form_results WHERE participant_id='997107'");m0_assert(empty($d['success'])&&$status==='pending'&&$rows===0,'HTTP P1 reproduced: status='.wp_remote_retrieve_response_code($r).', success='.json_encode($d['success']).', assignment='.$status.', response_rows='.$rows);};
$clock='2026-10-06 12:00:00';
foreach(array('NULL'=>null,'past'=>'2026-10-06 11:59:59','equal'=>$clock,'future'=>'2026-10-06 12:00:01')as$label=>$available){foreach(array(1,2,3)as$index){$tests['Temporal available '.$label.' T'.$index]=function()use($clock,$available,$label,$index){$r=EIPSI_Longitudinal_Assignment_Transition_Service::evaluate_temporal(array('status'=>'pending','study_status'=>'active','wave_index'=>$index,'available_at'=>$available,'due_at'=>null),$clock);$allowed=$label!=='future'&&($available!==null||$index===1);m0_assert($r['success']===$allowed,'Availability boundary wrong');if(!$allowed)m0_assert($r['data']['code']==='not_yet_available','Availability code wrong');};}}
foreach(array('NULL'=>null,'future'=>'2026-10-06 12:00:01','equal'=>$clock,'past'=>'2026-10-06 11:59:59')as$label=>$due){$tests['Temporal deadline '.$label]=function()use($clock,$due,$label){$r=EIPSI_Longitudinal_Assignment_Transition_Service::evaluate_temporal(array('status'=>'pending','study_status'=>'active','wave_index'=>2,'available_at'=>'2026-10-06 11:00:00','due_at'=>$due),$clock);m0_assert($r['success']===in_array($label,array('NULL','future'),true),'Deadline boundary wrong');if(!$r['success'])m0_assert($r['data']['code']==='deadline_passed','Deadline code wrong');};}
foreach(array('pending','in_progress','submitted','skipped','expired')as$status){$tests['Temporal assignment status '.$status]=function()use($status,$clock){$r=EIPSI_Longitudinal_Assignment_Transition_Service::evaluate_temporal(array('status'=>$status,'study_status'=>'active','wave_index'=>1,'available_at'=>null,'due_at'=>null),$clock);m0_assert($r['success']===in_array($status,array('pending','in_progress'),true),'Status contract changed');if(!$r['success'])m0_assert($r['data']['code']==='invalid_assignment_state','Wrong state code');};}
foreach(array('active','paused','completed')as$status){$tests['Temporal study status '.$status]=function()use($status,$clock){$r=EIPSI_Longitudinal_Assignment_Transition_Service::evaluate_temporal(array('status'=>'pending','study_status'=>$status,'wave_index'=>1),$clock);m0_assert($r['success']===($status!=='completed'),'Study portal contract changed');};}
$tests['HTTP T1 NULL availability remains immediately submitable']=function(){s1_set(array('status'=>'pending','submitted_at'=>null,'available_at'=>null,'due_at'=>null),997121);list($r,$d)=s1_http_submit(997121);m0_assert(!empty($d['success'])&&s1_assignment(997121)->status==='submitted','T1 rejected');m0_assert(s1_assignment(997121)->t1_completed_at,'T1 anchor missing');};
$tests['HTTP T2 exactly available accepted']=function(){s1_set(array('available_at'=>current_time('mysql')));list($r,$d)=s1_http_submit();m0_assert(!empty($d['success'])&&s1_assignment()->status==='submitted','Inclusive availability rejected');};
$tests['HTTP available T2 and valid session accepted']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-60)));list($r,$d)=s1_http_submit();m0_assert(!empty($d['success'])&&s1_assignment()->status==='submitted','Available T2 rejected');};
$tests['HTTP T2 NULL deadline accepted']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-60),'due_at'=>null));list($r,$d)=s1_http_submit();m0_assert(!empty($d['success']),'NULL deadline rejected');};
foreach(array('equal'=>0,'past'=>-60)as$label=>$offset){$tests['HTTP T2 deadline '.$label.' rejects before Storage']=function()use($offset){global$wpdb;s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-3600),'due_at'=>gmdate('Y-m-d H:i:s',time()+$offset)));list($r,$d)=s1_http_submit();m0_assert(wp_remote_retrieve_response_code($r)===403&&($d['data']['code']??'')==='deadline_passed'&&s1_assignment()->status==='pending','Deadline rejection contract');m0_assert(!(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}vas_form_results WHERE participant_id='997107'"),'Deadline persisted response');};}
$tests['HTTP T2 missing anchor rejects']=function(){s1_set(array('available_at'=>null));list($r,$d)=s1_http_submit();m0_assert(($d['data']['code']??'')==='not_yet_available'&&s1_assignment()->status==='pending','Missing T2 window accepted');};
$tests['HTTP future T3 rejects']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()+DAY_IN_SECONDS),'due_at'=>gmdate('Y-m-d H:i:s',time()+2*DAY_IN_SECONDS)),997123);list($r,$d)=s1_http_submit(997123);m0_assert(($d['data']['code']??'')==='not_yet_available'&&s1_assignment(997123)->status==='pending','Future T3 accepted');};
foreach(array('participant_id'=>997108,'study_id'=>997104)as$field=>$value){$tests['HTTP foreign '.$field.' rejected']=function()use($field,$value){s1_set(array('available_at'=>current_time('mysql')));list($r,$d)=s1_http_submit(997122,array($field=>$value));m0_assert(wp_remote_retrieve_response_code($r)===403&&empty($d['success'])&&s1_assignment()->status==='pending','Foreign context accepted');};}
$tests['HTTP anonymous form unaffected']=function(){list($r,$d)=s1_http_submit(997122,array('form_id'=>'s1-anon','wave_id'=>0,'study_id'=>0,'participant_id'=>'s1-anon'));m0_assert(!empty($d['success']),'Anonymous form rejected');};
$tests['HTTP retry when availability arrives succeeds']=function(){list($r,$d)=s1_http_submit();m0_assert(empty($d['success']),'Future retry initially accepted');s1_set(array('available_at'=>current_time('mysql')));list($r,$d)=s1_http_submit();m0_assert(!empty($d['success'])&&s1_assignment()->status==='submitted','Available retry failed');};
$tests['HTTP render unavailable agrees with backend']=function(){global$session,$form_pages;$r=wp_remote_get('http://127.0.0.1/?page_id='.$form_pages[2].'&wave_id=997122',array('headers'=>array('Host'=>'127.0.0.1:18080','Cookie'=>'eipsi_session_token='.rawurlencode($session['token']))));m0_assert(!is_wp_error($r)&&strpos(wp_remote_retrieve_body($r),'todavía no está disponible')!==false,'Renderer did not block future T2');list($r,$d)=s1_http_submit();m0_assert(($d['data']['code']??'')==='not_yet_available','Render/backend disagree');};
$tests['Expiration stale deadline snapshot must not expire extended row']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-3600),'due_at'=>gmdate('Y-m-d H:i:s',time()-60)));$old=s1_assignment();s1_set(array('due_at'=>gmdate('Y-m-d H:i:s',time()+3600)));m0_assert(EIPSI_Longitudinal_Assignment_Transition_Service::expire_snapshot($old)===0&&s1_assignment()->status==='pending','Stale deadline expired extended assignment');};
$tests['Expiration due row still transitions expired']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-3600),'due_at'=>gmdate('Y-m-d H:i:s',time()-60)));m0_assert(EIPSI_Longitudinal_Assignment_Transition_Service::expire_snapshot(s1_assignment())===1&&s1_assignment()->status==='expired','Expiration path broken');};

$tests['Race submit waits for availability and evaluates after lock']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()+1)));$r=s1_concurrent(array('submit'),null,true);$a=s1_assignment();m0_assert(!is_array($r[0]['result'])&&$a->status==='submitted'&&$a->submitted_at>=$a->available_at,'Lock-time availability violated');};
$tests['Race submit vs expiration leaves expired, no premature submitted']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-3600),'due_at'=>gmdate('Y-m-d H:i:s',time()-1)));$r=s1_concurrent(array('submit','expire'));m0_assert(s1_assignment()->status==='expired'&&is_array($r[0]['result'])&&!$r[0]['result']['success'],'Expiration race allowed expired submit');};
$tests['Race two submits has one transition winner']=function(){s1_set(array('available_at'=>current_time('mysql')));$r=s1_concurrent(array('submit','submit'));$winners=count(array_filter($r,function($row){return!is_array($row['result']);}));m0_assert($winners===1&&s1_assignment()->status==='submitted','Concurrent transition duplicated');};
$tests['Race deadline update committed while submit waits is re-read']=function(){s1_set(array('available_at'=>current_time('mysql')));$r=s1_concurrent(array('submit'),array('due_at'=>gmdate('Y-m-d H:i:s',time()-1)));m0_assert(($r[0]['result']['data']['code']??'')==='deadline_passed'&&s1_assignment()->status==='pending','Submit used stale deadline');};
$tests['Race deadline configuration owner vs submit stays coherent']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-7200),'due_at'=>gmdate('Y-m-d H:i:s',time()+3600)));$r=s1_concurrent(array('submit','deadline'));$a=s1_assignment();m0_assert(in_array($a->status,array('pending','submitted'),true),'Invalid final state');if($a->status==='submitted')m0_assert($a->due_at===null||$a->submitted_at<$a->due_at,'Deadline writer invalidated completed submit');else m0_assert(is_array($r[0]['result'])&&!$r[0]['result']['success'],'Pending without rejected submit');};
$tests['Race submit vs skip has one terminal winner']=function(){s1_set(array('available_at'=>current_time('mysql')));$r=s1_concurrent(array('submit','skip'));m0_assert(in_array(s1_assignment()->status,array('submitted','skipped'),true),'Terminal race incoherent');m0_assert((!is_array($r[0]['result']))!==($r[1]['result']===true),'Submit and skip both won');};
$tests['HTTP deadline change after precheck rejects but stored response can remain']=function(){global$wpdb;s1_set(array('available_at'=>current_time('mysql')));update_option('eipsi_s1_move_deadline',true,false);try{list($r,$d)=s1_http_submit();m0_assert(($d['data']['code']??'')==='deadline_passed'&&s1_assignment()->status==='pending','Lock recheck missed deadline changed during Storage');m0_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}vas_form_results WHERE participant_id='997107'")===1,'Storage/assignment race characterization changed');}finally{delete_option('eipsi_s1_move_deadline');}};
$tests['HTTP T1 T2 T3 preserve base-one and completion hooks']=function(){global$wpdb;delete_option('eipsi_s1_completion');foreach(array(1,2,3)as$index){s1_set(array('status'=>'pending','submitted_at'=>null,'available_at'=>$index===1?null:current_time('mysql'),'due_at'=>gmdate('Y-m-d H:i:s',time()+3600)),997120+$index);list($r,$d)=s1_http_submit(997120+$index);m0_assert(!empty($d['success']),'Sequential T'.$index.' failed');if($index<3)m0_assert((int)$d['data']['next_wave']['wave_index']===$index+1,'Next wave index changed');} $events=maybe_unserialize($wpdb->get_var("SELECT option_value FROM {$wpdb->options} WHERE option_name='eipsi_s1_completion'"));m0_assert(array_column($events,'wave_index')===array(1,2,3),'Completion hook indices changed');};

$tests['HTTP request cannot forge earlier availability']=function(){list($r,$d)=s1_http_submit(997122,array('available_at'=>'2020-01-01 00:00:00','due_at'=>'2099-01-01 00:00:00','metadata'=>'{"available_at":"2020-01-01 00:00:00"}'));m0_assert(($d['data']['code']??'')==='not_yet_available'&&s1_assignment()->status==='pending','Client dates bypassed availability');};
$tests['HTTP request cannot forge later deadline']=function(){s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-3600),'due_at'=>gmdate('Y-m-d H:i:s',time()-1)));list($r,$d)=s1_http_submit(997122,array('due_at'=>'2099-01-01 00:00:00'));m0_assert(($d['data']['code']??'')==='deadline_passed'&&s1_assignment()->status==='pending','Client dates bypassed deadline');};
$tests['Temporal precheck uses longitudinal writer clock at nonzero WP offset']=function(){$offset=get_option('gmt_offset');$zone=get_option('timezone_string');try{update_option('timezone_string','');update_option('gmt_offset',5);$local=current_time('mysql');s1_set(array('available_at'=>$local,'due_at'=>date('Y-m-d H:i:s',current_time('timestamp')+60)));m0_assert(EIPSI_Longitudinal_Assignment_Transition_Service::precheck_submission(997107,997103,997122)['success'],'Existing writer clock mismatch');s1_set(array('due_at'=>$local));m0_assert(EIPSI_Longitudinal_Assignment_Transition_Service::precheck_submission(997107,997103,997122)['data']['code']==='deadline_passed','Local exact deadline mismatch');}finally{update_option('gmt_offset',$offset);update_option('timezone_string',$zone);}};
$tests['HTTP completed study rejects without Storage']=function(){global$wpdb;s1_set(array('available_at'=>current_time('mysql')));$wpdb->update($wpdb->prefix.'survey_studies',array('status'=>'completed'),array('id'=>997103));list($r,$d)=s1_http_submit();m0_assert(wp_remote_retrieve_response_code($r)===403&&empty($d['success'])&&s1_assignment()->status==='pending','Closed study accepted');m0_assert(!(int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}vas_form_results WHERE participant_id='997107'"),'Completed study stored response');};
$tests['HTTP paused study preserves existing portal permission']=function(){global$wpdb;s1_set(array('available_at'=>current_time('mysql')));$wpdb->update($wpdb->prefix.'survey_studies',array('status'=>'paused'),array('id'=>997103));list($r,$d)=s1_http_submit();m0_assert(!empty($d['success']),'S1 invented paused-study rejection');};

$tests['HTTP render and submit honor extended deadline beyond original window']=function(){global$session,$form_pages;s1_set(array('available_at'=>gmdate('Y-m-d H:i:s',time()-7200),'due_at'=>gmdate('Y-m-d H:i:s',time()+3600)));$r=wp_remote_get('http://127.0.0.1/?page_id='.$form_pages[2].'&wave_id=997122',array('headers'=>array('Host'=>'127.0.0.1:18080','Cookie'=>'eipsi_session_token='.rawurlencode($session['token']))));m0_assert(!is_wp_error($r)&&strpos(wp_remote_retrieve_body($r),'eipsi-form-template-wrapper')!==false&&s1_assignment()->status==='pending','Renderer ignored extended canonical deadline');list($r,$d)=s1_http_submit();m0_assert(!empty($d['success'])&&s1_assignment()->status==='submitted','Extended deadline denied by backend');};

try{
 foreach(array('survey_studies'=>997103,'survey_participants'=>997107,'survey_waves'=>997121,'survey_assignments'=>997131)as$table=>$id)m0_assert(!$wpdb->get_var("SELECT id FROM {$wpdb->prefix}$table WHERE id=$id"),'Fixture collision');
 m0_assert(!file_exists($mu),'Existing isolation must not be overwritten');wp_mkdir_p(dirname($mu));m0_assert(copy(__DIR__.'/s1/mail-isolation.php',$mu),'Mail isolation failed');$owned=true;
 m0_assert($wpdb->insert($wpdb->prefix.'survey_studies',array('id'=>$sid,'study_code'=>'s1-owned','study_name'=>'S1 fixture','status'=>'active','config'=>'{"double_opt_in":false}'))!==false,$wpdb->last_error);$created=true;
 m0_assert($wpdb->insert($wpdb->prefix.'survey_participants',array('id'=>$pid,'survey_id'=>$sid,'email'=>'s1-victim@example.invalid','password_hash'=>wp_hash_password('s1-valid-password'),'is_active'=>1,'consent_decision'=>'accepted','t1_completed_at'=>gmdate('Y-m-d H:i:s',time()-HOUR_IN_SECONDS)))!==false,$wpdb->last_error);
 foreach(array(1,2,3)as$index){$name='s1-t'.$index;$form=wp_insert_post(array('post_type'=>'eipsi_form_template','post_status'=>'publish','post_title'=>$name,'post_content'=>'<!-- wp:eipsi/form-container {"formName":"'.$name.'"} --><form class="eipsi-form"><input name="answer"></form><!-- /wp:eipsi/form-container -->'));m0_assert($form&&!is_wp_error($form),'Form failed');$posts[]=$form;update_post_meta($form,'_eipsi_form_name',$name);m0_assert($wpdb->insert($wpdb->prefix.'survey_waves',array('id'=>997120+$index,'study_id'=>$sid,'wave_index'=>$index,'name'=>'S1 T'.$index,'form_id'=>$form,'status'=>'active','offset_minutes'=>($index-1)*60,'window_minutes'=>60))!==false,$wpdb->last_error);m0_assert($wpdb->insert($wpdb->prefix.'survey_assignments',array('id'=>997130+$index,'study_id'=>$sid,'wave_id'=>997120+$index,'participant_id'=>$pid,'status'=>$index===1?'submitted':'pending','submitted_at'=>$index===1?gmdate('Y-m-d H:i:s',time()-HOUR_IN_SECONDS):null))!==false,$wpdb->last_error);}
 $anon=wp_insert_post(array('post_type'=>'eipsi_form_template','post_status'=>'publish','post_title'=>'S1 anon','post_content'=>'<!-- wp:eipsi/form-container {"formName":"s1-anon"} --><form class="eipsi-form"><input name="answer"></form><!-- /wp:eipsi/form-container -->'));$posts[]=$anon;update_post_meta($anon,'_eipsi_form_name','s1-anon');
 foreach(array_slice($posts,0,3)as$index=>$form){$page=wp_insert_post(array('post_type'=>'page','post_status'=>'publish','post_title'=>'S1 form page','post_content'=>'[eipsi_form id="'.$form.'"]'));$posts[]=$page;$form_pages[$index+1]=$page;}
 $auth=EIPSI_Auth_Service::authenticate($sid,'s1-victim@example.invalid','s1-valid-password');m0_assert($auth['success'],'Password fixture failed');$session=EIPSI_Auth_Service::create_session($auth['participant_id'],$sid);m0_assert($session['success'],'Session fixture failed');
 foreach($tests as$name=>$test){try{s1_reset();$test();echo 'PASS '.$name."\n";}catch(Throwable$e){$failed++;echo 'FAIL '.$name.': '.$e->getMessage()."\n";}}
}finally{
 $wpdb->query('ROLLBACK');if($created){$wpdb->query("DELETE j FROM {$wpdb->prefix}survey_nudge_jobs j JOIN {$wpdb->prefix}survey_assignments a ON JSON_EXTRACT(j.payload,'$.assignment_id')=a.id WHERE a.study_id=$sid");foreach(array('survey_sessions'=>'survey_id','survey_magic_links'=>'survey_id','survey_audit_log'=>'survey_id','survey_email_log'=>'survey_id','survey_participant_access_log'=>'study_id','survey_assignments'=>'study_id','survey_waves'=>'study_id','survey_participants'=>'survey_id','survey_studies'=>'id')as$table=>$key)$wpdb->query("DELETE FROM {$wpdb->prefix}$table WHERE $key=$sid");$wpdb->query("DELETE FROM {$wpdb->prefix}vas_form_results WHERE participant_id IN ('997107','s1-anon')");}foreach($posts as$post)wp_delete_post($post,true);if($owned)unlink($mu);delete_option('eipsi_s1_move_deadline');delete_option('eipsi_s1_completion');update_option('cron',$cron_before);$_COOKIE=array();
}
echo count($tests).' tests, '.$failed." failures\n";ob_end_flush();exit($failed?1:0);
