<?php
/** M7 real WordPress/MariaDB characterization; disposable database only. */
define('DOING_CRON',true);
require __DIR__.'/m0/bootstrap.php';
require __DIR__.'/m7/concurrency.php';
$tests=array();$failed=0;$created=false;$posts=array();$extra_pools=array();
function m7_request($params){$r=new WP_REST_Request('POST','/eipsi/v1/pool-assign');$r->set_header('Content-Type','application/json');$r->set_body(wp_json_encode($params));return $r;}
function m7_session(){ $s=EIPSI_Auth_Service::create_session(994707,994703);m0_assert($s['success'],'Session failed');$_COOKIE[$s['cookie_name']]=$s['token'];return $s; }
function m7_http($action,$data=array(),$session=null,$admin=false){
 $headers=array('Host'=>'127.0.0.1:18080');$cookies=array();
 if($admin){foreach(m0_admin_cookies()as$n=>$v){$cookies[]=new WP_Http_Cookie(array('name'=>$n,'value'=>$v));}}
 else{wp_set_current_user(0);} $nonce=wp_create_nonce($action==='eipsi_load_form'?'eipsi_randomization_nonce':'eipsi_pool_access');wp_set_current_user(1);
 if($session){$headers['Cookie']=$session['cookie_name'].'='.rawurlencode($session['token']);}
 $r=wp_remote_post('http://127.0.0.1/wp-admin/admin-ajax.php',array('headers'=>$headers,'cookies'=>$cookies,'timeout'=>20,'body'=>array_merge(array('action'=>$action,'nonce'=>$nonce,'eipsi_pool_join_nonce'=>$nonce),$data)));
 m0_assert(!is_wp_error($r),'HTTP transport');return array(wp_remote_retrieve_response_code($r),json_decode(wp_remote_retrieve_body($r),true));
}
function m7_reset(){global$wpdb;$_COOKIE=array();$_POST=array();wp_set_current_user(1);$wpdb->delete($wpdb->prefix.'eipsi_pool_analytics',array('pool_id'=>994701));$wpdb->delete($wpdb->prefix.'eipsi_pool_assignments',array('pool_id'=>994701));$wpdb->delete($wpdb->prefix.'eipsi_randomization_assignments',array('randomization_id'=>'m7-config'));$wpdb->delete($wpdb->prefix.'eipsi_manual_overrides',array('randomization_id'=>'m7-config'));$wpdb->update($wpdb->prefix.'survey_participants',array('is_active'=>1,'consent_decision'=>'accepted','status'=>'active'),array('id'=>994707));$wpdb->update($wpdb->prefix.'eipsi_longitudinal_pools',array('status'=>'active'),array('id'=>994701));}
function m7_assign(){return(new EIPSI_Pool_Assignment_Service())->assign_participant(994701,994707);}
function m7_cfg(){global$form,$other_form;return array('config_id'=>'m7-config','method'=>'seeded','metodo'=>'seeded','seed'=>'fixture','formularios'=>array(array('id'=>$form),array('id'=>$other_form)),'probabilidades'=>array($form=>30,$other_form=>70),'persistent_mode'=>true);}
try{
 m0_assert(!$wpdb->get_var("SELECT id FROM {$wpdb->prefix}survey_studies WHERE id IN (994703,994704)")&&!$wpdb->get_var("SELECT id FROM {$wpdb->prefix}eipsi_longitudinal_pools WHERE id=994701"),'Fixture collision');$created=true;$now=current_time('mysql');
 foreach(array(994703,994704)as$id){m0_assert($wpdb->insert($wpdb->prefix.'survey_studies',array('id'=>$id,'study_code'=>'m7-'.$id,'study_name'=>'M7','created_at'=>$now,'updated_at'=>$now,'config'=>'{}'))!==false,$wpdb->last_error);}
 foreach(array(994707=>994703,994708=>994704)as$id=>$study){m0_assert($wpdb->insert($wpdb->prefix.'survey_participants',array('id'=>$id,'survey_id'=>$study,'email'=>'m7-'.$id.'@example.invalid','password_hash'=>wp_hash_password('fixture'),'is_active'=>1,'consent_decision'=>'accepted','created_at'=>$now))!==false,$wpdb->last_error);}
 m0_assert($wpdb->insert($wpdb->prefix.'eipsi_longitudinal_pools',array('id'=>994701,'pool_name'=>'M7 fixture','status'=>'active','config'=>wp_json_encode(array('studies'=>array(array('id'=>994703,'probability'=>100)),'method'=>'seeded'))))!==false,$wpdb->last_error);
 $form=wp_insert_post(array('post_type'=>'eipsi_form_template','post_status'=>'publish','post_title'=>'M7 form','post_content'=>'<!-- wp:paragraph --><p>M7 public content</p><!-- /wp:paragraph -->'));$posts[]=$form;
 $other_form=wp_insert_post(array('post_type'=>'eipsi_form_template','post_status'=>'publish','post_title'=>'M7 variant','post_content'=>'<p>M7 other variant</p>'));$posts[]=$other_form;
 $draft=wp_insert_post(array('post_type'=>'eipsi_form_template','post_status'=>'draft','post_title'=>'M7 draft'));$posts[]=$draft;
 $page=wp_insert_post(array('post_type'=>'page','post_status'=>'publish','post_title'=>'M7 config','post_content'=>''));$posts[]=$page;
 $tests['Pool config create uses real pool_name schema']=function()use(&$extra_pools){$r=eipsi_rest_pool_config(m7_request(array('name'=>'M7 created','studies'=>array(array('id'=>994703,'probability'=>100)))));m0_assert($r->get_status()===201,'Create failed');$id=$r->get_data()['pool_id'];$extra_pools[]=$id;m0_assert((new EIPSI_Pool_Repository())->get_pool($id)->pool_name==='M7 created','Name not persisted');};
 $tests['Pool config invalid weights rejected']=function(){m0_assert(eipsi_rest_pool_config(m7_request(array('studies'=>array(array('id'=>994703,'probability'=>50)))))->get_status()===400,'Invalid weights accepted');};
 $tests['Pool lookup missing returns null']=function(){m0_assert(!(new EIPSI_Pool_Repository())->get_pool(0),'Missing pool');};
 $tests['Pool new assignment maps selected study and DTO']=function(){$a=m7_assign();m0_assert($a&&(int)$a->study_id===994703&&!$a->is_existing&&isset($a->id,$a->pool_id,$a->completed),'New assignment DTO');};
 $tests['Pool existing assignment stable with access count']=function(){$a=m7_assign();$b=m7_assign();m0_assert($a->id===$b->id&&$b->is_existing&&$b->access_count===1,'Existing unstable');};
 $tests['Pool inactive rejected without persistence']=function(){global$wpdb;$wpdb->update($wpdb->prefix.'eipsi_longitudinal_pools',array('status'=>'inactive'),array('id'=>994701));m0_assert(!m7_assign(),'Inactive assigned');};
 $tests['Pool REST public 401']=function(){m0_assert(eipsi_rest_pool_assign(m7_request(array('pool_id'=>994701)))->get_status()===401,'Public allowed');};
 $tests['Pool REST spoof 403']=function(){m7_session();m0_assert(eipsi_rest_pool_assign(m7_request(array('pool_id'=>994701,'participant_id'=>994708)))->get_status()===403,'Spoof accepted');};
 $tests['Pool REST foreign study 403']=function(){m7_session();m0_assert(eipsi_rest_pool_assign(m7_request(array('pool_id'=>994701,'study_id'=>994704)))->get_status()===403,'Study spoof');};
 $tests['Pool REST session identity 201 then 200']=function(){m7_session();$r=m7_request(array('pool_id'=>994701));m0_assert(eipsi_rest_pool_assign($r)->get_status()===201&&eipsi_rest_pool_assign($r)->get_status()===200,'Status contract');};
 foreach(array('inactive'=>array('is_active'=>0),'withdrawn'=>array('consent_decision'=>'withdrawn'))as$name=>$state){$tests['Pool REST rejects '.$name]=function()use($state){global$wpdb;m7_session();$wpdb->update($wpdb->prefix.'survey_participants',$state,array('id'=>994707));m0_assert(eipsi_rest_pool_assign(m7_request(array('pool_id'=>994701)))->get_status()===401,'Invalid session accepted');};}
 $tests['Pool AJAX request rejects public identity']=function(){list($status,$json)=m7_http('eipsi_request_pool_assignment',array('pool_id'=>994701,'participant_id'=>994707));m0_assert($status===401&&!$json['success'],'Public AJAX');};
 $tests['Pool AJAX request rejects another participant']=function(){list($status,$json)=m7_http('eipsi_request_pool_assignment',array('pool_id'=>994701,'participant_id'=>994708),m7_session());m0_assert($status===403&&!$json['success'],'AJAX spoof');};
 $tests['Pool AJAX nonce rejected']=function(){list($status)=m7_http('eipsi_request_pool_assignment',array('pool_id'=>994701,'nonce'=>'invalid'),m7_session());m0_assert($status===403,'Nonce bypass');};
 $tests['Pool AJAX valid self assignment retains fields']=function(){list($status,$json)=m7_http('eipsi_request_pool_assignment',array('pool_id'=>994701),m7_session());m0_assert($status===200&&$json['success']&&!empty($json['data']['assignment_id'])&&isset($json['data']['study_name'],$json['data']['redirect_url']),'Self assignment failed');};
 $tests['Pool join public email cannot mint session link']=function(){list($status,$json)=m7_http('eipsi_join_pool',array('pool_id'=>994701,'email'=>'m7-994707@example.invalid'));m0_assert($status===401&&!$json['success'],'Email impersonation');};
 $tests['Pool join authenticated self works']=function(){list($status,$json)=m7_http('eipsi_join_pool',array('pool_id'=>994701,'email'=>'m7-994707@example.invalid'),m7_session());m0_assert($status===200&&$json['success']&&isset($json['data']['magic_link_url']),'Self join');};
 $tests['Pool join another email rejected']=function(){list($status)=m7_http('eipsi_join_pool',array('pool_id'=>994701,'email'=>'m7-994708@example.invalid'),m7_session());m0_assert($status===403,'Foreign email');};
 $tests['Pool login email alone cannot authenticate']=function(){list($status)=m7_http('eipsi_pool_auth',array('pool_id'=>994701,'auth_action'=>'login','email'=>'m7-994707@example.invalid'));m0_assert($status===401,'Email login');};
 $tests['Pool analytics reflects one assignment']=function(){m7_assign();m0_assert((new EIPSI_Pool_Analytics_Service())->get_pool_stats(994701)['total']===1,'Analytics count');};
 $tests['Pool completion mutation idempotent']=function(){global$wpdb;m7_assign();$s=new EIPSI_Pool_Assignment_Service();m0_assert($s->mark_completed(994701,994707,'m7')&&!$s->mark_completed(994701,994707,'m7'),'Repeat completion');m0_assert((int)$wpdb->get_var("SELECT SUM(completions) FROM {$wpdb->prefix}eipsi_pool_analytics WHERE pool_id=994701")===1,'Double analytics');};
 $tests['Pool direct completion helper uses same command']=function(){m7_assign();m0_assert(eipsi_check_and_mark_pool_completion(994707,994703,'m7')&&!eipsi_check_and_mark_pool_completion(994707,994703,'m7'),'Direct completion');};
 $tests['Pool hook remains registered at priority ten']=function(){m0_assert(has_action('eipsi_form_submitted','eipsi_check_pool_completion_on_submit')===10,'Hook missing');};
 $tests['Pool shortcode renders anonymous access gate']=function(){m0_assert(strpos(do_shortcode('[eipsi_pool pool_id="994701"]'),'eipsi-pool')!==false,'Shortcode empty');};
 $tests['Pool block authenticated unassigned dashboard renders']=function(){m7_session();m0_assert(strpos(EIPSI_Pool_Block_Renderer::render_block(array('poolId'=>'994701')),'eipsi-pool')!==false,'Block fatal');};
 $tests['Pool M6 roster query compatibility']=function(){m7_assign();m0_assert(is_array(EIPSI_Export_Query_Service::pool_roster_hub(994701)),'Export query shape');};
 $tests['Pool admin analytics unavailable to anonymous callers']=function(){list($status)=m7_http('eipsi_get_pool_analytics',array('pool_id'=>994701,'nonce'=>'invalid'));m0_assert(in_array($status,array(400,403),true),'Admin boundary');};
 $tests['Random DB configuration persists and loads']=function(){m0_assert(eipsi_save_randomization_config_to_db('m7-config',m7_cfg()),'Save');m0_assert(eipsi_get_randomization_config_from_db('m7-config')['method']==='seeded','Load');};
 $tests['Random missing DB config returns null']=function(){m0_assert(eipsi_get_randomization_config_from_db('m7-missing')===null,'Missing config');};
 $tests['Random postmeta lookup retains config key']=function()use($page){update_post_meta($page,'_randomization_config_m7-config',m7_cfg());m0_assert(eipsi_get_randomization_config_from_post_meta($page,'m7-config')===m7_cfg(),'Meta changed');};
 $tests['Random legacy meta preserved']=function()use($page){update_post_meta($page,'_eipsi_random_config',array('enabled'=>true,'forms'=>array(1,2)));m0_assert(get_post_meta($page,'_eipsi_random_config',true)['enabled'],'Legacy removed');};
 $tests['Random shortcode parser deduplicates form IDs']=function(){m0_assert(count(eipsi_parse_shortcodes_input('[eipsi_form id="1"] [eipsi_form id=1] [eipsi_form id=2]'))===2,'Parsing drift');};
 $tests['Random weighted seeded stable']=function(){$a=eipsi_calculate_rct_assignment(m7_cfg(),'fixture');m0_assert($a===eipsi_calculate_rct_assignment(m7_cfg(),'fixture')&&in_array($a,array_column(m7_cfg()['formularios'],'id')),'RNG drift');};
 $tests['Random pure random keeps configured variants']=function(){$c=m7_cfg();$c['method']='pure-random';for($i=0;$i<20;$i++){m0_assert(in_array(eipsi_calculate_rct_assignment($c,'fixture'),array_column($c['formularios'],'id')),'Unknown variant');}};
 $tests['Random frontend algorithm keeps own seeded contract']=function(){m0_assert(eipsi_calculate_frontend_assignment(m7_cfg(),'fixture')===eipsi_calculate_frontend_assignment(m7_cfg(),'fixture'),'Frontend seeded drift');};
 $tests['Random stable assignment persists once']=function(){$a=EIPSI_Randomization_Assignment_Service::resolve('m7-config',m7_cfg(),'fixture');$b=EIPSI_Randomization_Assignment_Service::resolve('m7-config',m7_cfg(),'fixture');m0_assert($a['assigned_form_id']===$b['assigned_form_id']&&$a['is_new_assignment']&&!$b['is_new_assignment'],'Stable resolve');};
 $tests['Random duplicate insert retains first variant']=function()use($form,$other_form){m0_assert(eipsi_create_assignment('m7-config','fixture',$form)&&eipsi_create_assignment('m7-config','fixture',$other_form),'Duplicate failure');m0_assert((int)eipsi_get_existing_assignment('m7-config','fixture')['assigned_form_id']===$form,'First overwritten');};
 $tests['Random active override wins first assignment']=function()use($other_form){m0_assert(EIPSI_Randomization_Override_Service::save('m7-config','fixture',$other_form,'fixture',1,null)!==false,'Override save');$a=EIPSI_Randomization_Assignment_Service::resolve('m7-config',m7_cfg(),'fixture');m0_assert($a['assigned_form_id']===$other_form,'Override ignored');};
 $tests['Random late override preserves stable assignment']=function()use($form,$other_form){eipsi_create_assignment('m7-config','fixture',$form);EIPSI_Randomization_Override_Service::save('m7-config','fixture',$other_form,'fixture',1,null);m0_assert(EIPSI_Randomization_Assignment_Service::resolve('m7-config',m7_cfg(),'fixture')['assigned_form_id']===$form,'Stable changed');};
 $tests['Random revoked override ignored']=function()use($other_form){global$wpdb;EIPSI_Randomization_Override_Service::save('m7-config','fixture',$other_form,'fixture',1,null);$wpdb->update($wpdb->prefix.'eipsi_manual_overrides',array('status'=>'revoked'),array('randomization_id'=>'m7-config'));m0_assert(eipsi_check_manual_override_db('m7-config','fixture')===null,'Revoked active');};
 $tests['Random invalid config returns error']=function(){m0_assert(is_wp_error(EIPSI_Randomization_Assignment_Service::resolve('m7-config',array(),'fixture')),'Invalid accepted');};
 $tests['Random shortcode invalid config gives notice']=function(){m0_assert(strpos(eipsi_randomization_shortcode(array('template'=>0)),'div')!==false,'Notice missing');};
 $tests['Random Gutenberg callback retains generated shortcode']=function(){m0_assert(strpos(eipsi_render_randomization_block(array()),'eipsi-randomization-notice')!==false,'Block callback drift');};
 $tests['Form load published public returns HTML string']=function()use($form){list($status,$j)=m7_http('eipsi_load_form',array('form_id'=>$form));m0_assert($status===200&&$j['success']&&is_string($j['data'])&&strpos($j['data'],'M7 public content')!==false,'HTML contract');};
 foreach(array('missing'=>0,'draft'=>$draft,'arbitrary post'=>$page)as$name=>$id){$tests['Form load rejects '.$name]=function()use($id){list($status,$j)=m7_http('eipsi_load_form',array('form_id'=>$id));m0_assert($status===404&&!$j['success'],'Private/missing post rendered');};}
 $tests['Form load invalid nonce denied']=function()use($form){list($status)=m7_http('eipsi_load_form',array('form_id'=>$form,'nonce'=>'invalid'));m0_assert($status===403,'Nonce bypass');};
 $tests['Form load login required rejects public']=function()use($form){update_post_meta($form,'_eipsi_require_login',1);try{list($status)=m7_http('eipsi_load_form',array('form_id'=>$form));m0_assert($status===401,'Private form exposed');}finally{delete_post_meta($form,'_eipsi_require_login');}};
 $tests['Form load session cannot impersonate other participant']=function()use($form){update_post_meta($form,'_eipsi_require_login',1);try{list($status)=m7_http('eipsi_load_form',array('form_id'=>$form,'participant_id'=>994708),m7_session());m0_assert($status===403,'Cross identity');}finally{delete_post_meta($form,'_eipsi_require_login');}};
 $tests['Random legacy JS retained pending saved-content evidence']=function(){foreach(array('assets/js/eipsi-random.js','src/frontend/eipsi-random.js','assets/js/eipsi-randomization-shortcode.php')as$f){m0_assert(is_file(EIPSI_FORMS_PLUGIN_DIR.$f),'Unsafe purge');}};
 $tests['Concurrent pool assignment returns same persisted identity']=function(){$a=m7_concurrent('pool');m0_assert($a[0]['id']===$a[1]['id']&&$a[0]['id']>0,'Pool race');};
 $tests['Concurrent completion has one winner']=function(){m7_assign();$a=m7_concurrent('complete');m0_assert(count(array_filter($a))===1,'Completion race');};
 $tests['Concurrent randomization returns same persisted variant']=function(){$a=m7_concurrent('random');m0_assert($a[0]['assigned_form_id']===$a[1]['assigned_form_id'],'RCT race');};
 $tests['Concurrent override and assignment preserve stable winner']=function(){global$wpdb;$a=m7_concurrent('override');$rows=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}eipsi_randomization_assignments WHERE randomization_id='m7-config'",ARRAY_A);m0_assert(count($rows)===1&&$rows[0]['assigned_form_id']==$a[1]['assigned_form_id'],'Override race');};


 $tests['Pool completion hook executes once after submitted wave']=function()use($form){global$wpdb;$wave=0;$assignment=0;try{m0_assert($wpdb->insert($wpdb->prefix.'survey_waves',array('study_id'=>994703,'wave_index'=>1,'name'=>'M7 wave','form_id'=>$form,'status'=>'active','created_at'=>current_time('mysql')))!==false,$wpdb->last_error);$wave=(int)$wpdb->insert_id;m0_assert($wpdb->insert($wpdb->prefix.'survey_assignments',array('participant_id'=>994707,'study_id'=>994703,'wave_id'=>$wave,'status'=>'submitted','assigned_at'=>current_time('mysql')))!==false,$wpdb->last_error);$assignment=(int)$wpdb->insert_id;m7_assign();$events=0;$listener=function($data)use(&$events){$events++;m0_assert((int)$data['participant_id']===994707&&$data['pool_name']==='M7 fixture','Completion context');};add_action('eipsi_pool_study_completed',$listener);try{eipsi_check_pool_completion_on_submit(array('survey_id'=>994703,'participant_id'=>994707,'form_id'=>(string)$form));eipsi_check_pool_completion_on_submit(array('survey_id'=>994703,'participant_id'=>994707,'form_id'=>(string)$form));m0_assert($events===1,'Hook duplicates');}finally{remove_action('eipsi_pool_study_completed',$listener);}}finally{if($assignment){$wpdb->delete($wpdb->prefix.'survey_assignments',array('id'=>$assignment));}if($wave){$wpdb->delete($wpdb->prefix.'survey_waves',array('id'=>$wave));}}};
 $tests['Form load another study rejected despite valid session']=function()use($other_form){global$wpdb;$wave=0;try{$wpdb->insert($wpdb->prefix.'survey_waves',array('study_id'=>994704,'wave_index'=>1,'name'=>'M7 foreign wave','form_id'=>$other_form,'status'=>'active','created_at'=>current_time('mysql')));$wave=(int)$wpdb->insert_id;m0_assert($wave>0,'Wave fixture');list($status)=m7_http('eipsi_load_form',array('form_id'=>$other_form),m7_session());m0_assert($status===403,'Cross-study form');}finally{if($wave){$wpdb->delete($wpdb->prefix.'survey_waves',array('id'=>$wave));}}};
 $tests['Form load malformed identifier rejected']=function(){list($status)=m7_http('eipsi_load_form',array('form_id'=>array(1)));m0_assert($status===404,'Malformed ID');};
 $tests['Random valid shortcode renders persisted variant']=function()use($page){update_post_meta($page,'_randomization_config_m7-config',m7_cfg());$_COOKIE['eipsi_user_fingerprint']='m7-shortcode';$html=eipsi_randomization_shortcode(array('template'=>$page,'config'=>'m7-config'));m0_assert(strpos($html,'eipsi')!==false&&is_string($html),'Shortcode render');};
 $tests['Seeded algorithm fixtures preserve pre-M7 outputs']=function(){require_once __DIR__.'/m7/baseline-m7_baseline_rct.php';require_once __DIR__.'/m7/baseline-m7_baseline_frontend.php';foreach(array('one','two','three','four','five')as$key){m0_assert(eipsi_calculate_rct_assignment(m7_cfg(),$key)===m7_baseline_rct(m7_cfg(),$key),'RCT baseline drift');m0_assert(eipsi_calculate_frontend_assignment(m7_cfg(),$key)===m7_baseline_frontend(m7_cfg(),$key),'Frontend baseline drift');}};
 $tests['All frozen public signatures preserved']=function(){ $c=json_decode(file_get_contents(__DIR__.'/m7/contracts.json'),true);foreach($c['functions']as$name=>$sig){if (!function_exists($name)) { $source=file_get_contents(EIPSI_FORMS_PLUGIN_DIR.$c['function_files'][$name]);m0_assert(strpos($source,$sig)!==false,'Missing deferred UI signature '.$name);continue; }$ref=new ReflectionFunction($name);preg_match_all('/\$([A-Za-z_][A-Za-z0-9_]*)/',$sig,$matches);m0_assert(array_map(function($p){return$p->getName();},$ref->getParameters())===$matches[1],'Signature '.$name);}foreach($c['classes']as$class=>$methods){if(!class_exists($class)){require_once EIPSI_FORMS_PLUGIN_DIR.$c['class_files'][$class];}foreach($methods as$name=>$sig){$ref=new ReflectionMethod($class,$name);m0_assert($ref->isPublic(),'Visibility');preg_match_all('/\$([A-Za-z_][A-Za-z0-9_]*)/',$sig,$matches);m0_assert(array_map(function($p){return$p->getName();},$ref->getParameters())===$matches[1],'Signature '.$class.'::'.$name);}} };
 foreach($tests as$name=>$test){try{m7_reset();$test();echo"PASS $name\n";}catch(Throwable$e){$failed++;echo"FAIL $name: {$e->getMessage()}\n";}}
}finally{
 if($created){foreach($extra_pools as$id){$wpdb->delete($wpdb->prefix.'eipsi_longitudinal_pools',array('id'=>$id));}foreach(array('eipsi_pool_analytics'=>'pool_id=994701','eipsi_pool_assignments'=>'pool_id=994701','eipsi_longitudinal_pools'=>'id=994701','eipsi_randomization_assignments'=>"randomization_id='m7-config'",'eipsi_randomization_configs'=>"randomization_id='m7-config'",'eipsi_manual_overrides'=>"randomization_id='m7-config'",'survey_magic_links'=>'participant_id IN (994707,994708)','survey_sessions'=>'participant_id IN (994707,994708)','survey_participants'=>'id IN (994707,994708)','survey_studies'=>'id IN (994703,994704)')as$t=>$where){$wpdb->query("DELETE FROM {$wpdb->prefix}{$t} WHERE $where");}}
 foreach($posts as$id){wp_delete_post($id,true);}$_COOKIE=array();
}
echo count($tests).' tests, '.$failed." failures\n";ob_end_flush();exit($failed?1:0);
