<?php
function m6_data($answers='{"answer":4}') { return array('form_id'=>generate_stable_form_id('long-form'),'form_name'=>'long-form','participant_id'=>'7','form_responses'=>$answers,'created_at'=>current_time('mysql')); }
function m6_result($db) { return EIPSI_Submission_Storage_Service::attempt(m6_data()); }
function m6_personal($db) { $id=p1c_request($db);$GLOBALS['p0_admin']=true;$result=EIPSI_Participant_Data_Request_Service::process_request($id,'approve');p0_assert($result['success'],'Personal export failed');return array($id,$result); }
// Storage: each case exercises a distinct persistence or verification condition.
$tests['M6 local owner INSERT confirmado']=function($db){$r=EIPSI_Local_Submission_Store::insert(m6_data());p0_assert($r['success']&&(int)$db->get_var("SELECT COUNT(*) FROM {$db->prefix}vas_form_results")===1,'No write');};
$tests['M6 DTO local destino e ID reales']=function($db){$r=m6_result($db);p0_assert($r['success']&&$r['destination']==='wordpress_db'&&$r['submission_id']===$r['insert_id'],'Wrong destination');};
$tests['M6 DTO local verificación soportada']=function($db){$r=m6_result($db);p0_assert($r['verified']&&$r['verification_supported']&&$r['verification_status']==='verified','Verification');};
$tests['M6 vacío persiste pero no verifica']=function($db){$r=EIPSI_Submission_Storage_Service::attempt(m6_data('{}'));p0_assert($r['success']&&!$r['verified']&&$r['verification_status']==='not_verified','Empty verification');};
$tests['M6 fallo local no confirma éxito']=function($db){$db->query("DROP TABLE {$db->prefix}vas_form_results");$r=m6_result($db);p0_assert(!$r['success']&&!$r['insert_confirmed']&&$r['error_code']==='DB_INSERT_FAILED','False success');};
$tests['M6 emergencia real identifica destino']=function($db){$r=eipsi_safety_emergency_save(m6_data(),'controlled failure');p0_assert($r['success']&&$r['destination']==='emergency_table_wp'&&$r['submission_id']===$r['emergency_id'],'Emergency destination');};
$tests['M6 emergencia no inventa verificación']=function($db){$r=eipsi_safety_emergency_save(m6_data(),'failure');p0_assert(!$r['verified']&&!$r['verification_supported']&&$r['verification_status']==='unsupported','Emergency verification');};
$tests['M6 emergencia conserva diagnóstico']=function($db){$r=eipsi_safety_emergency_save(m6_data(),'controlled failure');$row=$db->get_row("SELECT * FROM {$db->prefix}eipsi_emergency_submissions");p0_assert(strpos(wp_json_encode($row),'controlled failure')!==false&&count($GLOBALS['p0_mail'])===1,'Missing diagnosis');};
$tests['M6 emergencia fallida no confirma']=function($db){$db->query("DROP TABLE {$db->prefix}eipsi_emergency_submissions");$db->query("CREATE TABLE {$db->prefix}eipsi_emergency_submissions (id BIGINT PRIMARY KEY)");$r=eipsi_safety_emergency_save(m6_data(),'failure');p0_assert(!$r['success'],'Emergency false success');};
$tests['M6 no dual write con storage local']=function($db){$r=m6_result($db);p0_assert($r['success']&&(int)$db->get_var("SELECT COUNT(*) FROM {$db->prefix}eipsi_emergency_submissions")===0&&!$r['fallback_used'],'Duplicate');};
$tests['M6 ID inexistente no verifica']=function($db){p0_assert(!eipsi_safety_verify_submission(9988,'wordpress_db',m6_data()),'Nonexistent verified');};
$tests['M6 ID externo no se verifica en local']=function($db){$id=p1c_seed_response($db);$r=EIPSI_Storage_Result::normalize(array('success'=>true,'insert_id'=>$id,'storage'=>'external_db'));p0_assert(!$r['verified']&&!$r['verification_supported'],'External collision');};
$tests['M6 destino desconocido no confirma']=function($db){$r=EIPSI_Storage_Result::normalize(array('success'=>true,'insert_id'=>1,'storage'=>'unknown'));p0_assert(!$r['success'],'Unknown destination');};
// Privacy: exercise direct writer, JSON boundaries and each operation separately.
$tests['M6 filtro local directo aplica política']=function($db){p1c_config('long-form');$d=m6_data();$d['ip_address']='203.0.113.1';EIPSI_Local_Submission_Store::insert($d);p0_assert(!$db->get_var("SELECT ip_address FROM {$db->prefix}vas_form_results"),'Direct bypass');};
$tests['M6 filtro JSON metadata recursivo']=function($db){$c=p1c_config();$r=EIPSI_Privacy_Capture_Policy::eipsi_filter_capture_data(array('metadata'=>'{"ip_address":"secret","answer":4}'),$c);p0_assert(strpos(wp_json_encode($r),'secret')===false&&strpos(wp_json_encode($r),'answer')!==false,'Metadata');};
$tests['M6 filtro conserva texto libre']=function($db){$r=eipsi_filter_capture_data(array('answer'=>'mi IP es texto libre'),p1c_config());p0_assert($r['answer']==='mi IP es texto libre','Free text altered');};
$tests['M6 política idempotente']=function($db){$c=p1c_config();$d=array('ip_address'=>'secret','metadata'=>'{"answer":4}');$r=eipsi_filter_capture_data($d,$c);p0_assert(eipsi_filter_capture_data($r,$c)===$r,'Not idempotent');};
$tests['M6 captura activa retiene IP']=function($db){$c=get_privacy_defaults();$c['ip_address']=true;$r=eipsi_filter_capture_data(array('ip_address'=>'203.0.113.1'),$c);p0_assert($r['ip_address']==='203.0.113.1','Active lost');};
$tests['M6 anonymize retiene respuesta y participante']=function($db){p1c_seed_response($db);$r=EIPSI_Participant_Data_Cleanup::run(7,'anonymize');p0_assert($r['success']&&(int)$db->get_var("SELECT COUNT(*) FROM {$db->prefix}vas_form_results")===1&&(int)$db->get_var("SELECT COUNT(*) FROM {$db->prefix}survey_participants WHERE id=7")===1,'Anonymize semantics');};
$tests['M6 hard delete retiene respuesta sin identidad']=function($db){p1c_seed_response($db);$r=EIPSI_Participant_Data_Cleanup::run(7,'hard_delete');p0_assert($r['success']&&(int)$db->get_var("SELECT COUNT(*) FROM {$db->prefix}vas_form_results")===1&&!$db->get_var("SELECT id FROM {$db->prefix}survey_participants WHERE id=7"),'Hard semantics');};
$tests['M6 B2 elimina respuesta y conserva participante']=function($db){p1c_seed_response($db);$r=EIPSI_Participant_Data_Cleanup::run(7,'b2');p0_assert($r['success']&&(int)$db->get_var("SELECT COUNT(*) FROM {$db->prefix}vas_form_results")===0&&$db->get_var("SELECT id FROM {$db->prefix}survey_participants WHERE id=7"),'B2 semantics');};
$tests['M6 cleanup no afecta tercero']=function($db){EIPSI_Participant_Data_Cleanup::run(7,'hard_delete');p0_assert($db->get_var("SELECT email FROM {$db->prefix}survey_participants WHERE id=8")==='p8@example.invalid','Other erased');};
$tests['M6 cleanup falla sin participante']=function($db){$r=EIPSI_Participant_Data_Cleanup::run(555,'hard_delete');p0_assert(!$r['success']&&count($r['errors'])>0,'Missing accepted');};
foreach(array('external_db','historical_export_files','backups','server_logs','delivered_email','unreliably_linked_records','identifying_free_text') as $exclusion){$tests['M6 cobertura excluye '.$exclusion]=function($db)use($exclusion){$r=EIPSI_Privacy_Coverage_Report::for_operation('cleanup');p0_assert(!$r['complete']&&in_array($exclusion,$r['excluded'],true),'Coverage overclaim');};}
$tests['M6 personal delete es anonymize']=function($db){p1c_seed_response($db);p1_session();$r=EIPSI_Participant_Data_Request_Service::submit_request(7,'delete');$GLOBALS['p0_admin']=true;$done=EIPSI_Participant_Data_Request_Service::process_request($r['request_id'],'approve');p0_assert($done['success']&&(int)$db->get_var("SELECT COUNT(*) FROM {$db->prefix}vas_form_results")===1,'Personal delete');};
// Requests: authorization, private artifact and optimistic claim.
$tests['M6 request sin sesión denegado']=function($db){p0_assert(!EIPSI_Participant_Data_Request_Service::submit_request(7,'export')['success'],'Anonymous');};
$tests['M6 request sesión A no solicita B']=function($db){p1_session();p0_assert(!EIPSI_Participant_Data_Request_Service::submit_request(8,'export')['success'],'Foreign');};
$tests['M6 request tipo fuera allowlist denegado']=function($db){p1_session();p0_assert(!EIPSI_Participant_Data_Request_Service::submit_request(7,'arbitrary')['success'],'Type');};
$tests['M6 aprobar exige capability']=function($db){$id=p1c_request($db);p0_assert(!EIPSI_Participant_Data_Request_Service::process_request($id,'approve')['success'],'Capability');};
$tests['M6 personal archivo privado 0600']=function($db){list($id,$r)=m6_personal($db);$download=EIPSI_Participant_Data_Request_Service::get_download($id,'valid:eipsi_data_download');p0_assert($download['success']&&(fileperms($download['file_path'])&0777)===0600&&strpos($download['file_path'],get_temp_dir())===0,'Private permissions');};
$tests['M6 personal nonce incorrecto denegado']=function($db){list($id,$r)=m6_personal($db);p0_assert(!EIPSI_Participant_Data_Request_Service::get_download($id,'bad')['success'],'Nonce');};
$tests['M6 segunda aprobación no genera segundo archivo']=function($db){list($id,$r)=m6_personal($db);$count=count(glob(get_temp_dir().'/*'));p0_assert(!EIPSI_Participant_Data_Request_Service::process_request($id,'approve')['success']&&count(glob(get_temp_dir().'/*'))===$count,'Double approval');};
// Exports: datasets, formats, file failure and download boundary.
$tests['M6 personal dataset usa columnas explícitas']=function($db){p1c_seed_response($db);$db->observed_queries=array();$r=EIPSI_Personal_Export_Query_Service::dataset((object)array('participant_id'=>7,'survey_id'=>3));foreach($db->observed_queries as$q){p0_assert(strpos(strtoupper($q),'SELECT *')===false,'Wildcard');}p0_assert(isset($r['participant_info']['email']),'Data missing');};
$tests['M6 personal elimina secretos JSON anidados']=function($db){p1c_seed_response($db);$r=EIPSI_Personal_Export_Query_Service::dataset((object)array('participant_id'=>7,'survey_id'=>3));p0_assert(strpos(wp_json_encode($r),'password_hash')===false&&strpos(wp_json_encode($r),'session_token')===false,'Secrets');};
$tests['M6 personal lectura fallida lanza error']=function($db){$db->query("DROP TABLE {$db->prefix}survey_email_log");$failed=false;try{EIPSI_Personal_Export_Query_Service::dataset((object)array('participant_id'=>7,'survey_id'=>3));}catch(RuntimeException$e){$failed=true;}p0_assert($failed,'Silent read');};
$tests['M6 longitudinal dataset local']=function($db){p1c_seed_response($db);$r=(new EIPSI_Export_Query_Service())->export_longitudinal_data(3);p0_assert(count($r)>0&&!$db->last_error,'Long dataset');};
$tests['M6 wide dataset incluye waves']=function($db){p1c_seed_response($db);$r=(new EIPSI_Export_Query_Service())->fetch_participants_data(3);p0_assert(count($r['rows'])===2&&!$db->last_error,'Wide dataset');};
$tests['M6 raw dataset declara fuente local']=function($db){p1c_seed_response($db);$r=EIPSI_Export_Query_Service::raw_responses();p0_assert($r['source']==='wordpress_db'&&count($r['rows'])===1,'Raw source');};
$tests['M6 CSV genera archivo no vacío']=function($db){p1c_seed_response($db);$s=new EIPSI_Export_Service();$f=$s->export_to_csv($s->export_longitudinal_data(3),3);$GLOBALS['p1c_exports'][]=EIPSI_FORMS_PLUGIN_DIR.'exports/'.$f;p0_assert(filesize(end($GLOBALS['p1c_exports']))>0,'CSV');};
$tests['M6 XLSX archivo ZIP válido']=function($db){p1c_seed_response($db);$s=new EIPSI_Export_Service();$f=$s->export_to_excel($s->export_longitudinal_data(3),3);$p=EIPSI_FORMS_PLUGIN_DIR.'exports/'.$f;$GLOBALS['p1c_exports'][]=$p;p0_assert(substr(file_get_contents($p),0,2)==='PK','XLSX');};
$tests['M6 wide XLSX genera archivo']=function($db){p1c_seed_response($db);$f=(new EIPSI_Export_Service())->export_participants_wide_excel(3);$p=EIPSI_FORMS_PLUGIN_DIR.'exports/'.$f;$GLOBALS['p1c_exports'][]=$p;p0_assert(filesize($p)>0,'Wide XLSX');};
$tests['M6 colisión preserva archivo anterior']=function($db){$a=EIPSI_Export_File_Service::reserve_filename('m6-collision.csv');$p=EIPSI_FORMS_PLUGIN_DIR.'exports/'.$a;file_put_contents($p,'historical');$b=EIPSI_Export_File_Service::reserve_filename('m6-collision.csv');$GLOBALS['p1c_exports'][]=$p;$GLOBALS['p1c_exports'][]=EIPSI_FORMS_PLUGIN_DIR.'exports/'.$b;p0_assert($a!==$b&&file_get_contents($p)==='historical','Overwritten');};
$tests['M6 descarga admin sin capability denegada']=function($db){p0_assert(!EIPSI_Download_Authorization_Service::get_admin_download('m6.csv','valid:eipsi_export_download')['success'],'Capability');};
$tests['M6 descarga admin nonce inválido denegada']=function($db){$GLOBALS['p0_admin']=true;p0_assert(!EIPSI_Download_Authorization_Service::get_admin_download('m6.csv','bad')['success'],'Nonce');};
$tests['M6 descarga admin traversal denegado']=function($db){$GLOBALS['p0_admin']=true;p0_assert(!EIPSI_Download_Authorization_Service::get_admin_download('../secret.csv','valid:eipsi_export_download')['success'],'Traversal');};
$tests['M6 descarga admin autorizado conserva filename']=function($db){$GLOBALS['p0_admin']=true;$f=EIPSI_Export_File_Service::reserve_filename('m6-authorized.csv');$p=EIPSI_FORMS_PLUGIN_DIR.'exports/'.$f;$GLOBALS['p1c_exports'][]=$p;file_put_contents($p,'answer');$r=EIPSI_Download_Authorization_Service::get_admin_download($f,'valid:eipsi_export_download');p0_assert($r['success']&&$r['filename']===$f&&$r['file_path']===realpath($p),'Download');};
$tests['M6 access query fallo no simula cero filas']=function($db){$db->query("DROP TABLE {$db->prefix}survey_participant_access_log");$failed=false;try{EIPSI_Access_Log_Export_Query_Service::load(array());}catch(RuntimeException$e){$failed=true;}p0_assert($failed,'Access read');};
$tests['M6 protección HTTP presente']=function($db){p0_assert(strpos(file_get_contents(EIPSI_FORMS_PLUGIN_DIR.'exports/.htaccess'),'Require all denied')!==false,'Guard');};
function m6_external($db,$callback){
 $external=new EIPSI_External_Database();$external->save_credentials('eipsi-m0-db','m0','m0-isolated','m6_external');
 $connection=new mysqli('eipsi-m0-db','m0','m0-isolated','m6_external');
 try{p0_assert($connection->query(EIPSI_Database_Schema_Manager::get_table_sql('vas_form_results'))!==false,'External fixture schema');$callback($external,$connection);}finally{$result=$connection->query('SHOW TABLES');while($row=$result->fetch_row()){if(strpos($row[0],$db->prefix)===0){$connection->query('DROP TABLE `'.$row[0].'`');}}$connection->close();}
}
$tests['M6 externo real confirma INSERT sin dual write']=function($db){m6_external($db,function($e,$c)use($db){$r=m6_result($db);p0_assert($r['success']&&$r['destination']==='external_db'&&!$r['verified'],'External: '.wp_json_encode($r));p0_assert((int)$db->get_var("SELECT COUNT(*) FROM {$db->prefix}vas_form_results")===0&&(int)$c->query("SELECT COUNT(*) FROM {$db->prefix}vas_form_results")->fetch_row()[0]===1,'Dual write');});};
$tests['M6 writer externo directo filtra IP']=function($db){m6_external($db,function($e,$c)use($db){p1c_config('long-form');$d=m6_data();$d['ip_address']='secret';$r=$e->insert_form_submission($d);p0_assert($r['success'],'External insert');$row=$c->query("SELECT ip_address FROM {$db->prefix}vas_form_results")->fetch_row();p0_assert(!$row[0],'External policy bypass');});};
$tests['M6 falla externa cae a local informa fallback']=function($db){$e=new EIPSI_External_Database();$e->save_credentials('eipsi-m0-db','m0','intentionally-wrong','m6_external');$r=m6_result($db);p0_assert($r['success']&&$r['destination']==='wordpress_db'&&$r['fallback_used']&&isset($r['primary_error_code']),'Fallback');};
$tests['M6 falla externo y local llega a emergencia']=function($db){$e=new EIPSI_External_Database();$e->save_credentials('eipsi-m0-db','m0','intentionally-wrong','m6_external');$db->query("DROP TABLE {$db->prefix}vas_form_results");$r=eipsi_safety_save_with_retry(m6_data(),1);p0_assert($r['success']&&$r['destination']==='emergency_table_wp','Fallback emergency');};
foreach(array('user_agent_full'=>'user_agent','fingerprint_enabled'=>'user_fingerprint','device_type'=>'device','browser'=>'browser','os'=>'os','movement_tracking'=>'mouse_movements','mood_tracking'=>'mood_tracking')as$toggle=>$field){$tests['M6 CapturePolicy '.$toggle.' off']=function($db)use($toggle,$field){$c=get_privacy_defaults();$c[$toggle]=false;$r=eipsi_filter_capture_data(array($field=>'secret','answer'=>4),$c);p0_assert(!isset($r[$field])&&$r['answer']===4,'Toggle bypass');};}
$tests['M6 partial writer usa CapturePolicy']=function($db){p1c_config('long-form');$r=EIPSI_Partial_Responses::save('long-form','7','session',1,array('ip_address'=>'secret','answer'=>4));$row=$db->get_row("SELECT * FROM {$db->prefix}eipsi_partial_responses");p0_assert($r['success']&&strpos(wp_json_encode($row),'secret')===false,'Partial bypass');};
$tests['M6 event writer usa CapturePolicy']=function($db){p1c_config('long-form');$r=EIPSI_Storage_Event_Store::insert(array('form_id'=>generate_stable_form_id('long-form'),'session_id'=>'m6','event_type'=>'page_change','page_number'=>1,'metadata'=>'{"ip_address":"secret"}','user_agent'=>'secret','created_at'=>current_time('mysql')));$row=$db->get_row("SELECT * FROM {$db->prefix}vas_form_events");p0_assert($r['success']&&strpos(wp_json_encode($row),'secret')===false,'Event bypass');};
$tests['M6 emergency filtra raw POST real']=function($db){p1c_config('long-form');$_POST=array('ip_address'=>'secret','answer'=>4);$r=eipsi_safety_emergency_save(m6_data(),'controlled');$row=$db->get_row("SELECT * FROM {$db->prefix}eipsi_emergency_submissions");p0_assert($r['success']&&strpos(wp_json_encode($row),'secret')===false&&strpos(wp_json_encode($row),'answer')!==false,'Raw POST');};
$tests['M6 cleanup rollback real ante fallo audit']=function($db){$db->query("ALTER TABLE {$db->prefix}survey_audit_log ADD required_m6 varchar(20) NOT NULL");$db->query("SET SESSION sql_mode='STRICT_ALL_TABLES'");$r=EIPSI_Participant_Data_Cleanup::run(7,'hard_delete');p0_assert(!$r['success']&&$r['rolled_back']&&$db->get_var("SELECT email FROM {$db->prefix}survey_participants WHERE id=7")==='p7@example.invalid','Rollback');};
$tests['M6 raw externo declara fuente sin unir IDs locales']=function($db){m6_external($db,function($e,$c)use($db){$d=m6_data();$d['status']='submitted';$r=$e->insert_form_submission($d);p0_assert($r['success'],'External fixture INSERT');p1c_seed_response($db);$raw=EIPSI_Export_Query_Service::raw_responses();p0_assert($raw['source']==='external_db'&&count($raw['rows'])===1,'External source');});};
$tests['M6 pool context conserva contrato separado']=function($db){$GLOBALS['p0_admin']=true;require_once EIPSI_FORMS_PLUGIN_DIR.'admin/export.php';p1c_seed_response($db);$r=EIPSI_Export_Query_Service::eipsi_export_responses_with_pool_context(generate_stable_form_id('long-form'),3);p0_assert(count($r)===1&&!$db->last_error,'Pool context');};
$tests['M6 access dataset conserva filtro de participante']=function($db){require_once EIPSI_FORMS_PLUGIN_DIR.'admin/services/class-participant-access-log-service.php';EIPSI_Participant_Access_Log_Service::log(7,3,'login',array());EIPSI_Participant_Access_Log_Service::log(8,3,'login',array());$r=EIPSI_Access_Log_Export_Query_Service::load(array('participant_id'=>7));p0_assert(count($r)===1&&(int)$r[0]->participant_id===7,'Access filter');};
$tests['M6 generación rechaza directorio destino']=function($db){$p=EIPSI_FORMS_PLUGIN_DIR.'exports/m6-dir.csv';mkdir($p);try{$failed=false;try{EIPSI_Export_File_Service::reserve_filename('m6-dir.csv');}catch(RuntimeException$e){$failed=true;}p0_assert($failed,'Directory accepted');}finally{rmdir($p);}};
$tests['M6 LONG actions siguen deuda sin alias incorrecto']=function($db){p0_assert(empty($GLOBALS['p0_hooks']['wp_ajax_eipsi_export_participants_long_excel'])&&empty($GLOBALS['p0_hooks']['wp_ajax_eipsi_export_participants_long_csv']),'Invented alias');};
$tests['M6 filenames concurrentes reservan archivos distintos']=function($db){$dir='/tmp/eipsi-m6-files-'.bin2hex(random_bytes(6));mkdir($dir);$workers=array();$pipes=array();try{foreach(array(0,1)as$i){$workers[$i]=proc_open(array(PHP_BINARY,__DIR__.'/filename-worker.php',$dir,(string)$i),array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('file',$dir.'/log'.$i,'a')),$pipes[$i]);p0_assert(is_resource($workers[$i]),'Worker');fclose($pipes[$i][0]);}$deadline=microtime(true)+20;while(!file_exists($dir.'/ready0')||!file_exists($dir.'/ready1')){p0_assert(microtime(true)<$deadline,'Barrier');usleep(10000);}touch($dir.'/start');while(!file_exists($dir.'/result0')||!file_exists($dir.'/result1')){p0_assert(microtime(true)<$deadline,'Results');usleep(10000);}$r=array();foreach(array(0,1)as$i){$r[$i]=json_decode(file_get_contents($dir.'/result'.$i),true);p0_assert(empty($r[$i]['error']),$r[$i]['error']??'Error');$GLOBALS['p1c_exports'][]=EIPSI_FORMS_PLUGIN_DIR.'exports/'.$r[$i]['filename'];p0_assert(file_get_contents(end($GLOBALS['p1c_exports']))==='slot'.$i,'Overwrite');}p0_assert($r[0]['filename']!==$r[1]['filename'],'Collision');}finally{foreach($workers as$i=>$w){$state=proc_get_status($w);if($state['running']){proc_terminate($w);}fclose($pipes[$i][1]);proc_close($w);}foreach(glob($dir.'/*')as$p){unlink($p);}rmdir($dir);}};
$tests['M6 pool roster dos datasets sin fusionar']=function($db){$a=EIPSI_Export_Query_Service::pool_roster_dashboard(3);$b=EIPSI_Export_Query_Service::pool_roster_hub(3);p0_assert(isset($a['rows'],$b['rows'])&&!$db->last_error,'Roster contracts');};
$tests['M6 facades conservan todas las firmas públicas congeladas']=function($db){require_once EIPSI_FORMS_PLUGIN_DIR.'admin/privacy-config.php';require_once EIPSI_FORMS_PLUGIN_DIR.'admin/services/class-device-data-service.php';require_once EIPSI_FORMS_PLUGIN_DIR.'admin/export.php';require_once EIPSI_FORMS_PLUGIN_DIR.'admin/services/class-access-log-export-service.php';$c=json_decode(file_get_contents(__DIR__.'/contracts.json'),true);$check=function($ref,$expected){p0_assert(array_map(function($p){return$p->getName();},$ref->getParameters())===$expected['parameters'],'Parameters: '.$ref->getName());p0_assert($ref->getNumberOfParameters()-$ref->getNumberOfRequiredParameters()===$expected['optional'],'Defaults: '.$ref->getName());};foreach($c['functions']as$name=>$sig){$check(new ReflectionFunction($name),$sig);}foreach($c['classes']as$class=>$methods){foreach($methods as$name=>$sig){$ref=new ReflectionMethod($class,$name);$check($ref,$sig);p0_assert($ref->isPublic()&&$ref->isStatic()===$sig['static'],'Visibility: '.$class.'::'.$name);}}};
$tests['M6 XLSX canónico conserva bytes originales']=function($db){$c=json_decode(file_get_contents(__DIR__.'/baseline-hashes.json'),true);p0_assert(hash_file('sha256',EIPSI_FORMS_PLUGIN_DIR.'lib/SimpleXLSXGen.php')===$c['files']['lib/SimpleXLSXGen.php'],'Library changed');};
foreach(array('IV termina en dos puntos'=>'abcdefghijklmno:','IV contiene delimitador'=>'abc::fghijklmnop')as$label=>$iv){$tests['M6 credenciales externas '.$label]=function($db)use($iv){$encrypted=openssl_encrypt('m0-isolated','aes-256-cbc',wp_salt('auth'),0,$iv);$GLOBALS['p0_options']['eipsi_external_db_enabled']=true;$GLOBALS['p0_options']['eipsi_external_db_host']='eipsi-m0-db';$GLOBALS['p0_options']['eipsi_external_db_user']='m0';$GLOBALS['p0_options']['eipsi_external_db_name']='m6_external';$GLOBALS['p0_options']['eipsi_external_db_password']=base64_encode($iv.'::'.$encrypted);$c=(new EIPSI_External_Database())->get_credentials();p0_assert($c['password']==='m0-isolated','Binary IV parser');};}
$tests['M6 handler wide CSV error de destino devuelve JSON controlado']=function($db){require_once EIPSI_FORMS_PLUGIN_DIR.'admin/ajax-export-handlers.php';$GLOBALS['p0_admin']=true;$_POST=array('nonce'=>'valid:eipsi_admin_nonce','study_id'=>3);$paths=array();foreach(array(-1,0,1)as$offset){$p=EIPSI_FORMS_PLUGIN_DIR.'exports/participantes-wide-3-'.date('Y-m-d_H-i-s',time()+$offset).'.csv';mkdir($p);$paths[]=$p;}try{$caught=false;try{eipsi_export_participants_wide_csv_handler();}catch(P0JsonResponse$e){$caught=true;p0_assert(!$e->success&&$e->status===500,'Wrong error envelope');}p0_assert($caught,'Missing JSON error');}finally{foreach($paths as$p){rmdir($p);}}};
$tests['M6 externo fallback y emergencia fallidos nunca confirman éxito']=function($db){(new EIPSI_External_Database())->save_credentials('eipsi-m0-db','m0','intentionally-wrong','m6_external');$db->query("DROP TABLE {$db->prefix}vas_form_results");$db->query("DROP TABLE {$db->prefix}eipsi_emergency_submissions");$db->query("CREATE TABLE {$db->prefix}eipsi_emergency_submissions (id BIGINT PRIMARY KEY)");$r=eipsi_safety_save_with_retry(m6_data(),1);p0_assert(!$r['success']&&!$r['insert_confirmed']&&$r['submission_id']===null,'All destinations failed but success returned');};
