<?php
function s4_partial($participant='999407',$responses=array('clinical_answer'=>'S4 sensitive sentinel')){return EIPSI_Partial_Responses::save('s4-partial-fixture',$participant,'sess-1700000000000-shared',1,$responses);}
function s4_partial_row(){global $wpdb;return $wpdb->get_row("SELECT * FROM {$wpdb->prefix}eipsi_partial_responses WHERE form_id='s4-partial-fixture'",ARRAY_A);}
function s4_partial_request($action,$participant='999407',$session=null){return s4_request($action,array('form_id'=>'s4-partial-fixture','participant_id'=>$participant,'session_id'=>'sess-1700000000000-shared','page_index'=>1,'responses'=>array('clinical_answer'=>'Attacker replacement')),false,$session,'eipsi_save_partial');}
$tests['Regression: partial foreign session cannot read victim answers']=function(){global $wpdb;$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>'s4-partial-fixture'));m0_assert(s4_partial()['success'],'Partial fixture');$r=s4_partial_request('eipsi_load_partial_response','999407',s4_session(999408));$j=s4_json($r);m0_assert(empty($j['success'])||empty($j['data']['found']),'Foreign session read victim responses: '.wp_json_encode($j));};
$tests['Regression: partial foreign session cannot overwrite victim answers']=function(){global $wpdb;$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>'s4-partial-fixture'));s4_partial();$before=s4_partial_row();$r=s4_partial_request('eipsi_save_partial_response','999407',s4_session(999408));m0_assert(!s4_json($r)['success']&&s4_partial_row()===$before,'Foreign session overwrote victim partial');};
$tests['Regression: partial foreign session cannot discard victim answers']=function(){global $wpdb;$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>'s4-partial-fixture'));s4_partial();$before=s4_partial_row();$r=s4_partial_request('eipsi_discard_partial_response','999407',s4_session(999408));m0_assert(!s4_json($r)['success']&&s4_partial_row()===$before,'Foreign session deleted victim partial');};
$tests['Regression: anonymous numeric identity cannot create participant partial']=function(){global $wpdb;$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>'s4-partial-fixture'));$r=s4_partial_request('eipsi_save_partial_response','999407');m0_assert(!s4_json($r)['success']&&!s4_partial_row(),'Public nonce impersonated numeric participant');};
$tests['Invariant S4-03 RCT attacker cannot delete a canonical assignment']=function(){global $wpdb;$config='s4-current-rct-fixture';$fp='s4-foreign-browser-fingerprint';m0_assert(!$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}eipsi_randomization_assignments WHERE randomization_id=%s",$config)),'RCT collision');try{m0_assert(EIPSI_Randomization_Assignment_Service::eipsi_create_assignment($config,$fp,$GLOBALS['posts'][0]),'RCT owner fixture');$before=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}eipsi_randomization_assignments ORDER BY id",ARRAY_A);$r=s4_request('eipsi_close_randomization_session',array('randomization_id'=>$config,'user_fingerprint'=>$fp,'nonce'=>''),false);$j=s4_json($r); $exists=(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}eipsi_randomization_assignments WHERE randomization_id=%s AND user_fingerprint=%s",$config,$fp));$GLOBALS['s4_rct_evidence']=array('severity'=>'P1','status'=>'CLOSED','public_without_nonce'=>true,'success'=>$j['success'],'assignment_exists_after'=>$exists);m0_assert(wp_remote_retrieve_response_code($r)===403&&!$j['success']&&$exists,'S4-03: public request deleted canonical RCT assignment');m0_assert($before===$wpdb->get_results("SELECT * FROM {$wpdb->prefix}eipsi_randomization_assignments ORDER BY id",ARRAY_A),'Other RCT assignments changed');}finally{$wpdb->delete($wpdb->prefix.'eipsi_randomization_assignments',array('randomization_id'=>$config));}};

$tests['Regression: future wave partial cannot bypass temporal gate']=function(){global $wpdb;$form=$GLOBALS['posts'][0];$wpdb->update($wpdb->prefix.'survey_assignments',array('available_at'=>date('Y-m-d H:i:s',current_time('timestamp')+86400)),array('id'=>999432));$r=s4_request('eipsi_save_partial_response',array('form_id'=>(string)$form,'participant_id'=>'999407','session_id'=>'s4-future-partial','wave_id'=>999422,'responses'=>array('answer'=>'future')),false,s4_session(),'eipsi_save_partial');m0_assert(!s4_json($r)['success']&&!$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}eipsi_partial_responses WHERE form_id=%s AND session_id='s4-future-partial'",(string)$form)),'Future wave captured partial');$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>(string)$form,'session_id'=>'s4-future-partial'));};
$tests['Regression: refresh SELECT failure reports persisted partial recalc']=function(){global $wpdb;$fired=false;$filter=function($sql)use(&$fired){if(!$fired&&preg_match('/^\s*SELECT a\.\*, w\.follow_up_reminders_enabled.*WHERE a\.wave_id/is',$sql)){$fired=true;return 'SELECT eipsi_s4_missing_refresh_column';}return $sql;};$previous=$wpdb->suppress_errors(true);add_filter('query',$filter);try{$r=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_study(999403,1);}finally{remove_filter('query',$filter);$wpdb->suppress_errors($previous);}m0_assert($fired&&is_wp_error($r)&&$r->get_error_code()==='refresh_failed'&&$r->get_error_data()['updated']===1,'Refresh query failure presented as successful recalc: '.wp_json_encode($r));};
$tests['Own numeric partial HTTP save load discard keeps contract']=function(){global $wpdb;$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>'s4-partial-fixture'));$session=s4_session();m0_assert(s4_json(s4_partial_request('eipsi_save_partial_response','999407',$session))['success'],'Own save');$load=s4_json(s4_partial_request('eipsi_load_partial_response','999407',$session));m0_assert($load['success']&&$load['data']['found']&&$load['data']['partial']['participant_id']==='999407','Own load');m0_assert(s4_json(s4_partial_request('eipsi_discard_partial_response','999407',$session))['success']&&!s4_partial_row(),'Own discard');};
$tests['Anonymous browser partial preserves save load discard contract']=function(){global $wpdb;$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>'s4-partial-fixture'));m0_assert(s4_json(s4_partial_request('eipsi_save_partial_response','p-s4-browser'))['success'],'Browser save');$load=s4_json(s4_partial_request('eipsi_load_partial_response','p-s4-browser'));m0_assert($load['success']&&$load['data']['found'],'Browser load');m0_assert(s4_json(s4_partial_request('eipsi_discard_partial_response','p-s4-browser'))['success']&&!s4_partial_row(),'Browser discard');};
$tests['Partial guessed foreign wave rejected before writer']=function(){global $wpdb;$form=$GLOBALS['posts'][0];$r=s4_request('eipsi_save_partial_response',array('form_id'=>(string)$form,'participant_id'=>'999407','session_id'=>'s4-future-partial','wave_id'=>999424,'responses'=>array('answer'=>'spoof')),false,s4_session(),'eipsi_save_partial');m0_assert(!s4_json($r)['success'],'Foreign wave');};
$tests['Inactive or declined session cannot access partials']=function(){global $wpdb;$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>'s4-partial-fixture'));s4_partial();foreach(array(array('is_active'=>0),array('is_active'=>1,'consent_decision'=>'declined'))as$state){$wpdb->update($wpdb->prefix.'survey_participants',array('is_active'=>1,'consent_decision'=>'accepted'),array('id'=>999407));$session=s4_session();$wpdb->update($wpdb->prefix.'survey_participants',$state,array('id'=>999407));$r=s4_partial_request('eipsi_load_partial_response','999407',$session);m0_assert(!s4_json($r)['success'],'Ineligible partial access');}};
$tests['Expired session cannot extend or read partials']=function(){global $wpdb;$session=s4_session();$wpdb->update($wpdb->prefix.'survey_sessions',array('expires_at'=>date('Y-m-d H:i:s',time()-60)),array('token'=>hash('sha256',$session['token'])));m0_assert(!s4_json(s4_request('eipsi_extend_session',array('ttl_hours'=>720),false,$session,'eipsi_participant_auth'))['success'],'Expired extension');m0_assert(!s4_json(s4_partial_request('eipsi_load_partial_response','999407',$session))['success'],'Expired partial read');};
$tests['Session extension ignores spoof identity and cannot extend another session']=function(){global $wpdb;$victim=s4_session(999408);$before=$wpdb->get_var($wpdb->prepare("SELECT expires_at FROM {$wpdb->prefix}survey_sessions WHERE token=%s",hash('sha256',$victim['token'])));$own=s4_session();$r=s4_request('eipsi_extend_session',array('participant_id'=>999408,'survey_id'=>999404,'ttl_hours'=>720),false,$own,'eipsi_participant_auth');m0_assert(s4_json($r)['success'],'Own extension');m0_assert($wpdb->get_var($wpdb->prepare("SELECT expires_at FROM {$wpdb->prefix}survey_sessions WHERE token=%s",hash('sha256',$victim['token'])))===$before,'Victim extended');};
$tests['Participant info with foreign client IDs returns only canonical own identity']=function(){$r=s4_request('eipsi_participant_info',array('participant_id'=>999408,'study_id'=>999404),false,s4_session(),'eipsi_participant_auth');$j=s4_json($r);m0_assert($j['success']&&(int)$j['data']['participant_id']===999407&&(int)$j['data']['survey_id']===999403&&strpos(wp_json_encode($j),'s4-999408')===false,'Info IDOR');};
$tests['Refresh locked reread SELECT failure returns error after dates persist']=function(){global $wpdb;$fired=false;$filter=function($sql)use(&$fired){if(!$fired&&preg_match('/^\s*SELECT a\.\*, w\.follow_up_reminders_enabled.*WHERE a\.id=/is',$sql)){$fired=true;return 'SELECT eipsi_s4_missing_refresh_column';}return $sql;};$previous=$wpdb->suppress_errors(true);add_filter('query',$filter);try{$r=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_study(999403,1);}finally{remove_filter('query',$filter);$wpdb->suppress_errors($previous);}m0_assert($fired&&is_wp_error($r)&&$r->get_error_data()['updated']===1,'Reread failure swallowed');};
$tests['Actual resend reminder route remains valid without merging modal route']=function(){$r=s4_request('eipsi_resend_participant_email',array('participant_id'=>999407,'study_id'=>999403,'email_type'=>'reminder','wave_id'=>''));$j=s4_json($r);m0_assert($j['success'],'Visible reminder request: '.wp_json_encode($j));};
$tests['Actual resend route invalid nonce cannot deliver']=function(){$r=s4_request('eipsi_resend_participant_email',array('participant_id'=>999407,'study_id'=>999403,'email_type'=>'reminder','nonce'=>'invalid'));$j=s4_json($r);m0_assert(!$j['success'],'Resend CSRF');};
$tests['Legacy CSV GET stays unreachable in current WP menu']=function(){$r=m0_http('/wp-admin/admin.php?page=eipsi-results&action=export_participants_csv&study_id=999403',null,true);m0_assert(wp_remote_retrieve_response_code($r)===403&&strpos(wp_remote_retrieve_body($r),'s4-999407')===false,'CSV now reachable: reclassify CSRF');};
function s4_assignment(){global $wpdb;return $wpdb->get_row("SELECT * FROM {$wpdb->prefix}survey_assignments WHERE id=999432",ARRAY_A);}
require __DIR__.'/concurrency.php';
$tests['New race recalc apply versus real deadline writer stays coherent']=function(){global $wpdb;$r=s4_concurrent(array('apply','deadline'));foreach($r as$row){m0_assert(!isset($row['result']['error']),'Concurrent command failed');}$a=s4_assignment();$window=(int)$wpdb->get_var("SELECT window_minutes FROM {$wpdb->prefix}survey_waves WHERE id=999422");m0_assert($window===60&&$a['status']==='pending'&&$a['due_at']===date('Y-m-d H:i:s',strtotime($a['available_at'])+3600),'Mixed concurrent dates');};
$tests['Repeated apply preserves canonical dates and explicit per-command audit']=function(){global $wpdb;$first=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_study(999403,1);$a=s4_assignment();$second=EIPSI_Longitudinal_T1_Recalculation_Service::recalculate_study(999403,1);$b=s4_assignment();m0_assert(!is_wp_error($first)&&!is_wp_error($second)&&$a['available_at']===$b['available_at']&&$a['due_at']===$b['due_at'],'Repeated dates drift');m0_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_audit_log WHERE survey_id=999403")===4,'Audit loss');};
$tests['Visible reminder JS request reaches real HTTP owner']=function(){$f=json_decode(file_get_contents(__DIR__.'/consumer-request.json'),true);m0_assert(is_array($f),'Run S4 consumer JS first');$j=s4_json(s4_request($f['action'],$f['data'],true,null,$f['nonce_action']));m0_assert($j['success'],'Actual JS payload failed: '.wp_json_encode($j));};
$tests['Regression: logout owner must not confirm failed server revocation']=function(){global $wpdb;$session=s4_session();$_COOKIE[$session['cookie_name']]=$session['token'];$filter=function($sql){return preg_match('/^\s*DELETE FROM.*survey_sessions/i',$sql)?'SELECT eipsi_s4_logout_missing_column':$sql;};$previous=$wpdb->suppress_errors(true);add_filter('query',$filter);try{$r=EIPSI_Auth_Service::destroy_session();}finally{remove_filter('query',$filter);$wpdb->suppress_errors($previous);}m0_assert($r===false&&isset($_COOKIE[$session['cookie_name']]),'Failed DELETE was acknowledged and removed retry cookie');};
$tests['Regression: logout HTTP SQL failure reports error instead of false success']=function(){$session=s4_session();update_option('eipsi_s4_logout_sql_failure',true,false);try{$j=s4_json(s4_request('eipsi_participant_logout',array(),false,$session,'eipsi_participant_auth'));m0_assert(!$j['success'],'Logout falsely confirmed server revocation');}finally{delete_option('eipsi_s4_logout_sql_failure');}};
$tests['Valid logout HTTP revokes captured token and remains idempotent']=function(){$session=s4_session();m0_assert(s4_json(s4_request('eipsi_participant_logout',array(),false,$session,'eipsi_participant_auth'))['success'],'Own logout');m0_assert(!s4_json(s4_request('eipsi_participant_info',array(),false,$session,'eipsi_participant_auth'))['success'],'Old token reused after success');m0_assert(s4_json(s4_request('eipsi_participant_logout',array(),false,$session,'eipsi_participant_auth'))['success'],'Repeated logout');};
$tests['Real partial browser payload resolves own wave without client wave context']=function(){global $wpdb;$form=(string)$GLOBALS['posts'][0];$session=s4_session();$data=array('form_id'=>$form,'participant_id'=>'999407','session_id'=>'s4-future-partial','page_index'=>1,'responses'=>array('answer'=>'current browser fields'));try{m0_assert(s4_json(s4_request('eipsi_save_partial_response',$data,false,$session,'eipsi_save_partial'))['success'],'Browser payload without wave_id broke valid T2');$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>$form,'session_id'=>'s4-future-partial'));$wpdb->update($wpdb->prefix.'survey_assignments',array('available_at'=>date('Y-m-d H:i:s',current_time('timestamp')+86400)),array('id'=>999432));m0_assert(!s4_json(s4_request('eipsi_save_partial_response',$data,false,$session,'eipsi_save_partial'))['success']&&!$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}eipsi_partial_responses WHERE form_id=%s AND session_id='s4-future-partial'",$form)),'Context-free browser payload bypassed future wave');}finally{$wpdb->delete($wpdb->prefix.'eipsi_partial_responses',array('form_id'=>$form,'session_id'=>'s4-future-partial'));}};
