/* Execute the current visible reminder binding, rather than a mirrored payload. */
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const nodes=new Map(),requests=[],events=new Map();let total=0;
function $(key){if(typeof key==='function')return; if(key&&key.key)key=key.key; if(!nodes.has(key))nodes.set(key,{key,length:1,values:{},on(type,selector,fn){if(typeof selector==='function'){fn=selector;selector='';}events.set(String(key)+'|'+type+'|'+selector,fn);return this;},off(){return this;},data(k,v){if(arguments.length===2){this.values[k]=v;return this;}return this.values[k];},val(){return 'active';},addClass(){return this;},removeClass(){return this;},ready(){return this;}});return nodes.get(key);}
$.ajax=r=>{requests.push(r);return {done(){return this;},fail(){return this;}};};
const document={toString(){return 'document';}},window={currentStudyId:999403};
const ctx=vm.createContext({window,document,jQuery:$,$,eipsiStudyDash:{nonce:'localized-admin-nonce',ajaxUrl:'/wp-admin/admin-ajax.php'},ajaxurl:'/wp-admin/admin-ajax.php',confirm:()=>true,console:{log(){},error(){}},setTimeout(){},clearTimeout(){},setInterval(){},clearInterval(){},Date,Map});
const source=fs.readFileSync('assets/js/study-dashboard.js','utf8').replace('const StudyDashboard = {','const StudyDashboard = window.__s4Dashboard = {');vm.runInContext(source,ctx);
const dashboard=window.__s4Dashboard;dashboard.currentStudyId=999403;dashboard.bindEvents();
function test(name,fn){fn();total++;console.log('PASS '+name);}
let reminder;
test('Visible delegated reminder click uses its real route and localized nonce',()=>{const btn=$('fixture-button');btn.data('participant-id',999407).data('participant-email','fixture@example.invalid');events.get('document|click|.resend-reminder-btn').call(btn,{stopPropagation(){}});reminder=requests.pop();assert.equal(reminder.data.action,'eipsi_resend_participant_email');assert.equal(reminder.data.nonce,'localized-admin-nonce');assert.equal(reminder.data.study_id,999403);assert.equal(reminder.data.wave_id,null);});
test('Actual reminder consumer displays error and success separately',()=>{let toast;dashboard.showToast=(message,type)=>{toast={message,type};};reminder.success({success:false,data:{message:'Controlled failure'}});assert.equal(toast.type,'error');reminder.success({success:true,data:{message:'Delivered'}});assert.deepEqual(toast,{message:'Delivered',type:'success'});});
const modal=fs.readFileSync('admin/templates/study-dashboard-modal.php','utf8');const start=modal.indexOf('function loadParticipants(');vm.runInContext(modal.slice(start,modal.indexOf('function renderParticipants(',start)),ctx);
test('Known P2 inline participant variant throws before request without its undefined nonce',()=>{const before=requests.length;assert.throws(()=>ctx.loadParticipants(999403),/currentParticipantsFilter|eipsi_dashboard_nonce/);/* supply real preceding locals to isolate the nonce fault */vm.runInContext("let currentParticipantsPage=1,currentParticipantsFilter='all',currentParticipantsSearch='';",ctx);assert.throws(()=>ctx.loadParticipants(999403),/eipsi_dashboard_nonce/);assert.equal(requests.length,before);});
const fixture={action:reminder.data.action,nonce_action:'eipsi_study_dashboard_nonce',data:{...reminder.data}};delete fixture.data.action;delete fixture.data.nonce;fs.writeFileSync('tests/s4/consumer-request.json',JSON.stringify(fixture,null,2)+'\n');console.log(total+' consumer tests, 0 failures');
