<?php
require __DIR__.'/concurrency.php';
function s2_reset() {
    global $wpdb;
    foreach($GLOBALS['jobs'] as $id){EIPSI_Notification_Nudge_Queue_Service::release_processing($id);$wpdb->delete($wpdb->prefix.'survey_nudge_jobs',array('id'=>$id));}
    $GLOBALS['m0_mail']=array();
    $wpdb->update($wpdb->prefix.'survey_assignments',array('status'=>'pending','reminder_count'=>1,'available_at'=>date('Y-m-d H:i:s',current_time('timestamp')-600),'due_at'=>date('Y-m-d H:i:s',current_time('timestamp')+21600)),array('id'=>998231));
    EIPSI_Nudge_Cache::invalidate_assignment_cache(998231);
}
function s2_stale($id,$retries=0,$null=false) {global $wpdb;$time=date('Y-m-d H:i:s',current_time('timestamp')-901);$wpdb->update($wpdb->prefix.'survey_nudge_jobs',array('status'=>'processing','processed_at'=>$null?null:$time,'updated_at'=>$time,'retries'=>$retries),array('id'=>$id));}
function s2_claim($id){m0_assert(EIPSI_Notification_Nudge_Queue_Service::mark_processing($id),'Claim failed');}
function s2_worker($id){return EIPSI_Notification_Nudge_Worker_Service::process_job(s2_row($id));}
function s2_mail_failure($callback){$filter=function(){return false;};add_filter('pre_wp_mail',$filter,PHP_INT_MAX);try{return $callback();}finally{remove_filter('pre_wp_mail',$filter,PHP_INT_MAX);}}
$tests['Pending create persists payload and retries zero']=function(){$id=s2_job();$j=s2_row($id);m0_assert($j->status==='pending'&&(int)$j->retries===0&&json_decode($j->payload,true)['assignment_id']===998231,'Create contract');};
$tests['Claim is confirmed and double claim fails']=function(){$id=s2_job();s2_claim($id);m0_assert(!EIPSI_Notification_Nudge_Queue_Service::mark_processing($id)&&s2_row($id)->processed_at,'Double claim');};
$tests['Claim SQL failure is not a winner']=function(){$id=s2_job();$r=s2_fail_update($id,'processing',function()use($id){return EIPSI_Notification_Nudge_Queue_Service::mark_processing($id);});m0_assert($r===false&&s2_row($id)->status==='pending','Claim failure');s2_claim($id);};
$tests['Worker delivery and completed persistence confirmed']=function(){$id=s2_job();$r=s2_worker($id);m0_assert($r['completed']===1&&$r['persistence_failed']===0&&s2_row($id)->status==='completed'&&count($GLOBALS['m0_mail'])===1,'Completion');};
$tests['Worker completed SQL failure separate from delivery']=function(){$id=s2_job();$r=s2_fail_update($id,'completed',function()use($id){return s2_worker($id);});m0_assert($r['completed']===0&&$r['persistence_failed']===1&&s2_row($id)->status==='processing'&&count($GLOBALS['m0_mail'])===1,'False completed statistic');};
$tests['Completed zero rows cannot overwrite cancelled state']=function(){global $wpdb;$id=s2_job();s2_claim($id);$wpdb->update($wpdb->prefix.'survey_nudge_jobs',array('status'=>'cancelled'),array('id'=>$id));m0_assert(EIPSI_Notification_Nudge_Queue_Service::mark_completed($id)===false&&s2_row($id)->status==='cancelled','Zero rows');};
$tests['Completed repetition is a conflict not another completion']=function(){$id=s2_job();s2_claim($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::mark_completed($id)&&!EIPSI_Notification_Nudge_Queue_Service::mark_completed($id),'Idempotency reported new transition');};
$tests['Irrecoverable delivery failure persists failed']=function(){$id=s2_job('send_nudge_1',array('assignment_id'=>999999999));$r=s2_worker($id);m0_assert($r['failed']===1&&s2_row($id)->status==='failed'&&strpos(s2_row($id)->error,'IRRECOVERABLE')!==false,'Failed');};
$tests['Failed SQL error is uncertain not terminal failed']=function(){$id=s2_job('send_nudge_1',array('assignment_id'=>999999999));$r=s2_fail_update($id,'failed',function()use($id){return s2_worker($id);});m0_assert($r['failed']===0&&$r['persistence_failed']===1&&s2_row($id)->status==='processing','False failed');};
$tests['Delivery failure schedules retry and increments once']=function(){$id=s2_job();$r=s2_mail_failure(function()use($id){return s2_worker($id);});$j=s2_row($id);m0_assert($r['retried']===1&&$j->status==='pending'&&(int)$j->retries===1&&strtotime($j->scheduled_at)>=current_time('timestamp')+295,'Retry');};
$tests['Retry SQL failure cannot report requeued']=function(){$id=s2_job();s2_claim($id);$r=s2_fail_update($id,'pending',function()use($id){return EIPSI_Notification_Nudge_Queue_Service::persist_retry_outcome($id,'Email sending failed');});m0_assert($r==='sql_error'&&s2_row($id)->status==='processing'&&(int)s2_row($id)->retries===0,'False retry');};
foreach(array(1=>5,2=>15,3=>45,4=>120) as $attempt=>$minutes){$tests['Retry backoff attempt '.$attempt]=function()use($attempt,$minutes){global $wpdb;$id=s2_job();$wpdb->update($wpdb->prefix.'survey_nudge_jobs',array('retries'=>$attempt-1),array('id'=>$id));s2_claim($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::mark_for_retry($id,'Email sending failed')===true&&abs(strtotime(s2_row($id)->scheduled_at)-current_time('timestamp')-$minutes*60)<3,'Backoff changed');};}
$tests['Fifth retry is confirmed failed and not selected']=function(){global $wpdb;$id=s2_job();$wpdb->update($wpdb->prefix.'survey_nudge_jobs',array('retries'=>4),array('id'=>$id));s2_claim($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::persist_retry_outcome($id,'Email sending failed')==='failed'&&(int)s2_row($id)->retries===5&&s2_row($id)->status==='failed','Retry max');};
$tests['Fresh processing is not recovered']=function(){$id=s2_job();s2_claim($id);EIPSI_Notification_Nudge_Queue_Service::release_processing($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===0&&s2_row($id)->status==='processing','Fresh stolen');};
$tests['Stale live worker is not stolen by recovery']=function(){$id=s2_job();s2_claim($id);s2_stale($id);$r=s2_race($id,array('recover','recover'));m0_assert(array_sum($r)===0&&s2_row($id)->status==='processing','Live stolen');m0_assert(EIPSI_Notification_Nudge_Queue_Service::mark_completed($id),'Live ownership lost');};
$tests['Stale unowned processing recovered with budget and backoff']=function(){$id=s2_job();s2_stale($id,2);m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===1&&s2_row($id)->status==='pending'&&(int)s2_row($id)->retries===3&&strtotime(s2_row($id)->scheduled_at)>=current_time('timestamp')+2695,'Stale recovery');};
$tests['NULL processed_at uses stale updated_at']=function(){$id=s2_job();s2_stale($id,0,true);m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===1&&s2_row($id)->status==='pending','Legacy lease');};
$tests['Stale recovery exhaustion confirms failed']=function(){$id=s2_job();s2_stale($id,4);m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===1&&s2_row($id)->status==='failed'&&(int)s2_row($id)->retries===5,'Recovery max');};
$tests['Recovery SQL failure retains processing and budget']=function(){$id=s2_job();s2_stale($id);$r=s2_fail_update($id,'pending',function(){return EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing();});m0_assert($r===false&&s2_row($id)->status==='processing'&&(int)s2_row($id)->retries===0,'Recovery SQL');};
$tests['Selector triggers bounded recovery without immediate delivery']=function(){$id=s2_job();s2_stale($id);$rows=EIPSI_Notification_Nudge_Queue_Service::get_pending_jobs(100);m0_assert(s2_row($id)->status==='pending'&&!in_array($id,array_map(function($j){return(int)$j->id;},$rows),true),'Recovery bypass backoff');};
$tests['Cancel modern pending assignment uses payload']=function(){$id=s2_job();m0_assert(EIPSI_Notification_Nudge_Queue_Service::cancel_jobs_for_assignment(998231)===1&&s2_row($id)->status==='cancelled','Cancel');};
$tests['Cancel processing leaves live delivery owned']=function(){$id=s2_job();s2_claim($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::cancel_jobs_for_assignment(998231)===0&&s2_row($id)->status==='processing','Processing cancelled');};
$tests['Cancel completed ignored']=function(){$id=s2_job();s2_claim($id);EIPSI_Notification_Nudge_Queue_Service::mark_completed($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::cancel_jobs_for_assignment(998231)===0&&s2_row($id)->status==='completed','Completed cancelled');};
$tests['Cancel SQL failure differs from zero affected']=function(){$id=s2_job();$filter=function($sql){return strpos($sql,'UPDATE wp_survey_nudge_jobs')===0?'UPDATE eipsi_s2_nonexistent_table SET status=1':$sql;};global $wpdb;add_filter('query',$filter);$previous=$wpdb->suppress_errors(true);try{$r=EIPSI_Notification_Nudge_Queue_Service::cancel_jobs_for_assignment(998231);}finally{remove_filter('query',$filter);$wpdb->suppress_errors($previous);}m0_assert($r===false&&s2_row($id)->status==='pending','Cancel SQL');};
$tests['Expiry cancellation matches participant wave JSON only']=function(){$a=s2_job();$b=s2_job('send_nudge_1',array('assignment_id'=>998232,'participant_id'=>998208,'wave_id'=>998221));m0_assert(EIPSI_Notification_Nudge_Queue_Service::cancel_pending_nudges(998207,998221)===1&&s2_row($a)->status==='cancelled'&&s2_row($b)->status==='pending','Expiry cancel');};
$tests['Followup cancellation preserves nudge zero']=function(){$a=s2_job('send_nudge_0');$b=s2_job();m0_assert(EIPSI_Notification_Nudge_Queue_Service::cancel_follow_up_jobs(998231)===1&&s2_row($a)->status==='pending'&&s2_row($b)->status==='cancelled','Stage cancellation');};
$tests['Scheduler cancellation reaches canonical jobs']=function(){$id=s2_job();m0_assert(EIPSI_Notification_Nudge_Schedule_Service::cancel_nudges_for_assignment(998231)===1&&s2_row($id)->status==='cancelled','Scheduler modern');};
$tests['Optional legacy table cancellation remains separate']=function(){global $wpdb;$table=$wpdb->prefix.'survey_job_queue';m0_assert(!$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->esc_like($table))),'Cannot overwrite legacy table');m0_assert($wpdb->query("CREATE TABLE {$table} (id BIGINT PRIMARY KEY, assignment_id BIGINT, status VARCHAR(20))")!==false,'Legacy fixture');try{$wpdb->insert($table,array('id'=>998901,'assignment_id'=>998231,'status'=>'pending'));$wpdb->insert($table,array('id'=>998902,'assignment_id'=>998232,'status'=>'pending'));$id=s2_job();m0_assert(EIPSI_Notification_Nudge_Schedule_Service::cancel_nudges_for_assignment(998231)===2&&s2_row($id)->status==='cancelled'&&$wpdb->get_var("SELECT status FROM {$table} WHERE id=998901")==='cancelled'&&$wpdb->get_var("SELECT status FROM {$table} WHERE id=998902")==='pending','Legacy separation');}finally{$wpdb->query("DROP TABLE {$table}");}};
$tests['Same assignment stage duplicates remain characterized not unique']=function(){$a=s2_job();$b=s2_job();m0_assert($a!==$b&&s2_row($a)->status==='pending'&&s2_row($b)->status==='pending','Unexpected uniqueness');};
$tests['Different stages preserve independent jobs']=function(){$a=s2_job();$b=s2_job('send_nudge_2');m0_assert(s2_worker($a)['completed']===1&&s2_worker($b)['completed']===1&&count($GLOBALS['m0_mail'])===2,'Different stages');};
$tests['Two real workers one pending one delivery']=function(){$id=s2_job();$r=s2_race($id,array('worker','worker'));m0_assert(array_sum(array_column($r,'completed'))===1&&array_sum(array_column($r,'processed'))===1&&array_sum(array_column($r,'intercepted_mail_count'))===1&&s2_row($id)->status==='completed','Double worker');};
$tests['Two recoverers single budget increment']=function(){$id=s2_job();s2_stale($id);$r=s2_race($id,array('recover','recover'));m0_assert(array_sum($r)===1&&(int)s2_row($id)->retries===1,'Double recovery');};
$tests['Worker versus cancel single coherent winner']=function(){$id=s2_job();$r=s2_race($id,array('worker','cancel'));$j=s2_row($id);m0_assert(in_array($j->status,array('completed','cancelled'),true)&&($j->status==='cancelled'?$r[0]['processed']===0:$r[0]['completed']===1),'Worker cancel');};
$tests['Retry versus cancel cannot resurrect terminal state']=function(){$id=s2_job();$r=s2_race($id,array('retry','cancel'));$j=s2_row($id);m0_assert(in_array($j->status,array('pending','cancelled'),true)&&($j->status==='pending'?(int)$j->retries===1:true),'Retry cancel');};
$tests['Concurrent mark_completed no foreign owner succeeds']=function(){$id=s2_job();s2_claim($id);$r=s2_race($id,array('complete','complete'));m0_assert($r===array(false,false)&&EIPSI_Notification_Nudge_Queue_Service::mark_completed($id)&&s2_row($id)->status==='completed','Foreign completion');};
$tests['Worker process dies after claim before delivery']=function(){$id=s2_job();s2_race($id,array('crash','noop'));m0_assert(s2_row($id)->status==='processing','Crash fixture');s2_stale($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===1,'Crash unrecoverable');};
$tests['Crash after controlled delivery leaves uncertain recoverable job']=function(){$id=s2_job();$r=s2_race($id,array('crash_after_mail','noop'));m0_assert($r[0]['delivered']===true&&s2_row($id)->status==='processing','Crash window');s2_stale($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===1&&strpos(s2_row($id)->error,'unknown')!==false,'Unknown outcome lost');};
$tests['DB connection disappears after delivery cannot report completed']=function(){$id=s2_job();$r=s2_race($id,array('disconnect','noop'));m0_assert($r[0]['delivered']===true&&$r[0]['completed']===false&&s2_row($id)->status==='processing','DB loss');};
$tests['Cron cadence survives deactivate reactivate without duplication']=function(){$hook='eipsi_process_nudge_jobs';$plugin=plugin_basename(EIPSI_FORMS_PLUGIN_FILE);deactivate_plugins($plugin);m0_assert(!wp_next_scheduled($hook),'Cron remains');m0_assert(!is_wp_error(activate_plugin($plugin)),'Activate');eipsi_schedule_job_worker();eipsi_schedule_job_worker();$events=array();foreach(_get_cron_array() as $ts=>$hooks){foreach(($hooks[$hook]??array()) as $event){$events[]=$event;}}m0_assert(count($events)===1&&$events[0]['schedule']==='every_5_minutes'&&has_action($hook,'eipsi_process_nudge_jobs_worker')!==false,'Cron duplicated/cadence');};
$tests['Contextual cron processes persisted queued job']=function(){$id=s2_job();delete_transient('eipsi_job_worker_lock');do_action('eipsi_process_nudge_jobs');m0_assert(s2_row($id)->status==='completed'&&!get_transient('eipsi_job_worker_lock'),'Cron worker');};
$tests['Stats read actual processing after terminal SQL failure']=function(){$id=s2_job();s2_fail_update($id,'completed',function()use($id){return s2_worker($id);});$stats=EIPSI_Notification_Nudge_Queue_Service::get_stats();m0_assert($stats['processing']>=1&&s2_row($id)->status==='processing','Stats invented completed');};
$tests['Same connection recovery cannot steal its own live claim']=function(){$id=s2_job();s2_claim($id);s2_stale($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===0&&s2_row($id)->status==='processing','Recursive GET_LOCK stole own job');};
$tests['Lease exact cutoff is eligible']=function(){global $wpdb;$id=s2_job();$time=date('Y-m-d H:i:s',current_time('timestamp')-900);$wpdb->update($wpdb->prefix.'survey_nudge_jobs',array('status'=>'processing','processed_at'=>$time),array('id'=>$id));m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===1,'Lease equality');};
$tests['Worker retry SQL failure not counted as failed or retried']=function(){$id=s2_job();$r=s2_mail_failure(function()use($id){return s2_fail_update($id,'pending',function()use($id){return s2_worker($id);});});m0_assert($r['persistence_failed']===1&&$r['failed']===0&&$r['retried']===0&&s2_row($id)->status==='processing','Retry statistics');};
$tests['Enqueue INSERT SQL error is failure']=function(){global $wpdb;$filter=function($sql)use($wpdb){return strpos($sql,'INSERT INTO `'.$wpdb->prefix.'survey_nudge_jobs`')===0?'INSERT INTO eipsi_s2_nonexistent_table (id) VALUES (1)':$sql;};add_filter('query',$filter);$previous=$wpdb->suppress_errors(true);try{$r=EIPSI_Notification_Nudge_Queue_Service::enqueue('send_nudge_1',array('assignment_id'=>998231));}finally{remove_filter('query',$filter);$wpdb->suppress_errors($previous);}m0_assert($r===false,'INSERT error success');};
$tests['Canonical table unavailable after delivery reports persistence failure']=function(){global $wpdb;$id=s2_job();$table=$wpdb->prefix.'survey_nudge_jobs';$backup=$wpdb->prefix.'s2_owned_queue_unavailable';m0_assert(!$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->esc_like($backup))),'Backup collision');$renamed=false;$filter=function($pre)use($wpdb,$table,$backup,&$renamed){if(!$renamed){m0_assert($wpdb->query("RENAME TABLE {$table} TO {$backup}")!==false,'Controlled table disappearance');$renamed=true;}return $pre;};add_filter('pre_wp_mail',$filter,PHP_INT_MAX);$previous=$wpdb->suppress_errors(true);try{$r=s2_worker($id);}finally{remove_filter('pre_wp_mail',$filter,PHP_INT_MAX);if($renamed){m0_assert($wpdb->query("RENAME TABLE {$backup} TO {$table}")!==false,'Restore canonical table');}$wpdb->suppress_errors($previous);}m0_assert($r['completed']===0&&$r['persistence_failed']===1&&s2_row($id)->status==='processing','Missing table success');};

$tests['Live worker versus stale recovery preserves sole completion']=function(){$id=s2_job();$r=s2_race($id,array('held_worker','noop'),function($dir)use($id){$deadline=microtime(true)+10;while(!file_exists($dir.'/claimed')){m0_assert(microtime(true)<$deadline,'Claim barrier');usleep(10000);}s2_stale($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::recover_stale_processing()===0,'Recovery stole worker');touch($dir.'/continue');});m0_assert($r[0]['delivered']===true&&$r[0]['completed']===true&&s2_row($id)->status==='completed','Worker recovery');};

$tests['Historical seed jobs remain unchanged by fixture selectors']=function(){global $wpdb;foreach($GLOBALS['s2_existing_jobs'] as $expected){$actual=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}survey_nudge_jobs WHERE id=%d",$expected['id']),ARRAY_A);m0_assert($actual===$expected,'Historical job was consumed by test');}};

$tests['Stale selected worker cannot bypass a newly scheduled retry']=function(){$id=s2_job();$old=s2_row($id);s2_claim($id);m0_assert(EIPSI_Notification_Nudge_Queue_Service::mark_for_retry($id,'Controlled delivery failure'),'Retry');$r=EIPSI_Notification_Nudge_Worker_Service::process_job($old);m0_assert($r['processed']===0&&s2_row($id)->status==='pending'&&(int)s2_row($id)->retries===1&&count($GLOBALS['m0_mail'])===0,'Backoff bypass');};
