<?php
/** M1 bootstrap: preserve existing contracts and registration order. */
if (!defined('ABSPATH')) { exit; }

final class EIPSI_Service_Loader {
    /** Existing admin files are intentionally always-loaded: they expose public handlers too. */
    public static function manifest() {
        return array(
            array('file' => 'admin/config/longitudinal-config.php', 'context' => 'always'),
            array('file' => 'admin/menu.php', 'context' => 'always'),
            array('file' => 'admin/results-page.php', 'context' => 'always'),
            array('file' => 'admin/longitudinal-study-page.php', 'context' => 'always'),
            array('file' => 'admin/randomization-pools-page.php', 'context' => 'always'),
            array('file' => 'admin/longitudinal-pool-dashboard.php', 'context' => 'always'),
            array('file' => 'admin/export.php', 'context' => 'always'),
            array('file' => 'admin/handlers.php', 'context' => 'always'),
            array('file' => 'admin/database.php', 'context' => 'always'),
            array('file' => 'admin/database-schema-manager.php', 'context' => 'always'),
            array('file' => 'admin/partial-responses.php', 'context' => 'always'),
            array('file' => 'admin/configuration.php', 'context' => 'always'),
            array('file' => 'admin/ajax-handlers.php', 'context' => 'always'),
            array('file' => 'admin/ajax-handlers-wizard.php', 'context' => 'always'),
            array('file' => 'admin/ajax-email-log-handlers.php', 'context' => 'always'),
            array('file' => 'admin/cron-handlers.php', 'context' => 'always'),
            array('file' => 'admin/cron-reminders-handler.php', 'context' => 'always'),
            array('file' => 'admin/cron-wave-skipping.php', 'context' => 'always'),
            array('file' => 'admin/cron-weekly-reminders.php', 'context' => 'always'),
            array('file' => 'admin/diagnostic-frontend-backend-sync.php', 'context' => 'always'),
            array('file' => 'admin/ajax-wave-state-checker.php', 'context' => 'always'),
            array('file' => 'admin/delete-study-handler.php', 'context' => 'always'),
            array('file' => 'admin/monitoring.php', 'context' => 'always'),
            array('file' => 'admin/study-close-handler.php', 'context' => 'always'),
            array('file' => 'admin/completion-message-backend.php', 'context' => 'always'),
            array('file' => 'admin/form-library.php', 'context' => 'always'),
            array('file' => 'admin/form-library-tools.php', 'context' => 'always'),
            array('file' => 'admin/demo-templates.php', 'context' => 'always'),
            array('file' => 'includes/form-template-render.php', 'context' => 'always'),
            array('file' => 'includes/shortcodes.php', 'context' => 'always'),
            array('file' => 'includes/disable-cache-for-participants.php', 'context' => 'always'),
            array('file' => 'assets/js/eipsi-randomization-shortcode.php', 'context' => 'always'),
            array('file' => 'admin/manual-overrides-table.php', 'context' => 'always'),
            array('file' => 'admin/randomization-db-setup.php', 'context' => 'always'),
            array('file' => 'admin/randomization-shortcode-handler.php', 'context' => 'always'),
            array('file' => 'admin/randomization-config-handler.php', 'context' => 'always'),
            array('file' => 'includes/randomization-frontend.php', 'context' => 'always'),
            array('file' => 'admin/randomization-page.php', 'context' => 'always'),
            array('file' => 'admin/randomization-api.php', 'context' => 'always'),
            array('file' => 'admin/waves-manager-api.php', 'context' => 'always'),
            array('file' => 'admin/services/class-participant-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-auth-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-wave-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-email-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-smtp-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-anonymize-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-assignment-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-magic-links-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-participant-access-log-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-participant-auth-handler.php', 'context' => 'always'),
            array('file' => 'includes/class-survey-access-handler.php', 'context' => 'always'),
            array('file' => 'includes/class-eipsi-migration-runner.php', 'context' => 'always'),
            array('file' => ':migration', 'context' => 'always'),
            array('file' => 'includes/services/class-nudge-job-queue.php', 'context' => 'always'),
            array('file' => 'includes/services/class-nudge-event-scheduler.php', 'context' => 'always'),
            array('file' => 'includes/services/class-nudge-cache.php', 'context' => 'always'),
            array('file' => 'includes/services/class-assignment-state-logger.php', 'context' => 'always'),
            array('file' => 'includes/services/class-participant-dashboard-data.php', 'context' => 'always'),
            array('file' => 'includes/services/class-wave-recalculator.php', 'context' => 'always'),
            array('file' => ':survey-access', 'context' => 'always'),
            array('file' => 'admin/setup-wizard.php', 'context' => 'always'),
            array('file' => 'admin/study-dashboard-api.php', 'context' => 'always'),
            array('file' => 'admin/ajax-email-handlers.php', 'context' => 'always'),
            array('file' => 'admin/ajax-participant-handlers.php', 'context' => 'always'),
            array('file' => 'admin/ajax-export-handlers.php', 'context' => 'always'),
            array('file' => 'admin/services/class-access-log-export-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-completion-verification-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-participant-timeline-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-failed-email-alerts-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-cron-health-service.php', 'context' => 'always'),
            array('file' => 'admin/services/class-participant-data-request-service.php', 'context' => 'always'),
            array('file' => 'admin/testing-helpers.php', 'context' => 'debug'),
            array('file' => 'admin/ajax-phase3-handlers.php', 'context' => 'always'),
            array('file' => 'admin/services/class-pool-assignment-service.php', 'context' => 'always'),
            array('file' => 'admin/pool-assignment-api.php', 'context' => 'always'),
            array('file' => 'admin/services/class-pool-dashboard-service.php', 'context' => 'always'),
            array('file' => 'admin/pool-dashboard-api.php', 'context' => 'always'),
            array('file' => 'admin/pool-rest-api.php', 'context' => 'always'),
            array('file' => 'includes/class-pool-block-renderer.php', 'context' => 'always'),
            array('file' => 'admin/pool-completion-hooks.php', 'context' => 'always'),
            array('file' => 'admin/services/class-t1-anchor-service.php', 'context' => 'always'),
            array('file' => 'admin/ajax-t1-anchor-handlers.php', 'context' => 'always'),
            array('file' => 'admin/services/class-wave-expiration-service.php', 'context' => 'always'),
        );
    }
}
