<?php
require __DIR__.'/concurrency.php';
function m5_config($unit='hours',$factor=1){$c=array();for($s=1;$s<=4;$s++){$c['nudge_'.$s]=array('enabled'=>true,'value'=>$s*$factor,'unit'=>$unit);}return $c;}
function m5_assignment(){global $wpdb;return $wpdb->get_row("SELECT a.*,w.nudge_config,w.follow_up_reminders_enabled FROM {$wpdb->prefix}survey_assignments a JOIN {$wpdb->prefix}survey_waves w ON w.id=a.wave_id WHERE a.id=992231");}
function m5_set($changes){global $wpdb;m0_assert($wpdb->update($wpdb->prefix.'survey_assignments',$changes,array('id'=>992231))!==false,$wpdb->last_error);}
function m5_wave_config($c){global $wpdb;$wpdb->update($wpdb->prefix.'survey_waves',array('nudge_config'=>wp_json_encode($c),'follow_up_reminders_enabled'=>1),array('id'=>992221));}
function m5_plan($assignment=null,$config=null,$now=null){return EIPSI_Notification_Nudge_Policy_Service::follow_up_plan($assignment?:m5_assignment(),$config?:json_decode(m5_assignment()->nudge_config,true),null,$now);}
function m5_events(){return array_values(array_filter(EIPSI_Nudge_Event_Scheduler::get_scheduled_events(),function($e){return (int)$e['assignment_id']===992231;}));}
function m5_job($type='send_nudge_1',$assignment=992231,$priority=10,$when=null){$id=EIPSI_Nudge_Job_Queue::enqueue($type,array('assignment_id'=>$assignment,'participant_id'=>992207,'study_id'=>992203,'wave_id'=>992221),$priority,$when);m0_assert($id,'Queue insert failed');$GLOBALS['m5_jobs'][]=$id;return $id;}
function m5_job_row($id){global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}survey_nudge_jobs WHERE id=%d",$id));}
function m5_mail_fail($pre,$atts){do_action('wp_mail_failed',new WP_Error('controlled_failure','M5 controlled delivery failure'));return false;}
function m5_notification_reset(){
 global $wpdb;$GLOBALS['m0_mail']=array();remove_filter('pre_wp_mail','m5_mail_fail',PHP_INT_MAX);
 foreach(($GLOBALS['m5_jobs']??array()) as $id){$wpdb->delete($wpdb->prefix.'survey_nudge_jobs',array('id'=>$id));}$GLOBALS['m5_jobs']=array();
 $wpdb->delete($wpdb->prefix.'survey_email_log',array('survey_id'=>992203));
 $wpdb->delete($wpdb->prefix.'survey_weekly_reminders',array('assignment_id'=>992231));
 $wpdb->update($wpdb->prefix.'survey_participants',array('created_at'=>current_time('mysql')),array('id'=>992207));
 foreach(array(992231,992232,992233) as $id){EIPSI_Nudge_Cache::invalidate_assignment_cache($id);}
 foreach(array(992221,992222,992223) as $wave){
  foreach(array('eipsi_wave_email_retries_','eipsi_nudge_0_sent_','eipsi_recovery_') as $prefix){$key=$prefix.'992207_'.$wave;delete_transient($key);delete_option($key);$GLOBALS['m5_options'][]=$key;}
 }
 $wpdb->update($wpdb->prefix.'survey_assignments',array('status'=>'submitted','reminder_count'=>0),array('study_id'=>992203));
 m5_set(array('status'=>'pending','reminder_count'=>1,'available_at'=>date('Y-m-d H:i:s',current_time('timestamp')-600),'due_at'=>date('Y-m-d H:i:s',current_time('timestamp')+21600),'last_nudge_sent_at'=>null));
 m5_wave_config(m5_config());
 foreach(m5_events() as $e){wp_clear_scheduled_hook('eipsi_scheduled_nudge_event',array(array('assignment_id'=>$e['assignment_id'],'stage'=>$e['stage'])));}
}
function m5_assert_plan_events(){
 $events=m5_events();$plan=m5_plan();m0_assert(count($events)===count($plan),'Event count differs from plan');
 foreach($events as $event){m0_assert(isset($plan[$event['stage']])&&$plan[$event['stage']]['timestamp']===$event['timestamp'],'Event differs from absolute plan');}
}
function m5_weekly_enable($extra=array()){global $wpdb;$wpdb->update($wpdb->prefix.'survey_studies',array('config'=>wp_json_encode(array('weekly_reminders'=>array_merge(array('enabled'=>true,'start_after_nudge'=>1,'frequency_days'=>7),$extra)))),array('id'=>992203));}
$contracts=json_decode(file_get_contents(__DIR__.'/contracts.json'),true);
foreach($contracts['templates'] as $file=>$hash){$tests['Frozen template '.$file]=function()use($file,$hash){m0_assert(hash_file('sha256',EIPSI_FORMS_PLUGIN_DIR.$file)===$hash,'Email template changed');};}
foreach($contracts['public_signatures'] as $file=>$signatures){$tests['Frozen public facade '.$file]=function()use($file,$signatures){$source=file_get_contents(EIPSI_FORMS_PLUGIN_DIR.$file);foreach($signatures as $signature){m0_assert(strpos($source,$signature)!==false,'Public signature changed: '.$signature);}};}
$tests['Absolute stages 1 to 4']=function(){$a=m5_assignment();$p=m5_plan();foreach(range(1,4) as $s){m0_assert($p[$s]['timestamp']===strtotime($a->available_at)+$s*3600,'Cumulative timing');}};
$tests['Fractional minute offset preserved']=function(){$a=m5_assignment();$a->available_at=date('Y-m-d H:i:s',time()+60);$p=m5_plan($a,m5_config('minutes',1.2));m0_assert($p[1]['timestamp']===strtotime($a->available_at)+72,'Minute precision');};
foreach(array('minutes'=>60,'hours'=>3600,'days'=>86400,'minutos'=>60,'horas'=>3600,'dias'=>86400) as $unit=>$seconds){$tests['Schedule conversion '.$unit]=function()use($unit,$seconds){m0_assert(EIPSI_Notification_Nudge_Policy_Service::schedule_seconds(2,$unit)===2*$seconds,'Conversion changed');};}
$tests['No stages in past']=function(){m5_set(array('available_at'=>date('Y-m-d H:i:s',time()-5*3600)));m0_assert(m5_plan()===array(),'Past stages scheduled');};
$tests['No stages at or after deadline']=function(){$a=m5_assignment();$a->due_at=date('Y-m-d H:i:s',strtotime($a->available_at)+3600);m0_assert(m5_plan($a)===array(),'At-deadline stage accepted');};
$tests['Sent stages excluded']=function(){m5_set(array('reminder_count'=>3));m0_assert(array_keys(m5_plan())===array(3,4),'Sent stages repeated');};
$tests['Disabled stage absent']=function(){$c=m5_config();$c['nudge_2']['enabled']=false;m0_assert(array_keys(m5_plan(null,$c))===array(1,3,4),'Disabled stage scheduled');};
$tests['Real WP cron matches policy plan']=function(){EIPSI_Nudge_Event_Scheduler::schedule_nudge_sequence(992231);m5_assert_plan_events();};
$tests['Repeated availability does not resend nudge zero']=function(){EIPSI_Nudge_Event_Scheduler::schedule_nudge_sequence(992231);EIPSI_Nudge_Event_Scheduler::schedule_nudge_sequence(992231);m5_assert_plan_events();m0_assert(count($GLOBALS['m0_mail'])===0,'Nudge0 resent');};
$tests['Config refresh uses fresh absolute offsets']=function(){EIPSI_Nudge_Event_Scheduler::schedule_nudge_sequence(992231);m5_wave_config(m5_config('hours',1.25));EIPSI_Nudge_Event_Scheduler::refresh_wave_follow_ups(992221,992231);m5_assert_plan_events();};
$tests['Deadline change rebuilds bounded plan']=function(){EIPSI_Nudge_Event_Scheduler::schedule_nudge_sequence(992231);m5_set(array('due_at'=>date('Y-m-d H:i:s',time()+5400)));do_action('eipsi_assignment_deadline_changed',992231);m5_assert_plan_events();m0_assert(count(m5_events())===1,'Deadline not consumed');};
$tests['Cancellation removes real cron stages']=function(){EIPSI_Nudge_Event_Scheduler::schedule_nudge_sequence(992231);EIPSI_Nudge_Event_Scheduler::cancel_scheduled_nudges(992231);m0_assert(m5_events()===array(),'Cancellation incomplete');};
$tests['Disable followups preserves configuration and cancels jobs']=function(){global $wpdb;$job=m5_job();EIPSI_Nudge_Event_Scheduler::schedule_nudge_sequence(992231);$wpdb->update($wpdb->prefix.'survey_waves',array('follow_up_reminders_enabled'=>0),array('id'=>992221));EIPSI_Nudge_Event_Scheduler::refresh_wave_follow_ups(992221,992231);m0_assert(m5_events()===array()&&m5_job_row($job)->status==='cancelled'&&m5_assignment()->nudge_config!=='{}','Disabled config lost');};
$tests['Catchup successor uses absolute plan']=function(){EIPSI_Notification_Nudge_Schedule_Service::reschedule_next_stage(992231,1);$e=m5_events();m0_assert(count($e)===1&&$e[0]['timestamp']===strtotime(m5_assignment()->available_at)+7200,'Catchup shifted from now');};
$tests['Catchup successor excluded beyond due']=function(){m5_set(array('due_at'=>date('Y-m-d H:i:s',time()+1200)));EIPSI_Notification_Nudge_Schedule_Service::reschedule_next_stage(992231,1);m0_assert(m5_events()===array(),'Catchup beyond due');};
$tests['T1 anchored legacy pending cancellation characterized']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_assignments',array('status'=>'pending','reminder_count'=>1,'available_at'=>date('Y-m-d H:i:s',time()-600),'due_at'=>date('Y-m-d H:i:s',time()+21600)),array('id'=>992232));$a=$wpdb->get_row("SELECT * FROM {$wpdb->prefix}survey_assignments WHERE id=992232");$a->follow_up_reminders_enabled=1;$wpdb->update($wpdb->prefix.'survey_waves',array('nudge_config'=>wp_json_encode(m5_config()),'follow_up_reminders_enabled'=>1),array('id'=>992222));EIPSI_Nudge_Event_Scheduler::schedule_follow_up_nudges_only($a);EIPSI_Nudge_Event_Scheduler::reschedule_all_nudges_for_participant(992203,992207);foreach(EIPSI_Nudge_Event_Scheduler::get_scheduled_events() as $e){m0_assert((int)$e['assignment_id']!==992232,'Existing T1 cancellation contract changed');}};
$tests['Scheduler failure leaves committed config']=function(){
 require_once EIPSI_FORMS_PLUGIN_DIR.'includes/services/class-nudge-service.php';
 $c=m5_config('minutes',60);$committed=false;$attempted=false;
 $query=function($sql)use(&$committed){if(strtoupper(trim($sql))==='COMMIT'){$committed=true;}return $sql;};
 $fail=function($pre,$event)use(&$committed,&$attempted){if($event->hook!=='eipsi_scheduled_nudge_event'){return $pre;}$attempted=$committed;return false;};
 add_filter('query',$query);add_filter('pre_schedule_event',$fail,10,2);
 try{$result=EIPSI_Nudge_Service::save_wave_configuration(992221,$c);m0_assert($attempted&&is_wp_error($result)&&json_decode(m5_assignment()->nudge_config,true)===$c,'Config was rolled back or scheduling did not follow COMMIT');}
 finally{remove_filter('query',$query);remove_filter('pre_schedule_event',$fail,10);}
};
$tests['Cache sent marking and invalidation']=function(){EIPSI_Nudge_Cache::mark_nudge_sent(992231,1);m0_assert(EIPSI_Nudge_Cache::is_nudge_sent(992231,1)===true,'Sent marker absent');EIPSI_Nudge_Cache::invalidate_assignment_cache(992231);m0_assert(EIPSI_Nudge_Cache::get_cached_should_send(992231,1)===null,'Cache invalidation failed');};
$tests['Nudge0 sends and advances count once']=function(){m5_set(array('reminder_count'=>0));$r=EIPSI_Nudge_Job_Queue::execute_nudge_0(array('assignment_id'=>992231));m0_assert($r['success']&&(int)m5_assignment()->reminder_count===1&&count($GLOBALS['m0_mail'])===1,'Nudge0 failed');$r=EIPSI_Nudge_Job_Queue::execute_nudge_0(array('assignment_id'=>992231));m0_assert($r['success']&&count($GLOBALS['m0_mail'])===1,'Nudge0 repeated');};
$tests['Nudge0 cannot notify future availability']=function(){m5_set(array('reminder_count'=>0,'available_at'=>date('Y-m-d H:i:s',time()+3600)));$r=EIPSI_Nudge_Job_Queue::execute_nudge_0(array('assignment_id'=>992231));m0_assert(!$r['success']&&count($GLOBALS['m0_mail'])===0,'Future nudge0 sent');};
$tests['Nudge0 failure stores retry diagnostics']=function(){m5_set(array('reminder_count'=>0));add_filter('pre_wp_mail','m5_mail_fail',PHP_INT_MAX,2);$r=EIPSI_Nudge_Job_Queue::execute_nudge_0(array('assignment_id'=>992231));$retry=get_transient('eipsi_wave_email_retries_992207_992221');m0_assert(!$r['success']&&(int)m5_assignment()->reminder_count===0&&$retry['attempts']===1&&!empty($retry['errors']),'Failure lost');};
$tests['Nudge0 retry cooldown prevents another send']=function(){m5_set(array('reminder_count'=>0));set_transient('eipsi_wave_email_retries_992207_992221',array('attempts'=>1,'last_attempt'=>time(),'errors'=>array()),3600);$r=EIPSI_Nudge_Job_Queue::execute_nudge_0(array('assignment_id'=>992231));m0_assert(!$r['success']&&$r['error']==='retry_cooldown'&&count($GLOBALS['m0_mail'])===0,'Cooldown bypass');};
$tests['Nudge0 retry maximum preserved']=function(){m5_set(array('reminder_count'=>0));set_transient('eipsi_wave_email_retries_992207_992221',array('attempts'=>3,'last_attempt'=>0,'errors'=>array()),3600);$r=EIPSI_Nudge_Job_Queue::execute_nudge_0(array('assignment_id'=>992231));m0_assert(!$r['success']&&count($GLOBALS['m0_mail'])===0,'Retry max bypass');};
$tests['Stages 1 and 2 update count and sent marker']=function(){foreach(array(1,2) as $stage){$r=EIPSI_Nudge_Job_Queue::execute_nudge_followup(array('assignment_id'=>992231),$stage);m0_assert($r['success']&&(int)m5_assignment()->reminder_count===$stage+1&&EIPSI_Nudge_Cache::is_nudge_sent(992231,$stage),'Followup state failed');}m0_assert(count($GLOBALS['m0_mail'])===2,'Delivery count differs');};
$tests['Repeated scheduled stage guarded by persisted count']=function(){EIPSI_Nudge_Event_Scheduler::execute_scheduled_nudge(array('assignment_id'=>992231,'stage'=>1));EIPSI_Nudge_Event_Scheduler::execute_scheduled_nudge(array('assignment_id'=>992231,'stage'=>1));m0_assert((int)m5_assignment()->reminder_count===2&&count($GLOBALS['m0_mail'])===1,'Repeated event resent');};
$tests['Queue creates distinct jobs without exactly-once assumption']=function(){$a=m5_job();$b=m5_job();m0_assert($a!==$b&&m5_job_row($a)->status==='pending'&&m5_job_row($b)->status==='pending','Distinct enqueue conflated');};
$tests['Atomic claim only first wins']=function(){$id=m5_job();m0_assert(EIPSI_Nudge_Job_Queue::mark_processing($id)&&!EIPSI_Nudge_Job_Queue::mark_processing($id)&&m5_job_row($id)->status==='processing','Claim duplicated');};
$tests['Worker completes owned job and records result']=function(){$id=m5_job();$r=EIPSI_Notification_Nudge_Worker_Service::process_job(m5_job_row($id));m0_assert($r['completed']===1&&m5_job_row($id)->status==='completed'&&!empty(m5_job_row($id)->result),'Job not completed');};
$tests['Worker delivery failure requeues with backoff']=function(){$id=m5_job();add_filter('pre_wp_mail','m5_mail_fail',PHP_INT_MAX,2);$r=EIPSI_Notification_Nudge_Worker_Service::process_job(m5_job_row($id));$j=m5_job_row($id);m0_assert($r['retried']===1&&$j->status==='pending'&&(int)$j->retries===1&&strtotime($j->scheduled_at)>=time()+295&&(int)m5_assignment()->reminder_count===1,'Retry state incorrect');};
$tests['Irrecoverable failure is permanent']=function(){$id=m5_job('send_nudge_1',99999999);$r=EIPSI_Notification_Nudge_Worker_Service::process_job(m5_job_row($id));m0_assert($r['failed']===1&&m5_job_row($id)->status==='failed'&&strpos(m5_job_row($id)->error,'IRRECOVERABLE')!==false,'Permanent failure retried');};
$tests['Retry exhaustion at five attempts']=function(){$id=m5_job();for($i=1;$i<=5;$i++){global $wpdb;$wpdb->update($wpdb->prefix.'survey_nudge_jobs',array('scheduled_at'=>current_time('mysql')),array('id'=>$id));m0_assert(EIPSI_Nudge_Job_Queue::mark_processing($id),'Retry requires owned processing claim');$r=EIPSI_Nudge_Job_Queue::mark_for_retry($id,'Email sending failed');m0_assert($r===($i<5),'Retry boundary');}m0_assert(m5_job_row($id)->status==='failed'&&(int)m5_job_row($id)->retries===5,'Exhaustion state');};
$tests['Pending selection excludes future jobs and preserves priority']=function(){$slow=m5_job('send_nudge_1',992231,90);$fast=m5_job('send_nudge_1',992231,1);$future=m5_job('send_nudge_1',992231,1,date('Y-m-d H:i:s',time()+3600));$ids=array_map(function($j){return (int)$j->id;},EIPSI_Nudge_Job_Queue::get_pending_jobs(10000));m0_assert(in_array($fast,$ids,true)&&in_array($slow,$ids,true)&&!in_array($future,$ids,true)&&array_search($fast,$ids)<array_search($slow,$ids),'Queue selection changed');};
$tests['Two workers same real job one claim and delivery']=function(){$id=m5_job();$r=m5_concurrent('worker',array($id,$id));m0_assert($r[0]['completed']+$r[1]['completed']===1&&m5_job_row($id)->status==='completed'&&(int)m5_assignment()->reminder_count===2,'Concurrent workers incoherent: '.wp_json_encode(array($r,m5_job_row($id),m5_assignment())));global $wpdb;m0_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_email_log WHERE survey_id=992203 AND status='sent'")===1,'Same job delivered twice');};
$tests['Two connections atomic pending claim']=function(){$id=m5_job();$r=m5_concurrent('claim',array($id,$id));sort($r);m0_assert($r===array(false,true)&&m5_job_row($id)->status==='processing','Cross-process claim not atomic: '.wp_json_encode(array($r,m5_job_row($id))));};
$tests['Two schedulers same assignment produce one event per stage']=function(){m5_concurrent('schedule');m5_assert_plan_events();};
$tests['Concurrent config refresh final cron follows fresh database']=function(){m5_concurrent('reschedule',array(),array(m5_config('hours',1),m5_config('hours',1.25)));m5_assert_plan_events();};
$tests['Distinct jobs same assignment stages converge after retry']=function(){global $wpdb;$a=m5_job('send_nudge_1');$b=m5_job('send_nudge_2');m5_concurrent('worker',array($a,$b));if(m5_job_row($b)->status==='pending'){$wpdb->update($wpdb->prefix.'survey_nudge_jobs',array('scheduled_at'=>current_time('mysql')),array('id'=>$b));EIPSI_Notification_Nudge_Worker_Service::process_job(m5_job_row($b));}m0_assert(m5_job_row($a)->status==='completed'&&m5_job_row($b)->status==='completed'&&(int)m5_assignment()->reminder_count===3,'Distinct jobs did not converge');};
$tests['Delivery returns sent log id with headers subject metadata']=function(){global $wpdb;$id=EIPSI_Email_Service::send_email(992203,992207,'m2-a@example.invalid','m5_probe','M5 subject','<p>M5 body</p>',array('stage'=>2));$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}survey_email_log WHERE id=%d",$id));$mail=end($GLOBALS['m0_mail']);m0_assert($id>0&&$row->status==='sent'&&$mail['subject']==='M5 subject'&&strpos(implode(' ',(array)$mail['headers']),'text/html')!==false&&json_decode($row->metadata,true)['stage']===2,'Delivery contract altered');};
$tests['Delivery failure returns false and failed log']=function(){global $wpdb;add_filter('pre_wp_mail','m5_mail_fail',PHP_INT_MAX,2);$r=EIPSI_Email_Service::send_email(992203,992207,'m2-a@example.invalid','m5_probe','M5 subject','body',array('stage'=>2));$row=$wpdb->get_row("SELECT * FROM {$wpdb->prefix}survey_email_log WHERE survey_id=992203 ORDER BY id DESC LIMIT 1");m0_assert($r===false&&$row->status==='failed'&&strpos($row->error_message,'controlled')!==false,'Failure contract lost');};
$tests['Weekly T1 selects only pending T1 and obeys interval']=function(){m5_weekly_enable();eipsi_weekly_t1_reminders();m0_assert(count($GLOBALS['m0_mail'])===1,'Weekly selection failed');eipsi_weekly_t1_reminders();m0_assert(count($GLOBALS['m0_mail'])===1,'Daily cron ignored weekly interval');};
$tests['Weekly T1 waits for configured nudge threshold']=function(){m5_weekly_enable(array('start_after_nudge'=>4));eipsi_weekly_t1_reminders();m0_assert(count($GLOBALS['m0_mail'])===0,'Weekly before nudges');};
$tests['Weekly T1 failure does not record sent weekly row']=function(){global $wpdb;m5_weekly_enable();add_filter('pre_wp_mail','m5_mail_fail',PHP_INT_MAX,2);eipsi_weekly_t1_reminders();m0_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}survey_weekly_reminders WHERE assignment_id=992231")===0,'Failed weekly logged sent');};
$tests['Dropout sends with persisted rate limit']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_studies',array('config'=>'{"dropout_recovery_enabled":true,"dropout_recovery_days":7}'),array('id'=>992203));$wpdb->update($wpdb->prefix.'survey_participants',array('created_at'=>date('Y-m-d H:i:s',time()-40*86400)),array('id'=>992207));eipsi_send_dropout_recovery_hourly();m0_assert((int)m5_assignment()->reminder_count===2&&count($GLOBALS['m0_mail'])===1,'Recovery failed');eipsi_send_dropout_recovery_hourly();m0_assert(count($GLOBALS['m0_mail'])===1,'Recovery rate limit bypass');};
$tests['Manual participant reminder through existing batch API']=function(){$r=EIPSI_Email_Service::send_manual_reminders(992203,array(992207));m0_assert($r['sent_count']===1&&$r['failed_count']===0&&count($GLOBALS['m0_mail'])===1,'Manual participant flow failed');};
$tests['Manual wave reminder through existing batch API']=function(){$r=EIPSI_Email_Service::send_manual_reminders(992203,array(992207),992221,'M5 custom');m0_assert($r['sent_count']===1&&strpos(end($GLOBALS['m0_mail'])['subject'],'Toma 1')!==false,'Manual wave flow failed');};
$tests['Individual reminder missing action stays explicit debt']=function(){m0_assert(!has_action('wp_ajax_eipsi_send_individual_reminder'),'Unrequested handler restored');};
foreach(array('eipsi_send_wave_reminders_hourly'=>'every_minute','eipsi_send_dropout_recovery_hourly'=>'every_minute','eipsi_purge_access_logs_daily'=>'daily') as $hook=>$schedule){$tests['Cron Health repair cadence '.$hook]=function()use($hook,$schedule){wp_clear_scheduled_hook($hook);$r=EIPSI_Cron_Health_Service::reschedule_cron($hook);$e=wp_get_scheduled_event($hook);m0_assert($r['success']&&$e->schedule===$schedule,'Repair changed cadence');};}
$tests['Cron Health preserves study args and logical cadence']=function(){wp_clear_scheduled_hook('eipsi_study_cron_job');wp_schedule_event(time()+600,'eipsi_weekly','eipsi_study_cron_job',array(992203,'reminders'));$r=EIPSI_Cron_Health_Service::reschedule_cron('eipsi_study_cron_job');$e=wp_get_scheduled_event('eipsi_study_cron_job',array(992203,'reminders'));m0_assert($r['success']&&$e&&$e->schedule==='eipsi_weekly'&&!wp_get_scheduled_event('eipsi_study_cron_job'),'Study args lost');wp_clear_scheduled_hook('eipsi_study_cron_job',array(992203,'reminders'));};
$tests['Cron Health refuses argless study fabrication']=function(){wp_clear_scheduled_hook('eipsi_study_cron_job');$r=EIPSI_Cron_Health_Service::reschedule_cron('eipsi_study_cron_job');m0_assert(!$r['success']&&!wp_next_scheduled('eipsi_study_cron_job'),'Argless study created');};
$tests['Cron observers retain priority 999']=function(){global $wp_filter;foreach(array('eipsi_send_wave_reminders_hourly','eipsi_send_dropout_recovery_hourly') as $hook){m0_assert(isset($wp_filter[$hook]->callbacks[999]),'Health observer absent');}};
$tests['Legacy and current wave callbacks remain registered']=function(){m0_assert(has_action('eipsi_send_wave_reminders_hourly','eipsi_run_send_wave_reminders')!==false&&has_action('eipsi_send_wave_reminders_hourly','eipsi_send_wave_reminders_hourly')!==false,'Legacy/current callback removed');};
$tests['Deprecated daily weekly callbacks remain log only']=function(){$before=count($GLOBALS['m0_mail']);eipsi_send_take_reminders_daily();eipsi_send_take_reminders_weekly();m0_assert(count($GLOBALS['m0_mail'])===$before,'Deprecated log callback started sending');};
$tests['Scheduled delivery transaction ordering preserved']=function(){$trace=array();$observe=function($q)use(&$trace){if(in_array(strtoupper(trim($q)),array('START TRANSACTION','COMMIT','ROLLBACK'),true)){$trace[]=strtoupper(trim($q));}return $q;};$mail=function($pre)use(&$trace){$trace[]='MAIL';return $pre;};add_filter('query',$observe);add_filter('pre_wp_mail',$mail,PHP_INT_MAX);try{EIPSI_Nudge_Event_Scheduler::execute_scheduled_nudge(array('assignment_id'=>992231,'stage'=>1));m0_assert(array_search('START TRANSACTION',$trace)<array_search('MAIL',$trace)&&array_search('MAIL',$trace)<array_search('COMMIT',$trace),'Delivery transaction moved');}finally{remove_filter('query',$observe);remove_filter('pre_wp_mail',$mail,PHP_INT_MAX);}};
$tests['Legacy wave post meta pipeline still delivers']=function(){
 global $wpdb;$wpdb->update($wpdb->prefix.'survey_waves',array('due_date'=>date('Y-m-d H:i:s',time()+86400)),array('id'=>992221));
 $posts=function($pre,$query){return $query->get('post_type')==='eipsi_form'?array(992203):$pre;};
 $meta=function($pre,$id,$key){if((int)$id!==992203){return $pre;}if($key==='_eipsi_reminders_enabled'){return 1;}if($key==='_eipsi_reminder_days_before'){return 3;}return $pre;};
 add_filter('posts_pre_query',$posts,10,2);add_filter('get_post_metadata',$meta,10,3);
 try{eipsi_run_send_wave_reminders();m0_assert(count($GLOBALS['m0_mail'])===1,'Legacy wave no delivery');eipsi_run_send_wave_reminders();m0_assert(count($GLOBALS['m0_mail'])===1,'Legacy rate limit broken');}
 finally{remove_filter('posts_pre_query',$posts,10);remove_filter('get_post_metadata',$meta,10);delete_transient('eipsi_reminder_sent_992207_992221');}
};
$tests['Legacy deferred manual cron still delivers']=function(){do_action('eipsi_send_manual_reminder','m5@example.invalid','https://example.invalid/survey');m0_assert(count($GLOBALS['m0_mail'])===1,'Deferred reminder lost');};
$tests['Dropout failed delivery keeps count and does not rate limit']=function(){global $wpdb;$wpdb->update($wpdb->prefix.'survey_studies',array('config'=>'{"dropout_recovery_enabled":true,"dropout_recovery_days":7}'),array('id'=>992203));$wpdb->update($wpdb->prefix.'survey_participants',array('created_at'=>date('Y-m-d H:i:s',time()-40*86400)),array('id'=>992207));add_filter('pre_wp_mail','m5_mail_fail',PHP_INT_MAX,2);eipsi_send_dropout_recovery_hourly();m0_assert((int)m5_assignment()->reminder_count===1&&!get_transient('eipsi_recovery_992207_992221'),'Failed recovery advanced state');};
$tests['Deactivation cleans notification singles without clinical data loss']=function(){
 $plugin=plugin_basename(EIPSI_FORMS_PLUGIN_FILE);$before=m5_assignment();
 foreach(array('eipsi_wave_available_retry','eipsi_scheduled_nudge_event','eipsi_process_nudge_jobs','eipsi_send_manual_reminder') as $hook){wp_schedule_single_event(time()+600,$hook,array('m5_fixture'));}
 try{deactivate_plugins($plugin);foreach(array('eipsi_wave_available_retry','eipsi_scheduled_nudge_event','eipsi_process_nudge_jobs','eipsi_send_manual_reminder') as $hook){m0_assert(!wp_next_scheduled($hook,array('m5_fixture')),'Notification cron remains');}m0_assert(m5_assignment()->status===$before->status&&m5_assignment()->due_at===$before->due_at,'Clinical state altered');}
 finally{$r=activate_plugin($plugin);m0_assert(!is_wp_error($r),'Reactivation failed');}
};
$tests['Repeated activation retains exact notification cron']=function(){$before=_get_cron_array();eipsi_forms_activate();eipsi_forms_activate();m0_assert(_get_cron_array()===$before,'Activation duplicated cron');};
$tests['Notification bootstrap defines owners without hook mutation']=function(){global $wp_filter;$before=array();foreach($wp_filter as $hook=>$callbacks){$before[$hook]=$callbacks->callbacks;}include EIPSI_FORMS_PLUGIN_DIR.'includes/notifications/bootstrap.php';$after=array();foreach($wp_filter as $hook=>$callbacks){$after[$hook]=$callbacks->callbacks;}m0_assert($before===$after&&class_exists('EIPSI_Notification_Nudge_Policy_Service')&&class_exists('EIPSI_Notification_Email_Delivery_Service'),'Bootstrap introduced callbacks');};
$tests['HTTP admin email configuration remains reachable']=function(){$r=m0_http('/wp-admin/',null,true);m0_assert(!is_wp_error($r)&&wp_remote_retrieve_response_code($r)===200,'Admin smoke failed');};
$tests['Longitudinal submit state precedes post commit nudge delivery']=function(){
 global $wpdb;m5_set(array('reminder_count'=>0,'due_at'=>null));$wpdb->update($wpdb->prefix.'survey_assignments',array('status'=>'pending','reminder_count'=>0),array('id'=>992232));$wpdb->update($wpdb->prefix.'survey_waves',array('offset_minutes'=>0,'window_minutes'=>60,'interval_days'=>0,'time_unit'=>'0'),array('id'=>992222));
 $states=array();$cb=function($pre)use(&$states){$states[]=m5_assignment()->status;return $pre;};add_filter('pre_wp_mail',$cb,PHP_INT_MAX);
 try{$r=EIPSI_Longitudinal_Submission_Service::handle_submission(array('wave_id'=>992221,'study_id'=>992203,'longitudinal_participant_id'=>992207,'stable_form_id'=>'m2-long-form','submitted_at'=>current_time('mysql'),'user_data'=>array('email'=>'m2-a@example.invalid')));m0_assert(!empty($r['has_next_wave'])&&!empty($states)&&count(array_filter($states,function($s){return $s!=='submitted';}))===0,'Delivery ordering: '.wp_json_encode(array($r,$states)));}
 finally{remove_filter('pre_wp_mail',$cb,PHP_INT_MAX);}
};
function m5_tokens($source){$out='';foreach(token_get_all('<?php '.$source) as $t){if(is_array($t)){if(in_array($t[0],array(T_OPEN_TAG,T_WHITESPACE,T_COMMENT,T_DOC_COMMENT),true)){continue;}$out.=$t[1];}else{$out.=$t;}}return $out;}
foreach($contracts['critical_bodies'] as $row){$tests['Frozen critical body '.$row['class'].'::'.$row['method']]=function()use($row){$r=new ReflectionMethod($row['class'],$row['method']);$source=implode('',array_slice(file($r->getFileName()),$r->getStartLine()-1,$r->getEndLine()-$r->getStartLine()+1));$s2delta=json_decode(file_get_contents(__DIR__.'/../s2/method-migrations.json'),true)[$row['class'].'::'.$row['method']]??null;if($s2delta){m0_assert(hash('sha256',m5_tokens($row['source']))===$s2delta['before_s2_tokens_sha256'],'Original M5 contract was replaced');m0_assert(hash('sha256',m5_tokens($source))===$s2delta['s2_tokens_sha256'],'Change exceeds explicit S2 delta');return;}$delta=json_decode(file_get_contents(__DIR__.'/../s1/method-migrations.json'),true)[$row['class'].'::'.$row['method']]??null;if($delta){m0_assert(hash('sha256',m5_tokens($row['source']))===$delta['before_s1_tokens_sha256'],'Original M5 contract was replaced');m0_assert(hash('sha256',m5_tokens($source))===$delta['s1_tokens_sha256'],'Change exceeds explicit S1 delta');}else m0_assert(m5_tokens($source)===m5_tokens($row['source']),'Critical rule or claim changed: '.substr(m5_tokens($source),0,150).' EXPECTED '.substr(m5_tokens($row['source']),0,150));};}
$tests['Conditioned purge removes private duplicates and retains public facades']=function(){
 $manifest=json_decode(file_get_contents(__DIR__.'/purge-manifest.json'),true);
 $classes=array('admin/services/class-email-service.php'=>'EIPSI_Email_Service','admin/services/class-wave-availability-email-service.php'=>'EIPSI_Wave_Availability_Email_Service','includes/services/class-nudge-event-scheduler.php'=>'EIPSI_Nudge_Event_Scheduler','includes/services/class-nudge-job-queue.php'=>'EIPSI_Nudge_Job_Queue','includes/services/class-nudge-cache.php'=>'EIPSI_Nudge_Cache');
 foreach($manifest['removed'] as $row){m0_assert($row['classification']==='A'&&!method_exists($classes[$row['file']],$row['method']),'Private duplicate retained');}
 m0_assert(method_exists('EIPSI_Email_Service','send_email')&&has_action('eipsi_wave_available',array('EIPSI_Nudge_Event_Scheduler','schedule_nudge_sequence'))!==false,'Public facade removed');
};
