<?php
$tests['Anonymous issued capability closes exactly its modern row']=function(){$r=s41_new('anonymous');list($status,$j)=s41_close($r);m0_assert($status===200&&$j['success']&&!s41_row($r),'Own close');};
$tests['Correct fingerprint and config without proof cannot reset']=function(){$r=s41_new('missing');$before=s41_row($r);list($status,$j)=s41_close($r,'');m0_assert($status===403&&!$j['success']&&s41_row($r)===$before,'Tracking authorized reset');};
$tests['Public nonce without capability cannot reset']=function(){$r=s41_new('nonce');list($status,$j)=s41_close($r,'');m0_assert(!$j['success']&&s41_row($r),'Public nonce accepted');};
$tests['Fabricated or tampered signature cannot reset']=function(){$r=s41_new('tampered');foreach(array('forged',$r['proof'].'x')as$p){list($status,$j)=s41_close($r,$p);m0_assert($status===403&&!$j['success']&&s41_row($r),'Forged proof');}};
$tests['Capability from foreign config cannot reset target or any other row']=function(){$a=s41_new('config-a');$b=s41_new('config-b');$before=s41_row($b);list($status,$j)=s41_close($b,$a['proof']);m0_assert(!$j['success']&&s41_row($a)&&s41_row($b)===$before,'Cross config');};
$tests['Same config foreign fingerprint cannot use another row capability']=function(){global $wpdb;$a=s41_new('same-config');$b=EIPSI_Randomization_Assignment_Service::resolve($a['config'],s41_config(),'fp_s41_other');$target=array('config'=>$a['config'],'fp'=>'fp_s41_other','proof'=>$b['reset_capability'],'id'=>$b['assignment_id']);list($status,$j)=s41_close($target,$a['proof']);m0_assert(!$j['success']&&s41_row($a)&&s41_row($target),'Cross assignment');};
$tests['Expired authentic capability fails closed']=function(){$r=s41_new('expired');$parts=explode('.',$r['proof']);$c=json_decode(base64_decode($parts[0]),true);$c['expires']=time()-1;$p=base64_encode(wp_json_encode($c));list($status,$j)=s41_close($r,$p.'.'.hash_hmac('sha256',$p,wp_salt('auth')));m0_assert(!$j['success']&&s41_row($r),'Expired accepted');};
$tests['Reload existing row never issues capability by fingerprint']=function(){$r=s41_new('reload');$again=EIPSI_Randomization_Assignment_Service::resolve($r['config'],s41_config(),$r['fp']);m0_assert($again['assignment_id']===$r['id']&&$again['reset_capability']==='','Guessed fingerprint minted proof');list($status,$j)=s41_close($r);m0_assert($j['success'],'Retained credential');};
$tests['Pre-S41 modern row has no unsafe fingerprint proof recovery']=function(){$r=array('config'=>'s41-preexisting','fp'=>'fp_s41_preexisting');$GLOBALS['s41_keys'][$r['config']]=true;m0_assert(EIPSI_Randomization_Assignment_Service::eipsi_create_assignment($r['config'],$r['fp'],$GLOBALS['s41_posts'][0]),'Old fixture');$again=EIPSI_Randomization_Assignment_Service::resolve($r['config'],s41_config(),$r['fp']);$r['id']=$again['assignment_id'];$r['proof']='';m0_assert($again['reset_capability']==='','Unsafe recovery');list($status,$j)=s41_close($r);m0_assert(!$j['success']&&s41_row($r),'Legacy fallback');};
$tests['Second close does not claim a nonexistent deletion']=function(){$r=s41_new('second');m0_assert(s41_close($r)[1]['success'],'First');list($status,$j)=s41_close($r);m0_assert($status===403&&!$j['success'],'Zero affected success');};
$tests['New assignment after close rejects replay of old capability']=function(){$a=s41_new('replay');m0_assert(s41_close($a)[1]['success'],'Close');$b=EIPSI_Randomization_Assignment_Service::resolve($a['config'],s41_config(),$a['fp']);$r=array('config'=>$a['config'],'fp'=>$a['fp'],'id'=>$b['assignment_id'],'proof'=>$b['reset_capability']);m0_assert($r['id']!==$a['id']&&$r['proof']!==$a['proof'],'New incarnation');list($status,$j)=s41_close($r,$a['proof']);m0_assert(!$j['success']&&s41_row($r),'Old proof deleted new row');m0_assert(s41_close($r)[1]['success'],'New own close');};
$tests['DELETE SQL failure never confirms close or removes rotation cookie']=function(){global $wpdb;$r=s41_new('sql-delete');$filter=function($sql){return preg_match('/^\s*DELETE FROM.*eipsi_randomization_assignments/i',$sql)?'SELECT s41_missing_delete_column':$sql;};$cookie='eipsi_rotation_'.$r['config'];$_COOKIE[$cookie]='1';$before=s41_row($r);$old=$wpdb->suppress_errors(true);add_filter('query',$filter);try{$ok=s41_direct($r);}finally{remove_filter('query',$filter);$wpdb->suppress_errors($old);}m0_assert(!$ok&&s41_row($r)===$before&&isset($_COOKIE[$cookie]),'SQL false success');};
$tests['Lookup failure cannot mint proof for an existing row']=function(){global $wpdb;$r=s41_new('sql-read');$fired=false;$filter=function($sql)use(&$fired){if(!$fired&&preg_match('/^\s*SELECT \* FROM.*eipsi_randomization_assignments/i',$sql)){$fired=true;return 'SELECT s41_missing_lookup_column';}return $sql;};$old=$wpdb->suppress_errors(true);add_filter('query',$filter);try{$again=EIPSI_Randomization_Assignment_Service::resolve($r['config'],s41_config(),$r['fp']);}finally{remove_filter('query',$filter);$wpdb->suppress_errors($old);}m0_assert($fired&&is_wp_error($again)&&s41_row($r),'Lookup failed open');};
$tests['Rotation reuses row and existing proof without reissuing one']=function(){$r=s41_new('rotation',false);$again=EIPSI_Randomization_Assignment_Service::resolve($r['config'],s41_config(false),$r['fp']);m0_assert($again['assignment_id']===$r['id']&&$again['reset_capability']==='','Rotation escalated ownership');m0_assert(s41_close($r)[1]['success'],'Rotation own reset');};
$tests['WordPress authenticated browser still requires and can use own capability']=function(){$r=s41_new('wp-auth');m0_assert(!s41_close($r,'',true)[1]['success'],'WP login alone authorized tracking');m0_assert(s41_close($r,null,true)[1]['success'],'Authenticated own capability');};
$tests['Shortcode emits proof only for creation and marks personalized output uncached']=function(){$config='s41-shortcode';$GLOBALS['s41_keys'][$config]=true;$form=$GLOBALS['s41_posts'][0];update_post_meta($form,'_randomization_config_'.$config,s41_config());$_COOKIE['eipsi_fingerprint']='fp_s41_shortcode';$html=do_shortcode('[eipsi_randomization template="'.$form.'" config="'.$config.'"]');m0_assert(preg_match('/data-reset-capability="([^"]+)"/',$html,$m)&&html_entity_decode($m[1])!==''&&DONOTCACHEPAGE,'New shortcode proof');$again=do_shortcode('[eipsi_randomization template="'.$form.'" config="'.$config.'"]');m0_assert(strpos($again,'data-reset-capability=""')!==false&&strpos($again,'data-reset-assignment-id=')!==false,'Reload reissued proof');$_COOKIE=array();};
require __DIR__.'/concurrency.php';
foreach(array(array('close','close'),array('close','invalid'),array('close','resolve'),array('close','create'))as$modes){$tests['Concurrent '.implode(' vs ',$modes).' respects row-bound ownership']=function()use($modes){$r=s41_new('race-'.implode('-',$modes));$out=s41_concurrent($r,$modes);$wins=0;foreach($out as$i=>$o){if($modes[$i]==='close'&&$o===true)$wins++;if($modes[$i]==='invalid')m0_assert($o===false,'Invalid close won');}m0_assert($wins===1,'Exactly one legitimate deletion must win');$current=EIPSI_Randomization_Assignment_Service::eipsi_get_existing_assignment($r['config'],$r['fp']);if($current){m0_assert((int)$current['id']!==$r['id']&&!s41_direct($r),'Old proof deleted replacement');}};}
$tests['DELETE failure over HTTP returns error and preserves victim row']=function(){$r=s41_new('sql-http');$before=s41_row($r);update_option('eipsi_s41_delete_sql_failure',true,false);try{list($status,$j)=s41_close($r);m0_assert(!$j['success']&&s41_row($r)===$before,'HTTP false success');}finally{delete_option('eipsi_s41_delete_sql_failure');}};
$tests['Participant Auth cookie reinforces no tracking-only reset and preserves own capability flow']=function(){global $wpdb;$study=999503;$pid=999507;m0_assert(!$wpdb->get_var("SELECT id FROM {$wpdb->prefix}survey_studies WHERE id=999503")&&!$wpdb->get_var("SELECT id FROM {$wpdb->prefix}survey_participants WHERE id=999507"),'Auth fixture collision');try{m0_assert($wpdb->insert($wpdb->prefix.'survey_studies',array('id'=>$study,'study_code'=>'s41-auth','study_name'=>'S41 Auth','status'=>'active','config'=>'{}'))===1,'Study');m0_assert($wpdb->insert($wpdb->prefix.'survey_participants',array('id'=>$pid,'survey_id'=>$study,'email'=>'s41-auth@example.invalid','is_active'=>1,'consent_decision'=>'accepted','created_at'=>current_time('mysql')))===1,'Participant');$session=EIPSI_Auth_Service::create_session($pid,$study);m0_assert($session['success'],'Session');$r=s41_new('participant-auth');m0_assert(!s41_close($r,'',false,$session)[1]['success'],'Auth alone closed fingerprint assignment');m0_assert(s41_close($r,null,false,$session)[1]['success'],'Authenticated legitimate reset');}finally{$wpdb->delete($wpdb->prefix.'survey_sessions',array('survey_id'=>$study));$wpdb->delete($wpdb->prefix.'survey_participants',array('id'=>$pid));$wpdb->delete($wpdb->prefix.'survey_studies',array('id'=>$study));}};
